LittleWeebLibrary.EventArguments.WebSocketEventArgs Class Reference
Public Member Functions
override string ToString ()
Properties
string Message [get, set]
Detailed Description
Definition at line 5 of file WebSocketEventArgs.cs.
Member Function Documentation
ToString()
override string LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString ()
Definition at line 8 of file WebSocketEventArgs.cs.
Referenced by LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent(), and LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            string toReturn = string.Empty;
            toReturn += "Message: " + Message + Environment.NewLine;
            return toReturn;
        }
Property Documentation
Message
string LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message [get], [set]
Definition at line 7 of file WebSocketEventArgs.cs.
Referenced by LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent(), and LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
{ get; set; }
The documentation for this class was generated from the following file:
EventArguments/WebSocketEventArgs.cs