LittleWeebLibrary.Handlers.WebSocketHandler Class Reference
Public Member Functions
WebSocketHandler (ISettingsHandler settingsHandler, IDebugHandler debugHandler)
async Task SendMessage (string message)
void SetIrcSettings (IrcSettings settings)
void SetLittleWeebSettings (LittleWeebSettings settings)
void StartServer ()
async Task StopServer ()
Events
EventHandler< WebSocketEventArgs > OnWebSocketEvent
Private Member Functions
async void OnWebSocketServerEvent (object sender, WebSocketEventArg args)
Private Attributes
List< string > ClientIds
readonly IDebugHandler DebugHandler
LittleWeebSettings LittleWeebSettings
SimpleWebSocketServer Server
Detailed Description
Definition at line 23 of file WebSocketHandler.cs.
Constructor & Destructor Documentation
WebSocketHandler()
LittleWeebLibrary.Handlers.WebSocketHandler.WebSocketHandler (ISettingsHandler settingsHandler, IDebugHandler debugHandler)
Definition at line 36 of file WebSocketHandler.cs.
References LittleWeebLibrary.Handlers.ISettingsHandler.GetLittleWeebSettings(), and LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            LittleWeebSettings = settingsHandler.GetLittleWeebSettings();
            DebugHandler = debugHandler;
        }
Member Function Documentation
SetLittleWeebSettings()
void LittleWeebLibrary.Handlers.WebSocketHandler.SetLittleWeebSettings (LittleWeebSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 43 of file WebSocketHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetLittleWeebSettings Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            LittleWeebSettings = settings;
        }
StartServer()
void LittleWeebLibrary.Handlers.WebSocketHandler.StartServer ()
Implements LittleWeebLibrary.Handlers.IWebSocketHandler.
Definition at line 50 of file WebSocketHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.Port, and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.StartUp.Start().
        {
            DebugHandler.TraceMessage("StartServer Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                ClientIds = new List<string>();
                Server = new SimpleWebSocketServer(new SimpleWebSocketServerSettings()
                {
                    port = LittleWeebSettings.Port,
                    bufferSize = 65535
                });
                Server.WebsocketServerEvent += OnWebSocketServerEvent;
                Server.StartServer();
                DebugHandler.TraceMessage("Web Socket Server Started!",
      DebugSource.TASK, DebugType.INFO);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
            }
        }
SendMessage()
async Task LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage (string message)
Implements LittleWeebLibrary.Handlers.IWebSocketHandler.
Definition at line 73 of file WebSocketHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.AbortDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownloads(), LittleWeebLibrary.Services.InfoApiWebSocketService.AddRule(), LittleWeebLibrary.Services.VersionWebSocketService.CheckVersion(), LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.DirectoryWebSocketService.CreateDirectory(), LittleWeebLibrary.Services.DirectoryWebSocketService.DeleteDirectory(), LittleWeebLibrary.Services.DataBaseWebSocketService.DeleteDocument(), LittleWeebLibrary.Services.FileWebSocketService.DeleteFile(), LittleWeebLibrary.Services.IrcWebSocketService.DisableSendMessage(), LittleWeebLibrary.Services.IrcWebSocketService.Disconnect(), LittleWeebLibrary.Services.IrcWebSocketService.EnableSendMessage(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeEpisodes(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeProfile(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetBotList(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetCollection(), LittleWeebLibrary.Services.DownloadWebSocketService.GetCurrentFileHistory(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.Services.IrcWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetCurrentlyAiring(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDirectories(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetDocument(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDrives(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetFilesForAnime(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetFreeSpace(), LittleWeebLibrary.Services.DownloadWebSocketService.OnDownloadUpdateEvent(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientConnectionStatusEvent(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientMessageEvent(), LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Services.FileWebSocketService.OpenFile(), LittleWeebLibrary.Services.DownloadWebSocketService.Openfullfilepath(), LittleWeebLibrary.Services.DownloadWebSocketService.RemoveDownload(), LittleWeebLibrary.Services.InfoApiWebSocketService.SearchKitsu(), LittleWeebLibrary.Services.IrcWebSocketService.SendMessage(), LittleWeebLibrary.Services.SettingsWebSocketService.Setfullfilepath(), LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Services.DataBaseWebSocketService.StoreDocument(), and LittleWeebLibrary.Services.DataBaseWebSocketService.UpdateDocument().
        {
            DebugHandler.TraceMessage("SendMessage Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(message,
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                if (await Server.SendTextMessageAsync(message))
                {
                    DebugHandler.TraceMessage("Succesfully send message to
       WebSocket Client.", DebugSource.TASK, DebugType.INFO);
                }
                else
                {
                    DebugHandler.TraceMessage("Could not send message to WebSocket
       Client.", DebugSource.TASK, DebugType.WARNING);
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
StopServer()
async Task LittleWeebLibrary.Handlers.WebSocketHandler.StopServer ()
Implements LittleWeebLibrary.Handlers.IWebSocketHandler.
Definition at line 98 of file WebSocketHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.StartUp.Stop().
        {
            DebugHandler.TraceMessage("StopServer Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                if (await Server.StopAllAsync())
                {
                    DebugHandler.TraceMessage("Succesfully closed websocket
       connection to client(s), stopped websocket server.", DebugSource.TASK,
      DebugType.INFO);
                }
                else
                {
                    DebugHandler.TraceMessage("Could not stop WebSocket connection
       with client, websocket server still running.", DebugSource.TASK,
      DebugType.WARNING);
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
OnWebSocketServerEvent()
async void LittleWeebLibrary.Handlers.WebSocketHandler.OnWebSocketServerEvent (object sender, WebSocketEventArg args) [private]
Definition at line 118 of file WebSocketHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.Local, LittleWeebLibrary.Models.JsonReceivedResponse.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketServerEvent Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                if (args.isOpen)
                {
                    if (!ClientIds.Contains(args.clientId))
                    {
                        DebugHandler.TraceMessage("Client with id " + args.clientId
       + " from " + args.clientBaseUrl + " connected!", DebugSource.TASK,
      DebugType.INFO);
                        ClientIds.Add(args.clientId);
                        await SendMessage(new JsonWelcome()
                        {
                            local = LittleWeebSettings.Local
                        }.ToJson());
                    }
                }
                if (args.isClosed)
                {
                    if (ClientIds.Contains(args.clientId))
                    {
                        DebugHandler.TraceMessage("Client with id " + args.clientId
       + " from " + args.clientBaseUrl + " disconnected!", DebugSource.TASK,
      DebugType.INFO);
                        ClientIds.Remove(args.clientId);
                    }
                }
                if (args.data != null && args.isText)
                {
                    string received = Encoding.ASCII.GetString(args.data);
                    DebugHandler.TraceMessage(received,
      DebugSource.TASK, DebugType.INFO);
                    OnWebSocketEvent?.Invoke(this, new
      WebSocketEventArgs() { Message = received });
                    await SendMessage(new JsonReceivedResponse()
                    {
                        received = received
                    }.ToJson());
                }
                if (args.isPing)
                {
                    DebugHandler.TraceMessage("IsPing: " + args.isPing.ToString(),
      DebugSource.TASK, DebugType.INFO);
                    await Server.SendPongMessageAsync();
                }
                if (args.isPong)
                {
                    DebugHandler.TraceMessage("IsPong: " + args.isPing.ToString(),
      DebugSource.TASK, DebugType.INFO);
                    await Server.SendPingMessageAsync();
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
SetIrcSettings()
void LittleWeebLibrary.Handlers.WebSocketHandler.SetIrcSettings (IrcSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 185 of file WebSocketHandler.cs.
        {
        }
Member Data Documentation
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.WebSocketHandler.DebugHandler [private]
Definition at line 28 of file WebSocketHandler.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Handlers.WebSocketHandler.LittleWeebSettings [private]
Definition at line 30 of file WebSocketHandler.cs.
Server
SimpleWebSocketServer LittleWeebLibrary.Handlers.WebSocketHandler.Server [private]
Definition at line 32 of file WebSocketHandler.cs.
ClientIds
List<string> LittleWeebLibrary.Handlers.WebSocketHandler.ClientIds [private]
Definition at line 34 of file WebSocketHandler.cs.
Event Documentation
OnWebSocketEvent
EventHandler<WebSocketEventArgs> LittleWeebLibrary.Handlers.WebSocketHandler.OnWebSocketEvent
Definition at line 25 of file WebSocketHandler.cs.
Referenced by LittleWeebLibrary.Controllers.BaseWebSocketController.BaseWebSocketController().
The documentation for this class was generated from the following file:
Handlers/WebSocketHandler.cs