LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController Class Reference
Public Member Functions
VersionWebSocketController (IWebSocketHandler webSocketHandler, IVersionWebSocketService versionWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IVersionWebSocketService VersionWebSocketService
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 14 of file VersionWebSocketController.cs.
Constructor & Destructor Documentation
VersionWebSocketController()
LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.VersionWebSocketController (IWebSocketHandler webSocketHandler, IVersionWebSocketService versionWebSocketService, IDebugHandler debugHandler)
Definition at line 22 of file VersionWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            VersionWebSocketService = versionWebSocketService;
            WebSocketHandler = webSocketHandler;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 31 of file VersionWebSocketController.cs.
References LittleWeebLibrary.Services.VersionWebSocketService.CheckVersion(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try
                {
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        switch (action)
                        {
                            case "check_version":
                                VersionWebSocketService.
      CheckVersion();
                                break;
                        }
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
VersionWebSocketService
readonly IVersionWebSocketService LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.VersionWebSocketService [private]
Definition at line 18 of file VersionWebSocketController.cs.
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.WebSocketHandler [private]
Definition at line 19 of file VersionWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.DebugHandler [private]
Definition at line 20 of file VersionWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/VersionWebSocketController.cs