LittleWeebLibrary.Services.InfoApiWebSocketService Class Reference
Public Member Functions
InfoApiWebSocketService (IWebSocketHandler webSocketHandler, IAnimeProfileHandler infoApiHandler, INiblHandler niblHandler, IKitsuHandler kitsuHandler, IAnimeRuleHandler animeRuleHandler, IDataBaseHandler dataBaseHandler, IDebugHandler debugHandler)
async Task AddRule (JObject query)
async Task GetAllCategories (JObject query)
async Task GetAllGenres (JObject query)
async Task GetAnimeEpisodes (JObject query)
async Task GetAnimeProfile (JObject query)
async Task GetBotList (JObject query)
async Task GetCurrentlyAiring ()
async Task GetCurrentlyAiring (JObject query)
async Task GetFilesForAnime (JObject query)
async Task SearchKitsu (JObject query)
Private Attributes
readonly IAnimeProfileHandler AnimeProfileHandler
readonly IAnimeRuleHandler AnimeRuleHandler
readonly IDataBaseHandler DataBaseHandler
readonly IDebugHandler DebugHandler
readonly IKitsuHandler KitsuHandler
readonly INiblHandler NiblHandler
readonly IWebSocketHandler WebSocketHandler
WeebFileNameParser WeebFileNameParser
Detailed Description
Definition at line 28 of file InfoApiWebSocketService.cs.
Constructor & Destructor Documentation
InfoApiWebSocketService()
LittleWeebLibrary.Services.InfoApiWebSocketService.InfoApiWebSocketService (IWebSocketHandler webSocketHandler, IAnimeProfileHandler infoApiHandler, INiblHandler niblHandler, IKitsuHandler kitsuHandler, IAnimeRuleHandler animeRuleHandler, IDataBaseHandler dataBaseHandler, IDebugHandler debugHandler)
Definition at line 40 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            WebSocketHandler = webSocketHandler;
            AnimeProfileHandler = infoApiHandler;
            NiblHandler = niblHandler;
            KitsuHandler = kitsuHandler;
            AnimeRuleHandler = animeRuleHandler;
            DataBaseHandler = dataBaseHandler;
            DebugHandler = debugHandler;
            WeebFileNameParser = new WeebFileNameParser();
        }
Member Function Documentation
GetAnimeProfile()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeProfile (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 55 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeProfile(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonKitsuAnimeInfo.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetAnimeProfile Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Query: " + query.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            string id = query.Value<string>("id");
            bool noCache = false;
            int amountPerPage = 40;
            if (query.ContainsKey("no_cache"))
            {
                noCache = query.Value<bool>("no_cache");
            }
            if (query.ContainsKey("amount_per_page"))
            {
                amountPerPage = query.Value<int>("amount_per_page");
            }
            JsonKitsuAnimeInfo info = await
      AnimeProfileHandler.GetAnimeProfile(id, amountPerPage, noCache);
            await WebSocketHandler.SendMessage(info.
      ToJson());
        }
GetFilesForAnime()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetFilesForAnime (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 80 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.NiblHandler.SearchNibl(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonNiblSearchResult.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetFilesForAnime Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Query: " + query.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                JArray animeNames = query.Value<JArray>("titles");
                JObject returnresult = new JObject();
                foreach (string title in animeNames)
                {
                    Dictionary<string, string> parsed = WeebFileNameParser.
      ParseFullString(title);
                    string searchQuery = parsed["MainAnimeTitle"];
                    if (parsed["SubAnimeTitle"].Length > 0)
                    {
                        searchQuery += " " + parsed["SubAnimeTitle"];
                    }
                    JObject result = await NiblHandler.SearchNibl(searchQuery);
                    returnresult.Add(title, result);
                }
                JsonNiblSearchResult resultoreturn = new
      JsonNiblSearchResult()
                {
                    result = returnresult
                };
                await WebSocketHandler.SendMessage(resultoreturn.
      ToJson());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Failed to get files for requested
       anime(s): " + e.ToString(), DebugSource.TASK, DebugType.WARNING);
                JsonError jsonError = new JsonError
                {
                    errortype = "Exception",
                    errormessage = "failed to get files for requested anime(s)",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToString());
            }
            
        }
GetCurrentlyAiring() [1/2]
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetCurrentlyAiring ()
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 133 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonCurrentlyAiring.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetCurrentlyAiring Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                JsonCurrentlyAiring currentlyAiring = await
      AnimeProfileHandler.GetCurrentlyAiring();
                await WebSocketHandler.SendMessage(currentlyAiring.
      ToJson());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "get_currently_airing_error",
                    errormessage = "Could not get currently airing.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
GetCurrentlyAiring() [2/2]
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetCurrentlyAiring (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 161 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonCurrentlyAiring.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("GetCurrentlyAiring Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                JsonCurrentlyAiring currentlyAiring = new
      JsonCurrentlyAiring();
                bool noCache = false;
                int bot = 21;
                bool noniblfoundresult = false;
                bool cached = false;
                if (query.ContainsKey("no_cache"))
                {
                    noCache = query.Value<bool>("no_cache");
                }
                if (query.ContainsKey("no_nibl_found_anime"))
                {
                    noniblfoundresult = query.Value<bool>("no_nibl_found_anime");
                }
                if (query.ContainsKey("bot_id"))
                {
                    bot = query.Value<int>("bot_id");
                }
                if (query.ContainsKey("cached"))
                {
                    cached = query.Value<bool>("cached");
                }
                currentlyAiring = await AnimeProfileHandler.
      GetCurrentlyAiring(noniblfoundresult, bot, noCache, cached);
                await WebSocketHandler.SendMessage(currentlyAiring.
      ToJson());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "get_currently_airing_error",
                    errormessage = "Could not get currently airing.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
GetAnimeEpisodes()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeEpisodes (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 214 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeEpisodes(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonKitsuAnimeInfo.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetAnimeEpisodes Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string id = query.Value<string>("id");
            bool noCache = false;
            bool cached = false;
            int amountPerPage = 26;
            if (query.ContainsKey("no_cache"))
            {
                noCache = query.Value<bool>("no_cache");
            }
            if (query.ContainsKey("amount_per_page"))
            {
                amountPerPage = query.Value<int>("amount_per_page");
            }
            if (query.ContainsKey("cached"))
            {
                cached = query.Value<bool>("cached");
            }
            JsonKitsuAnimeInfo info = new JsonKitsuAnimeInfo();
            info = await AnimeProfileHandler.GetAnimeEpisodes(id,
      amountPerPage, noCache, cached);
            await WebSocketHandler.SendMessage(info.
      ToJson());
        }
SearchKitsu()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.SearchKitsu (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 246 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.KitsuHandler.SearchAnime(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonKistuSearchResult.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("SearchKitsu Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            Dictionary<string, string> listWithQueries = new Dictionary<string, string>();
            if (query.ContainsKey("query")){
                DebugHandler.TraceMessage("Has query parameters: " + query.Value<
      JArray>("query").ToString(), DebugSource.TASK, DebugType.INFO);
                foreach (JObject val in query.Value<JArray>("query"))
                {
                    DebugHandler.TraceMessage("Adding query for " + val.ToString(),
       DebugSource.TASK, DebugType.INFO);
                    JToken token = val.First;
                    foreach (KeyValuePair<string, JToken> prop in val)
                    {
                        DebugHandler.TraceMessage("Adding query for " + prop.Key+ "
       with value: " + prop.Value.ToString(), DebugSource.TASK, DebugType.INFO);
                        listWithQueries.Add(prop.Key, prop.Value.ToString());
                    }
                }
            }
            if (query.ContainsKey("page") && !query.ContainsKey("pages"))
            {
                JsonKistuSearchResult searchResult = await
      KitsuHandler.SearchAnime(query.Value<string>("search"), listWithQueries, query.Value
      <int>("page"));
                await WebSocketHandler.SendMessage(searchResult.
      ToJson());
            }
            else if (query.ContainsKey("page") && query.ContainsKey("pages"))
            {
                JsonKistuSearchResult searchResult = await
      KitsuHandler.SearchAnime(query.Value<string>("search"), listWithQueries, query.Value
      <int>("page"), query.Value<int>("pages"));
                await WebSocketHandler.SendMessage(searchResult.
      ToJson());
            }
            else
            {
                JsonKistuSearchResult searchResult = await
      KitsuHandler.SearchAnime(query.Value<string>("search"), listWithQueries);
                await WebSocketHandler.SendMessage(searchResult.
      ToJson());
            }
        }
AddRule()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.AddRule (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 288 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.AnimeRuleHandler.AddRules(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonSuccess.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage(" AddRule Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string animeid = query.Value<string>("id");
            JObject rules = query.Value<JObject>("rules");
            bool succes = await AnimeRuleHandler.AddRules(rules, animeid);
            if (succes)
            {
                JsonSuccess jsonSuccess = new JsonSuccess()
                {
                    message = "Succesfully added rules to anime with id: " + animeid
                };
                await WebSocketHandler.SendMessage(jsonSuccess.
      ToJson());
            }
            else
            {
                JsonError error = new JsonError()
                {
                    type = "add_rule_error",
                    errormessage = "Could not add rule to anime with id: " + animeid,
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
GetAllGenres()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 318 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.KitsuHandler.GetAllGenres(), LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject(), LittleWeebLibrary.Models.JsonKistuGenres.result, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject(), LittleWeebLibrary.Models.JsonKistuGenres.ToJObject(), LittleWeebLibrary.Models.JsonKistuGenres.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage(" GetAllGenres Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JObject db_result = await DataBaseHandler.GetJObject("kitsu", "genres"
      );
            bool noCache = false;
            if (query.ContainsKey("no_cache"))
            {
                noCache = query.Value<bool>("no_cache");
            }
            if (db_result.Count > 0 && !noCache)
            {
                await WebSocketHandler.SendMessage(db_result.ToString());
            }
            else
            {
                JsonKistuGenres genres = new JsonKistuGenres()
                {
                    result = await KitsuHandler.GetAllGenres()
                };
                if (genres.result.Count > 0)
                {
                    await DataBaseHandler.StoreJObject("kitsu", genres.
      ToJObject(), "genres");
                    await WebSocketHandler.SendMessage(genres.
      ToJson());
                }
                else
                {
                    JsonError error = new JsonError()
                    {
                        type = "kitsu_genres_error",
                        errormessage = "Failed to retrieve genres from kitsu.",
                        errortype = "warning"
                    };
                    await WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
           
        }
GetAllCategories()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 363 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.KitsuHandler.GetAllCategories(), LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject(), LittleWeebLibrary.Models.JsonKistuCategories.result, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject(), LittleWeebLibrary.Models.JsonKistuCategories.ToJObject(), LittleWeebLibrary.Models.JsonKistuCategories.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage(" GetAllCategories Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JObject db_result = await DataBaseHandler.GetJObject("kitsu", "
      categories");
            bool noCache = false;
            if (query.ContainsKey("no_cache"))
            {
                noCache = query.Value<bool>("no_cache");
            }
            if (db_result.Count > 0 && !noCache)
            {
                await WebSocketHandler.SendMessage(db_result.ToString());
            }
            else
            {
                JsonKistuCategories categories = new
      JsonKistuCategories()
                {
                    result = await KitsuHandler.GetAllCategories()
                };
                if (categories.result.Count > 0)
                {
                    await DataBaseHandler.StoreJObject("kitsu", categories.
      ToJObject(), "categories");
                    await WebSocketHandler.SendMessage(categories.
      ToJson());
                }
                else
                {
                    JsonError error = new JsonError()
                    {
                        type = "kitsu_categories_error",
                        errormessage = "Failed to retrieve categories from kitsu.",
                        errortype = "warning"
                    };
                    await WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
                
        }
GetBotList()
async Task LittleWeebLibrary.Services.InfoApiWebSocketService.GetBotList (JObject query)
Implements LittleWeebLibrary.Services.IInfoApiWebSocketService.
Definition at line 410 of file InfoApiWebSocketService.cs.
References LittleWeebLibrary.Handlers.NiblHandler.GetBotList(), LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject(), LittleWeebLibrary.Models.JsonNiblBotList.result, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject(), LittleWeebLibrary.Models.JsonNiblBotList.ToJObject(), LittleWeebLibrary.Models.JsonNiblBotList.ToJson(), and LittleWeebLibrary.Models.JsonError.ToJson().
Referenced by LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent().
        {
            JsonNiblBotList botlist = new JsonNiblBotList()
            {
                result = await NiblHandler.GetBotList()
            };
            bool noCache = false;
            if (query.ContainsKey("no_cache"))
            {
                noCache = query.Value<bool>("no_cache");
            }
            JObject db_result = await DataBaseHandler.GetJObject("nibl", "botlist"
      );
            if (db_result.Count > 0 && !noCache)
            {
                await WebSocketHandler.SendMessage(db_result.ToString());
            }
            else
            {
                if (botlist.result.Count > 0)
                {
                    await DataBaseHandler.StoreJObject("nibl", botlist.
      ToJObject(), "botlist");
                    await WebSocketHandler.SendMessage(botlist.
      ToJson());
                }
                else
                {
                    JsonError error = new JsonError()
                    {
                        type = "nibl_botlist_error",
                        errormessage = "Failed to retrieve categories from nibl.",
                        errortype = "warning"
                    };
                    await WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
        }
Member Data Documentation
AnimeProfileHandler
readonly IAnimeProfileHandler LittleWeebLibrary.Services.InfoApiWebSocketService.AnimeProfileHandler [private]
Definition at line 31 of file InfoApiWebSocketService.cs.
NiblHandler
readonly INiblHandler LittleWeebLibrary.Services.InfoApiWebSocketService.NiblHandler [private]
Definition at line 32 of file InfoApiWebSocketService.cs.
KitsuHandler
readonly IKitsuHandler LittleWeebLibrary.Services.InfoApiWebSocketService.KitsuHandler [private]
Definition at line 33 of file InfoApiWebSocketService.cs.
AnimeRuleHandler
readonly IAnimeRuleHandler LittleWeebLibrary.Services.InfoApiWebSocketService.AnimeRuleHandler [private]
Definition at line 34 of file InfoApiWebSocketService.cs.
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Services.InfoApiWebSocketService.WebSocketHandler [private]
Definition at line 35 of file InfoApiWebSocketService.cs.
DataBaseHandler
readonly IDataBaseHandler LittleWeebLibrary.Services.InfoApiWebSocketService.DataBaseHandler [private]
Definition at line 36 of file InfoApiWebSocketService.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Services.InfoApiWebSocketService.DebugHandler [private]
Definition at line 37 of file InfoApiWebSocketService.cs.
WeebFileNameParser
WeebFileNameParser LittleWeebLibrary.Services.InfoApiWebSocketService.WeebFileNameParser [private]
Definition at line 38 of file InfoApiWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/InfoApiWebSocketService.cs