LittleWeebLibrary.Handlers.KitsuHandler Class Reference
Public Member Functions
KitsuHandler (IDebugHandler debugHandler)
async Task< JArray > GetAllCategories ()
async Task< JArray > GetAllGenres ()
async Task< JObject > GetAnime (string animeId)
async Task< JArray > GetCategories (string animeId)
async Task< JArray > GetCurrentlyAiring ()
async Task< JObject > GetEpisode (string animeId, int episodeNumber)
async Task< JArray > GetEpisodes (string animeId, int page=0, int pages=-1, int results=20, string order=`ASC`)
async Task< JsonKitsuAnimeInfo > GetFullAnime (string animeId, int amountEpisodesPerPage=26)
async Task< JArray > GetGenres (string animeId)
async Task< JArray > GetRelations (string animeId)
async Task< JsonKistuSearchResult > SearchAnime (string search, Dictionary< string, string > queryList, int page=0, int pages=1)
Private Member Functions
async Task< string > Get (string url)
async Task< JObject > GetEpisodesFromKitsu (string animeId, int page, int offset)
Private Attributes
readonly IDebugHandler DebugHandler
Detailed Description
Definition at line 31 of file KitsuHandler.cs.
Constructor & Destructor Documentation
KitsuHandler()
LittleWeebLibrary.Handlers.KitsuHandler.KitsuHandler (IDebugHandler debugHandler)
Definition at line 36 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
        }
Member Function Documentation
SearchAnime()
async Task<JsonKistuSearchResult> LittleWeebLibrary.Handlers.KitsuHandler.SearchAnime (string search, Dictionary< string, string > queryList, int page = 0, int pages = 1)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 42 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.CurrentlyAiringAsync(), and LittleWeebLibrary.Services.InfoApiWebSocketService.SearchKitsu().
                                                                                                           
                                         {
            DebugHandler.TraceMessage("SearchAnime Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Search: " + search + ", page: " + page.
      ToString() + ", pages: " + pages.ToString(), DebugSource.TASK, DebugType.PARAMETERS);
            JArray array = new JArray();
            
            string query = "";
            foreach (KeyValuePair<string, string> attributeValue in queryList)
            {
                query += "&filter[" + attributeValue.Key + "]=" + attributeValue.Value;
            }
            if (search != string.Empty)
            {
                query = "&filter[text]=" + search + query;
            }
            string searchresult = await Get("anime?" + query.Substring(1) + "
      &fields[anime]=canonicalTitle,averageRating,subtype,status,coverImage,posterImage,abbreviatedTitles,titles&page[limit]=20&page[offset]=
      " + (page * 20).ToString());
            if (searchresult.Contains("failed:"))
            {
                JsonKistuSearchResult resultfail = new
      JsonKistuSearchResult()
                {
                    result = array
                };
                return resultfail;
            }
            JObject searchresultjobject = JObject.Parse(searchresult);
            int totalPages = (int)Math.Ceiling(((double)((searchresultjobject["meta"].Value<int>("count"))
      / (double)20) + 0.5));
            if (pages == -1)
            {
                pages = totalPages;
            }
            array.Merge(searchresultjobject.Value<JArray>("data"));
            for (int i = 1; i < pages; i++) {
                searchresult = await Get("anime?" + query.Substring(1) + "
      &fields[anime]=canonicalTitle,averageRating,subtype,status,coverImage,posterImage,abbreviatedTitles,titles&page[limit]=20&page[offset]=" +
       ((page + i - 1) * 20).ToString());
                if (searchresult.Contains("failed:"))
                {
                    break;
                }
                searchresultjobject = JObject.Parse(searchresult);
                array.Merge(searchresultjobject.Value<JArray>("data"));
                if ((i + page) >= totalPages)
                {
                    break;
                }
            }
            JsonKistuSearchResult result = new
      JsonKistuSearchResult()
            {
                result = array
            };
            return result;
        }
GetAnime()
async Task<JObject> LittleWeebLibrary.Handlers.KitsuHandler.GetAnime (string animeId)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 109 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("GetAnime Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Anime ID: " + animeId,
      DebugSource.TASK, DebugType.PARAMETERS);
            string anime = await Get("anime?filter[id]=" + animeId);
            if (anime.Contains("failed:"))
            {
                return new JObject();
            }
            else
            {
                return JObject.Parse(anime);
            }
        }
GetEpisodes()
async Task<JArray> LittleWeebLibrary.Handlers.KitsuHandler.GetEpisodes (string animeId, int page = 0, int pages = -1, int results = 20, string order = `ASC`)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 127 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("GetEpisodes Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("AnimeID: " + animeId + ", page: " + page.
      ToString() + ", pages: " + pages.ToString(), DebugSource.TASK, DebugType.PARAMETERS);
            string orderquery= "";
            if (order == "DESC")
            {
                orderquery = "-";
            }
            string episodes = await Get("episodes?filter[mediaType]=Anime&filter[media_id]=" + animeId +
       "&page[limit]=20&page[offset]=" + ((page) * results).ToString() + "&sort=" + orderquery + "number");
            JObject searchresultjobject = JObject.Parse(episodes);
            JArray array = new JArray();
            int totalPages = 1;
            if (pages == -1)
            {
                totalPages = (int)Math.Ceiling(((double)((searchresultjobject["meta"].Value<int>("count"))
      / (double)20) + 0.5));
                pages = totalPages;
            }
            List<Task<JObject>> tasks = new List<Task<JObject>>();
            array.Merge(searchresultjobject.Value<JArray>("data"));
            DebugHandler.TraceMessage("Amount of pages to interate: " + totalPages,
       DebugSource.TASK, DebugType.INFO);
            for (int i = 1; i < totalPages; i++)
            {
                if (episodes.Contains("failed:"))
                {
                    break;
                }
                
                tasks.Add(GetEpisodesFromKitsu(animeId, page, i));
                              
                if ((i + page) >= totalPages)
                {
                    break;
                }
            }
            Task.WaitAll(tasks.ToArray());
            foreach (Task<JObject> task in tasks)
            {
                array.Merge(task.Result.Value<JArray>("data"));
                task.Dispose();
            }
            return array;
        }
GetFullAnime()
async Task<JsonKitsuAnimeInfo> LittleWeebLibrary.Handlers.KitsuHandler.GetFullAnime (string animeId, int amountEpisodesPerPage = 26)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 189 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeProfile().
        {
            DebugHandler.TraceMessage("GetFullAnime Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Anime ID: " + animeId,
      DebugSource.TASK, DebugType.PARAMETERS);
            string anime = await Get("anime/" + animeId + "?include=episodes,genres,categories");
            JObject result = JObject.Parse(anime);
            JArray included = result.Value<JArray>("included");
            JArray genres = new JArray();
            JArray categories = new JArray();
            JArray episodes = new JArray();
            JArray mediaRelationships = new JArray();
            foreach (JObject include in included)
            {
                switch(include.Value<string>("type"))
                {
                    case "genres":
                        genres.Add(include);
                        break;
                    case "categories":
                        categories.Add(include);
                        break;
                    case "episodes":
                        episodes.Add(include);
                        break;
                }
            }
            mediaRelationships = await GetRelations(animeId);
            JArray episodePages = new JArray();
            JArray page = new JArray();
            int count = 0;
            foreach (JObject episode in episodes)
            {
                if (count >= amountEpisodesPerPage)
                {
                    episodePages.Add(page);
                    page = new JArray();
                    count = 0;
                }
                count++;
                page.Add(episode);
            }
            if (episodes.Count <= amountEpisodesPerPage)
            {
                episodePages.Add(page);
            }
            JsonKitsuAnimeInfo jsonKitsuAnimeInfo = new
      JsonKitsuAnimeInfo
            {
                anime_id = animeId,
                anime_episodes_per_page = amountEpisodesPerPage,
                anime_total_episode_pages = episodePages.Count,
                anime_info = result.Value<JObject>("data"),
                anime_relations = mediaRelationships,
                anime_categories = categories,
                anime_genres = genres,
                anime_episodes = episodePages
            };
            
           //DebugHandler.TraceMessage("Finished getting anime profile, making values 'episodeCount' &
       'total episode pages global': " +
       jsonKitsuAnimeInfo.anime_info["data"][0]["attributes"].Value<int>("episodeCount"), DebugSource.TASK, DebugType.PARAMETERS);
            return jsonKitsuAnimeInfo;
        }
GetRelations()
async Task<JArray> LittleWeebLibrary.Handlers.KitsuHandler.GetRelations (string animeId)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 263 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("GetRelations Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Anime ID: " + animeId,
      DebugSource.TASK, DebugType.PARAMETERS);
            
            string relations = await Get("media-relationships?filter[source_id]=" + animeId + "
      &filter[so
      urce_type]=Anime&fields[anime]=episodeCount,canonicalTitle,averageRating,subtype,status,coverImage,posterImage,abbreviatedTitles,titles&include=destination&sort=role");
            if (relations.Contains("failed:"))
            {
                return new JArray();
            }
            else
            {
                JObject result = JObject.Parse(relations);
                JArray data = result.Value<JArray>("data");
                JArray included = result.Value<JArray>("included");
                int i = 0;
                foreach (JObject roles in data)
                {
                    JObject anime = included[i].Value<JObject>();
                    anime.Add(new JProperty("role", roles["attributes"].Value<string>("role")));
                    included[i] = anime;
                    i++;
                }
                return included;
            }
        }
GetCurrentlyAiring()
async Task<JArray> LittleWeebLibrary.Handlers.KitsuHandler.GetCurrentlyAiring ()
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 299 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring().
        {
            DebugHandler.TraceMessage("GetCurrentlyAiring Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JArray array = new JArray();
            int totalPages = 2;
            List<Task<string>> tasks = new List<Task<string>>();
            string airing = await Get("
      anime?filter[status]=current&fields[anime]=canonicalTitle,averageR
      ating,subtype,status,coverImage,posterImage,abbreviatedTitles,titles&sort=-averageRating&page[limit]=20&page[offset]=" + (0 * 20).ToString());
            JObject airingresultjobject = JObject.Parse(airing);
            array.Merge(airingresultjobject.Value<JArray>("data"));
            totalPages = (int)(airingresultjobject["meta"].Value<int>("count") / 20 - 0.5);
            for (int i = 1; i < totalPages; i++)
            {
                if (airing.Contains("failed:"))
                {
                    break;
                }
                tasks.Add(Get("
      anime?filter[status]=current&fields[anime]=canonicalTitle,averageRating,subtype,status,coverImage,posterImage,abbreviatedTitles,titles&page[limit]=20&page[offset]=" + (i * 20).
      ToString()));
                if (i >= totalPages)
                {
                    break;
                }
            }
            Task.WaitAll(tasks.ToArray());
            foreach (Task<string> task in tasks)
            {
                airingresultjobject = JObject.Parse(task.Result);
                try
                {
                    array.Merge(airingresultjobject.Value<JArray>("data"));
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage("Failed merging data: " + e.ToString(
      ), DebugSource.TASK, DebugType.WARNING);
                }
                task.Dispose();
            }
            return array;
        }
GetGenres()
async Task<JArray> LittleWeebLibrary.Handlers.KitsuHandler.GetGenres (string animeId)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 356 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("GetGenres Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Anime ID: " + animeId,
      DebugSource.TASK, DebugType.PARAMETERS);
            string genres = await Get("anime/" + animeId + "/genres");
            if (genres.Contains("failed:"))
            {
                return new JArray();
            }
            else
            {
                return JObject.Parse(genres).Value<JArray>("data");
            }
        }
GetCategories()
async Task<JArray> LittleWeebLibrary.Handlers.KitsuHandler.GetCategories (string animeId)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 373 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("GetCategories Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Anime ID: " + animeId,
      DebugSource.TASK, DebugType.PARAMETERS);
            string categories = await Get("anime/" + animeId + "/categories");
            if (categories.Contains("failed:"))
            {
                return new JArray();
            }
            else
            {
                return JObject.Parse(categories).Value<JArray>("data");
            }
        }
GetEpisode()
async Task<JObject> LittleWeebLibrary.Handlers.KitsuHandler.GetEpisode (string animeId, int episodeNumber)
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 393 of file KitsuHandler.cs.
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.AnimeLatestEpisode().
        {
            string episode = await Get("episodes?filter[mediaType]=Anime&filter[media_id]=" + animeId +
      "&filter[number]=" + episodeNumber);
            if (episode.Contains("failed:"))
            {
                return new JObject();
            }
            else
            {
                JObject searchresultjobject = JObject.Parse(episode);
                return searchresultjobject["data"].Value<JObject>(0);
            }
        }
GetAllGenres()
async Task<JArray> LittleWeebLibrary.Handlers.KitsuHandler.GetAllGenres ()
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 408 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres().
        {
            DebugHandler.TraceMessage("GetAllGenres Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JArray array = new JArray();
            int totalPages = 0;
            List<Task<string>> tasks = new List<Task<string>>();
            string genres = await Get("genres?fields[genres]=name&page[limit]=20&page[offset]=" + (0 * 2
      0).ToString());
            JObject genresresultjobject = JObject.Parse(genres);
            array.Merge(genresresultjobject.Value<JArray>("data"));
            totalPages = (int)(genresresultjobject["meta"].Value<int>("count") / 20 - 0.5);
            for (int i = 1; i < totalPages; i++)
            {
                if (genres.Contains("failed:"))
                {
                    break;
                }
                tasks.Add(Get("genres?fields[genres]=name&page[limit]=20&page[offset]=" + (i * 20).
      ToString()));
                
               
            }
            Task.WaitAll(tasks.ToArray());
            foreach (Task<string> task in tasks)
            {
                genresresultjobject = JObject.Parse(task.Result);
                try
                {
                    array.Merge(genresresultjobject.Value<JArray>("data"));
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage("Failed merging data: " + e.ToString(
      ), DebugSource.TASK, DebugType.WARNING);
                }
                task.Dispose();
            }
            return array;
        }
GetAllCategories()
async Task<JArray> LittleWeebLibrary.Handlers.KitsuHandler.GetAllCategories ()
Implements LittleWeebLibrary.Handlers.IKitsuHandler.
Definition at line 458 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories().
        {
            DebugHandler.TraceMessage("GetAllCategories Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JArray array = new JArray();
            int totalPages = 0;
            List<Task<string>> tasks = new List<Task<string>>();
            string categories = await Get("
      categories?fields[categories]=title&page[limit]=20&page[offset]=" + (0 * 20).ToString());
            JObject categoriesresultjobject = JObject.Parse(categories);
            array.Merge(categoriesresultjobject.Value<JArray>("data"));
            totalPages = (int)(categoriesresultjobject["meta"].Value<int>("count") / 20 - 0.5);
            for (int i = 1; i < totalPages; i++)
            {
                if (categories.Contains("failed:"))
                {
                    break;
                }
                tasks.Add(Get("categories?fields[categories]=title&page[limit]=20&page[offset]=" + (i *
      20).ToString()));
            }
            Task.WaitAll(tasks.ToArray());
            foreach (Task<string> task in tasks)
            {
                categoriesresultjobject = JObject.Parse(task.Result);
                try
                {
                    array.Merge(categoriesresultjobject.Value<JArray>("data"));
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage("Failed merging data: " + e.ToString(
      ), DebugSource.TASK, DebugType.WARNING);
                }
                task.Dispose();
            }
            return array;
        }
GetEpisodesFromKitsu()
async Task<JObject> LittleWeebLibrary.Handlers.KitsuHandler.GetEpisodesFromKitsu (string animeId, int page, int offset) [private]
Definition at line 507 of file KitsuHandler.cs.
        {
            string episodes = await Get("episodes?filter[mediaType]=Anime&filter[media_id]=" + animeId +
       "&page[limit]=20&page[offset]=" + ((page + offset) * 20).ToString() + "&sort=number");
            return JObject.Parse(episodes);
        }
Get()
async Task<string> LittleWeebLibrary.Handlers.KitsuHandler.Get (string url) [private]
Definition at line 513 of file KitsuHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("Get called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("URL: " + url,
      DebugSource.TASK, DebugType.PARAMETERS);
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync("https://kitsu.io/api/edge/" + url);
                if (response.IsSuccessStatusCode)
                {
                    return await response.Content.ReadAsStringAsync();
                }
                else
                {
                    return "failed: " + response.StatusCode.ToString();
                }
            }
        }
Member Data Documentation
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.KitsuHandler.DebugHandler [private]
Definition at line 34 of file KitsuHandler.cs.
The documentation for this class was generated from the following file:
Handlers/KitsuHandler.cs