LittleWeebLibrary.Models.JsonDownloadQueue Class Reference
Public Member Functions
JObject ToJObject ()
string ToJson ()
override string ToString ()
Properties
List< JsonDownloadInfo > downloadQueue = new List<JsonDownloadInfo>() [get, set]
string type = `download_queue` [get, set]
string updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get, set]
Detailed Description
Definition at line 8 of file JsonDownloadQueue.cs.
Member Function Documentation
ToJson()
string LittleWeebLibrary.Models.JsonDownloadQueue.ToJson ()
Definition at line 13 of file JsonDownloadQueue.cs.
        {
            return JsonConvert.SerializeObject(this);
        }
ToString()
override string LittleWeebLibrary.Models.JsonDownloadQueue.ToString ()
Definition at line 18 of file JsonDownloadQueue.cs.
        {
            JObject jobject = ToJObject();
            string properties = string.Empty;
            foreach (var x in jobject)
            {
                properties += x.Key + ": " + x.Value.ToString();
            }
            return properties;
        }
ToJObject()
JObject LittleWeebLibrary.Models.JsonDownloadQueue.ToJObject ()
Definition at line 29 of file JsonDownloadQueue.cs.
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.AddDownload(), LittleWeebLibrary.Handlers.DownloadHandler.AddDownloads(), and LittleWeebLibrary.Handlers.DownloadHandler.RemoveDownload().
        {
            JObject jobject = JObject.FromObject(this);
            return jobject;
        }
Property Documentation
type
string LittleWeebLibrary.Models.JsonDownloadQueue.type = `download_queue` [get], [set]
Definition at line 10 of file JsonDownloadQueue.cs.
{ get; set; } = "download_queue";
downloadQueue
List<JsonDownloadInfo> LittleWeebLibrary.Models.JsonDownloadQueue.downloadQueue = new List<JsonDownloadInfo>() [get], [set]
Definition at line 11 of file JsonDownloadQueue.cs.
{ get; set; } = new List<JsonDownloadInfo>();
updated
string LittleWeebLibrary.Models.JsonDownloadQueue.updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get], [set]
Definition at line 12 of file JsonDownloadQueue.cs.
{ get; set; } = StaticClasses.UtilityMethods.GetEpoch().ToString();
The documentation for this class was generated from the following file:
Models/JsonDownloadQueue.cs