LittleWeebLibrary.Settings.LittleWeebSettings Class Reference
Public Member Functions
override string ToString ()
Properties
int CurrentlyAiringBot = 21 [get, set]
List< int > DebugLevel [get, set]
List< int > DebugType [get, set]
bool Local [get, set]
int MaxDebugLogSize [get, set]
int Port [get, set]
int RandomUsernameLength [get, set]
Detailed Description
Definition at line 6 of file LittleWeebSettings.cs.
Member Function Documentation
ToString()
override string LittleWeebLibrary.Settings.LittleWeebSettings.ToString ()
Definition at line 16 of file LittleWeebSettings.cs.
Referenced by LittleWeebLibrary.Services.SettingsWebSocketService.SetAllLittleWeebSettings(), LittleWeebLibrary.Handlers.WebSocketHandler.SetLittleWeebSettings(), LittleWeebLibrary.Handlers.IrcClientHandler.SetLittleWeebSettings(), LittleWeebLibrary.Services.DirectoryWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Services.DownloadWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Handlers.FileHandler.SetLittleWeebSettings(), LittleWeebLibrary.Services.IrcWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Handlers.DownloadHandler.SetLittleWeebSettings(), and LittleWeebLibrary.Handlers.SettingsHandler.WriteLittleWeebSettings().
        {
            string toReturn = string.Empty;
            toReturn += "Port: " + Port.ToString() + Environment.NewLine;
            toReturn += "Local: " + Local.ToString() + Environment.NewLine;
            toReturn += "RandomUserNameLength:: " + RandomUsernameLength.ToString() +
      Environment.NewLine;
            toReturn += "DebugLevel: ";
            foreach (int debugLevel in DebugLevel) {
                toReturn += debugLevel.ToString() + ",";
            }
            toReturn += "DebugLevel: ";
            foreach (int debugType in DebugType)
            {
                toReturn += debugType.ToString() + ",";
            }
            toReturn += Environment.NewLine;
            toReturn += "MaxDebugLogSize: " + MaxDebugLogSize.ToString() + Environment.
      NewLine;
            return toReturn;
        }
Property Documentation
Port
int LittleWeebLibrary.Settings.LittleWeebSettings.Port [get], [set]
Definition at line 8 of file LittleWeebSettings.cs.
Referenced by LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), and LittleWeebLibrary.Handlers.WebSocketHandler.StartServer().
{ get; set; }
Local
bool LittleWeebLibrary.Settings.LittleWeebSettings.Local [get], [set]
Definition at line 9 of file LittleWeebSettings.cs.
Referenced by LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), and LittleWeebLibrary.Handlers.WebSocketHandler.OnWebSocketServerEvent().
{ get; set; }
RandomUsernameLength
int LittleWeebLibrary.Settings.LittleWeebSettings.RandomUsernameLength [get], [set]
Definition at line 10 of file LittleWeebSettings.cs.
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), and LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings().
{ get; set; }
DebugLevel
List<int> LittleWeebLibrary.Settings.LittleWeebSettings.DebugLevel [get], [set]
Definition at line 11 of file LittleWeebSettings.cs.
Referenced by LittleWeebLibrary.Handlers.DebugHandler.DebugHandler(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
{ get; set; }
DebugType
List<int> LittleWeebLibrary.Settings.LittleWeebSettings.DebugType [get], [set]
Definition at line 12 of file LittleWeebSettings.cs.
Referenced by LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
{ get; set; }
MaxDebugLogSize
int LittleWeebLibrary.Settings.LittleWeebSettings.MaxDebugLogSize [get], [set]
Definition at line 13 of file LittleWeebSettings.cs.
Referenced by LittleWeebLibrary.Handlers.DebugHandler.DebugFileWriter(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), and LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings().
{ get; set; }
CurrentlyAiringBot
int LittleWeebLibrary.Settings.LittleWeebSettings.CurrentlyAiringBot = 21 [get], [set]
Definition at line 14 of file LittleWeebSettings.cs.
{ get; set; } = 21; //Ginpachi-Sensei on Nibl.
The documentation for this class was generated from the following file:
Settings/LittleWeebSettings.cs