LittleWeebLibrary.Services.SettingsWebSocketService Class Reference
Public Member Functions
SettingsWebSocketService (IWebSocketHandler webSocketHandler, IDirectoryHandler directoryHandler, IDebugHandler debugHandler)
async Task GetCurrentIrcSettings ()
async Task GetCurrentLittleWeebSettings ()
async Task Setfullfilepath (JObject fullfilepathJson)
async Task SetIrcSettings (JObject jsonIrcSettings)
async Task SetLittleWeebSettings (JObject jsonLittleWeebSettings)
Task SetSettingsClasses (ISettingsHandler settingsHandler, IIrcClientHandler ircClientHandler, IFileHandler fileHandler, IDownloadHandler downloadHandler, IDirectoryWebSocketService directoryWebSocketService, IIrcWebSocketService ircWebSocketService)
Private Member Functions
void SetAllIrcSettings (IrcSettings settings)
void SetAllLittleWeebSettings (LittleWeebSettings settings)
Private Attributes
IDebugHandler DebugHandler
ISettingsInterface DebugHandlerSettings
IDirectoryHandler DirectoryHandler
IDirectoryWebSocketService DirectoryWebSocketService
ISettingsInterface DirectoryWebSocketServiceSettings
IDownloadHandler DownloadHandler
ISettingsInterface DownloadHandlerSettings
ISettingsInterface FileHandlerSettings
IIrcClientHandler IrcClientHandler
ISettingsInterface IrcClientHandlerSettings
IrcSettings IrcSettings
IIrcWebSocketService IrcWebSocketService
ISettingsInterface IrcWebSocketServiceSettings
LittleWeebSettings LittleWeebSettings
ISettingsHandler SettingsHandler
IWebSocketHandler WebSocketHandler
ISettingsInterface WebSocketHandlerSettings
Detailed Description
Definition at line 29 of file SettingsWebSocketService.cs.
Constructor & Destructor Documentation
SettingsWebSocketService()
LittleWeebLibrary.Services.SettingsWebSocketService.SettingsWebSocketService (IWebSocketHandler webSocketHandler, IDirectoryHandler directoryHandler, IDebugHandler debugHandler)
Definition at line 52 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            WebSocketHandler = webSocketHandler;
            DirectoryHandler = directoryHandler;
            DebugHandler = debugHandler;
        }
Member Function Documentation
SetSettingsClasses()
Task LittleWeebLibrary.Services.SettingsWebSocketService.SetSettingsClasses (ISettingsHandler settingsHandler, IIrcClientHandler ircClientHandler, IFileHandler fileHandler, IDownloadHandler downloadHandler, IDirectoryWebSocketService directoryWebSocketService, IIrcWebSocketService ircWebSocketService)
Implements LittleWeebLibrary.Services.ISettingsWebSocketService.
Definition at line 63 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.Handlers.ISettingsHandler.GetIrcSettings(), LittleWeebLibrary.Handlers.ISettingsHandler.GetLittleWeebSettings(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.StartUp.StartUp().
        {
            DebugHandler.TraceMessage("SetSettingsClasses Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            SettingsHandler = settingsHandler;
            IrcClientHandler = ircClientHandler;
            DownloadHandler = downloadHandler;
            DirectoryWebSocketService = directoryWebSocketService;
            IrcWebSocketService = ircWebSocketService;
            WebSocketHandlerSettings = WebSocketHandler as
      ISettingsInterface;
            IrcClientHandlerSettings = ircClientHandler as
      ISettingsInterface;
            DebugHandlerSettings = DebugHandler as
      ISettingsInterface;
            FileHandlerSettings = fileHandler as
      ISettingsInterface;
            DownloadHandlerSettings = downloadHandler as
      ISettingsInterface;
            DirectoryWebSocketServiceSettings = directoryWebSocketService
      as ISettingsInterface;
            IrcWebSocketServiceSettings = ircWebSocketService as
      ISettingsInterface;
            LittleWeebSettings = settingsHandler.
      GetLittleWeebSettings();
            IrcSettings = settingsHandler.GetIrcSettings();
            SetAllIrcSettings(IrcSettings);
            SetAllLittleWeebSettings(LittleWeebSettings);
            return Task.CompletedTask;
        }
GetCurrentIrcSettings()
async Task LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentIrcSettings ()
Implements LittleWeebLibrary.Services.ISettingsWebSocketService.
Definition at line 100 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.Channels, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.SettingsHandler.GetIrcSettings(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Settings.IrcSettings.ServerAddress, LittleWeebLibrary.Models.JsonIrcInfo.ToJson(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Settings.IrcSettings.UserName.
Referenced by LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetCurrentIrcSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            IrcSettings = SettingsHandler.
      GetIrcSettings();
            JsonIrcInfo info = new JsonIrcInfo()
            {
                channel = IrcSettings.Channels,
                server = IrcSettings.ServerAddress,
                user = IrcSettings.UserName,
                fullfilepath= IrcSettings.fullfilepath
            };
            await WebSocketHandler.SendMessage(info.
      ToJson());
        }
GetCurrentLittleWeebSettings()
async Task LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings ()
Implements LittleWeebLibrary.Services.ISettingsWebSocketService.
Definition at line 117 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.DebugLevel, LittleWeebLibrary.Settings.LittleWeebSettings.DebugType, LittleWeebLibrary.Handlers.SettingsHandler.GetLittleWeebSettings(), LittleWeebLibrary.Settings.LittleWeebSettings.Local, LittleWeebLibrary.Settings.LittleWeebSettings.MaxDebugLogSize, LittleWeebLibrary.Settings.LittleWeebSettings.Port, LittleWeebLibrary.Settings.LittleWeebSettings.RandomUsernameLength, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonLittleWeebSettings.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetCurrentLittleWeebSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            LittleWeebSettings = SettingsHandler.
      GetLittleWeebSettings();
            JsonLittleWeebSettings settings = new
      JsonLittleWeebSettings()
            {
                port = LittleWeebSettings.Port,
                local = LittleWeebSettings.Local,
                randomusernamelength = LittleWeebSettings.
      RandomUsernameLength,
                debuglevel = LittleWeebSettings.DebugLevel,
                debugtype = LittleWeebSettings.DebugType,
                maxdebuglogsize = LittleWeebSettings.
      MaxDebugLogSize
            };
            await WebSocketHandler.SendMessage(settings.
      ToJson());
        }
SetIrcSettings()
async Task LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings (JObject jsonIrcSettings)
Implements LittleWeebLibrary.Services.ISettingsWebSocketService.
Definition at line 134 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.Channels, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.SettingsHandler.GetIrcSettings(), LittleWeebLibrary.Settings.IrcSettings.Port, LittleWeebLibrary.Settings.IrcSettings.Secure, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Settings.IrcSettings.ServerAddress, LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), LittleWeebLibrary.Settings.IrcSettings.UserName, and LittleWeebLibrary.Handlers.SettingsHandler.WriteIrcSettings().
Referenced by LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("SetIrcSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(jsonIrcSettings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                IrcSettings = SettingsHandler.
      GetIrcSettings();
                IrcSettings.ServerAddress = jsonIrcSettings.Value<string>("address"
      );
                IrcSettings.Channels = jsonIrcSettings.Value<string>("channels");
                IrcSettings.UserName = jsonIrcSettings.Value<string>("username");
                IrcSettings.fullfilepath= jsonIrcSettings.Value<string>("
      fullfilepath");
                IrcSettings.Port = jsonIrcSettings.Value<int>("port");
                IrcSettings.Secure = jsonIrcSettings.Value<bool>("secure");
                SetAllIrcSettings(IrcSettings);
                SettingsHandler.WriteIrcSettings(
      IrcSettings);
                await GetCurrentIrcSettings();
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError jsonError = new JsonError
                {
                    type = "set_irc_settings_error",
                    errortype = "Exception",
                    errormessage = "Failed to set irc settings.",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
        }
SetLittleWeebSettings()
async Task LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings (JObject jsonLittleWeebSettings)
Implements LittleWeebLibrary.Services.ISettingsWebSocketService.
Definition at line 171 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.DebugLevel, LittleWeebLibrary.Settings.LittleWeebSettings.DebugType, LittleWeebLibrary.Handlers.SettingsHandler.GetLittleWeebSettings(), LittleWeebLibrary.Settings.LittleWeebSettings.MaxDebugLogSize, LittleWeebLibrary.Settings.LittleWeebSettings.RandomUsernameLength, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Handlers.SettingsHandler.WriteLittleWeebSettings().
Referenced by LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("SetLittleWeebSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(jsonLittleWeebSettings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                LittleWeebSettings = SettingsHandler.
      GetLittleWeebSettings();
                LittleWeebSettings.RandomUsernameLength =
      jsonLittleWeebSettings.Value<int>("randomusernamelength");
                LittleWeebSettings.DebugLevel = jsonLittleWeebSettings.Value<
      JArray>("debuglevel").ToObject<List<int>>();
                LittleWeebSettings.DebugType = jsonLittleWeebSettings.Value<
      JArray>("debugtype").ToObject<List<int>>();
                LittleWeebSettings.MaxDebugLogSize =
      jsonLittleWeebSettings.Value<int>("maxdebuglogsize");
                SetAllLittleWeebSettings(
      LittleWeebSettings);
                SettingsHandler.WriteLittleWeebSettings(
      LittleWeebSettings);
                await GetCurrentLittleWeebSettings();
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError
                {
                    type = "set_littleweeb_settings_error",
                    errortype = "Exception",
                    errormessage = "Failed to set littleweeb settings.",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Setfullfilepath()
async Task LittleWeebLibrary.Services.SettingsWebSocketService.Setfullfilepath (JObject fullfilepathJson)
Implements LittleWeebLibrary.Services.ISettingsWebSocketService.
Definition at line 206 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.Handlers.DirectoryHandler.CreateDirectory(), LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Handlers.SettingsHandler.WriteIrcSettings().
Referenced by LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("Setfullfilepath Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(fullfilepathJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string path = fullfilepathJson.Value<string>("path");
                DirectoryHandler.CreateDirectory(path, "");
                IrcSettings.fullfilepath= path;
                SetAllIrcSettings(IrcSettings);
                SettingsHandler.WriteIrcSettings(
      IrcSettings);
                await GetCurrentIrcSettings();
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError jsonError = new JsonError
                {
                    type = "set_download_directory_error",
                    errortype = "Exception",
                    errormessage = "Failed to set custom download directory.",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
        }
SetAllLittleWeebSettings()
void LittleWeebLibrary.Services.SettingsWebSocketService.SetAllLittleWeebSettings (LittleWeebSettings settings) [private]
Definition at line 237 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.SetLittleWeebSettings(), LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetAllLittleWeebSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IrcClientHandlerSettings.
      SetLittleWeebSettings(settings);
            FileHandlerSettings.SetLittleWeebSettings(settings);
            DownloadHandlerSettings.SetLittleWeebSettings(
      settings);
            DirectoryWebSocketServiceSettings.
      SetLittleWeebSettings(settings);
            IrcWebSocketServiceSettings.
      SetLittleWeebSettings(settings);
        }
SetAllIrcSettings()
void LittleWeebLibrary.Services.SettingsWebSocketService.SetAllIrcSettings (IrcSettings settings) [private]
Definition at line 248 of file SettingsWebSocketService.cs.
References LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.SetIrcSettings(), LittleWeebLibrary.Settings.IrcSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetAllIrcSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IrcClientHandlerSettings.SetIrcSettings(settings);
            FileHandlerSettings.SetIrcSettings(settings);
            DownloadHandlerSettings.SetIrcSettings(settings);
            DirectoryWebSocketServiceSettings.
      SetIrcSettings(settings);
            IrcWebSocketServiceSettings.
      SetIrcSettings(settings);
        }
Member Data Documentation
DebugHandler
IDebugHandler LittleWeebLibrary.Services.SettingsWebSocketService.DebugHandler [private]
Definition at line 34 of file SettingsWebSocketService.cs.
WebSocketHandler
IWebSocketHandler LittleWeebLibrary.Services.SettingsWebSocketService.WebSocketHandler [private]
Definition at line 35 of file SettingsWebSocketService.cs.
IrcClientHandler
IIrcClientHandler LittleWeebLibrary.Services.SettingsWebSocketService.IrcClientHandler [private]
Definition at line 36 of file SettingsWebSocketService.cs.
SettingsHandler
ISettingsHandler LittleWeebLibrary.Services.SettingsWebSocketService.SettingsHandler [private]
Definition at line 37 of file SettingsWebSocketService.cs.
DirectoryHandler
IDirectoryHandler LittleWeebLibrary.Services.SettingsWebSocketService.DirectoryHandler [private]
Definition at line 38 of file SettingsWebSocketService.cs.
DownloadHandler
IDownloadHandler LittleWeebLibrary.Services.SettingsWebSocketService.DownloadHandler [private]
Definition at line 39 of file SettingsWebSocketService.cs.
DirectoryWebSocketService
IDirectoryWebSocketService LittleWeebLibrary.Services.SettingsWebSocketService.DirectoryWebSocketService [private]
Definition at line 40 of file SettingsWebSocketService.cs.
IrcWebSocketService
IIrcWebSocketService LittleWeebLibrary.Services.SettingsWebSocketService.IrcWebSocketService [private]
Definition at line 41 of file SettingsWebSocketService.cs.
WebSocketHandlerSettings
ISettingsInterface LittleWeebLibrary.Services.SettingsWebSocketService.WebSocketHandlerSettings [private]
Definition at line 42 of file SettingsWebSocketService.cs.
IrcClientHandlerSettings
ISettingsInterface LittleWeebLibrary.Services.SettingsWebSocketService.IrcClientHandlerSettings [private]
Definition at line 43 of file SettingsWebSocketService.cs.
DebugHandlerSettings
ISettingsInterface LittleWeebLibrary.Services.SettingsWebSocketService.DebugHandlerSettings [private]
Definition at line 44 of file SettingsWebSocketService.cs.
FileHandlerSettings
ISettingsInterface LittleWeebLibrary.Services.SettingsWebSocketService.FileHandlerSettings [private]
Definition at line 45 of file SettingsWebSocketService.cs.
DownloadHandlerSettings
ISettingsInterface LittleWeebLibrary.Services.SettingsWebSocketService.DownloadHandlerSettings [private]
Definition at line 46 of file SettingsWebSocketService.cs.
DirectoryWebSocketServiceSettings
ISettingsInterface LittleWeebLibrary.Services.SettingsWebSocketService.DirectoryWebSocketServiceSettings [private]
Definition at line 47 of file SettingsWebSocketService.cs.
IrcWebSocketServiceSettings
ISettingsInterface LittleWeebLibrary.Services.SettingsWebSocketService.IrcWebSocketServiceSettings [private]
Definition at line 48 of file SettingsWebSocketService.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Services.SettingsWebSocketService.LittleWeebSettings [private]
Definition at line 49 of file SettingsWebSocketService.cs.
IrcSettings
IrcSettings LittleWeebLibrary.Services.SettingsWebSocketService.IrcSettings [private]
Definition at line 50 of file SettingsWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/SettingsWebSocketService.cs