LittleWeebLibrary.Services.DirectoryWebSocketService Class Reference
Public Member Functions
DirectoryWebSocketService (IWebSocketHandler webSocketHandler, IDirectoryHandler directoryHandler, IDebugHandler debugHandler)
async Task CreateDirectory (JObject directoryJson)
async Task DeleteDirectory (JObject directoryJson)
async Task GetDirectories (JObject directoryJson)
async Task GetDrives ()
async Task GetFreeSpace ()
void SetIrcSettings (IrcSettings settings)
void SetLittleWeebSettings (LittleWeebSettings settings)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IDirectoryHandler DirectoryHandler
IrcSettings IrcSettings
LittleWeebSettings LittleWeebSettings
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 20 of file DirectoryWebSocketService.cs.
Constructor & Destructor Documentation
DirectoryWebSocketService()
LittleWeebLibrary.Services.DirectoryWebSocketService.DirectoryWebSocketService (IWebSocketHandler webSocketHandler, IDirectoryHandler directoryHandler, IDebugHandler debugHandler)
Definition at line 31 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            WebSocketHandler = webSocketHandler;
            DirectoryHandler = directoryHandler;
        }
Member Function Documentation
CreateDirectory()
async Task LittleWeebLibrary.Services.DirectoryWebSocketService.CreateDirectory (JObject directoryJson)
Implements LittleWeebLibrary.Services.IDirectoryWebSocketService.
Definition at line 40 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Handlers.DirectoryHandler.CreateDirectory(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("CreateDirectory called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(directoryJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string filePath = directoryJson.Value<string>("path");
                if (filePath.Contains("//"))
                {
                    filePath.Replace("//", "/");
                }
                if (filePath.Contains("\\\\"))
                {
                    filePath.Replace("\\\\", "\\");
                }
                string result = DirectoryHandler.CreateDirectory(filePath, "
      ");
                await WebSocketHandler.SendMessage(result);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "create_directory_error",
                    errormessage = "Could not create directory.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
DeleteDirectory()
async Task LittleWeebLibrary.Services.DirectoryWebSocketService.DeleteDirectory (JObject directoryJson)
Implements LittleWeebLibrary.Services.IDirectoryWebSocketService.
Definition at line 77 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Handlers.DirectoryHandler.DeleteDirectory(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("DeleteDirectory called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(directoryJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string filePath = directoryJson.Value<string>("path");
                if (filePath.Contains("//"))
                {
                    filePath.Replace("//", "/");
                }
                if (filePath.Contains("\\\\"))
                {
                    filePath.Replace("\\\\", "\\");
                }
                string result = DirectoryHandler.DeleteDirectory(filePath);
                await WebSocketHandler.SendMessage(result);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
              
                JsonError error = new JsonError()
                {
                    type = "create_directory_error",
                    errormessage = "Could not create directory.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
GetDrives()
async Task LittleWeebLibrary.Services.DirectoryWebSocketService.GetDrives ()
Implements LittleWeebLibrary.Services.IDirectoryWebSocketService.
Definition at line 112 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Handlers.DirectoryHandler.GetDrives(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetDrives called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string result = DirectoryHandler.GetDrives();
            await WebSocketHandler.SendMessage(result);
        }
GetDirectories()
async Task LittleWeebLibrary.Services.DirectoryWebSocketService.GetDirectories (JObject directoryJson)
Implements LittleWeebLibrary.Services.IDirectoryWebSocketService.
Definition at line 119 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Handlers.DirectoryHandler.GetDirectories(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetDirectories called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(directoryJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string filePath = directoryJson.Value<string>("path");
                if (filePath.Contains("//"))
                {
                    filePath.Replace("//", "/");
                }
                if (filePath.Contains("\\\\"))
                {
                    filePath.Replace("\\\\", "\\");
                }
                string result = DirectoryHandler.GetDirectories(filePath);
                await WebSocketHandler.SendMessage(result);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "create_directory_error",
                    errormessage = "Could not create directory.",
                    errortype = "exception",
                    exception = e.ToString(),
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
GetFreeSpace()
async Task LittleWeebLibrary.Services.DirectoryWebSocketService.GetFreeSpace ()
Implements LittleWeebLibrary.Services.IDirectoryWebSocketService.
Definition at line 156 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.DirectoryHandler.GetFreeSpace(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetFreeSpace called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string result = DirectoryHandler.GetFreeSpace(
      IrcSettings.fullfilepath);
            await WebSocketHandler.SendMessage(result);
        }
SetIrcSettings()
void LittleWeebLibrary.Services.DirectoryWebSocketService.SetIrcSettings (IrcSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 163 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetIrcSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IrcSettings = settings;
        }
SetLittleWeebSettings()
void LittleWeebLibrary.Services.DirectoryWebSocketService.SetLittleWeebSettings (LittleWeebSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 170 of file DirectoryWebSocketService.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetIrcSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            LittleWeebSettings = settings;
        }
Member Data Documentation
DirectoryHandler
readonly IDirectoryHandler LittleWeebLibrary.Services.DirectoryWebSocketService.DirectoryHandler [private]
Definition at line 24 of file DirectoryWebSocketService.cs.
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Services.DirectoryWebSocketService.WebSocketHandler [private]
Definition at line 25 of file DirectoryWebSocketService.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Services.DirectoryWebSocketService.DebugHandler [private]
Definition at line 26 of file DirectoryWebSocketService.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Services.DirectoryWebSocketService.LittleWeebSettings [private]
Definition at line 28 of file DirectoryWebSocketService.cs.
IrcSettings
IrcSettings LittleWeebLibrary.Services.DirectoryWebSocketService.IrcSettings [private]
Definition at line 29 of file DirectoryWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/DirectoryWebSocketService.cs