LittleWeebLibrary.Services.FileWebSocketService Class Reference
Public Member Functions
FileWebSocketService (IWebSocketHandler webSocketHandler, IFileHandler fileHandler, IFileHistoryHandler fileHistoryHandler, IDownloadHandler downloadHandler, IDebugHandler debugHandler)
async Task DeleteFile (JObject fileInfoJson)
async Task OpenFile (JObject fileInfoJson)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IDownloadHandler DownloadHandler
readonly IFileHandler FileHandler
readonly IFileHistoryHandler FileHistoryHandler
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 17 of file FileWebSocketService.cs.
Constructor & Destructor Documentation
FileWebSocketService()
LittleWeebLibrary.Services.FileWebSocketService.FileWebSocketService (IWebSocketHandler webSocketHandler, IFileHandler fileHandler, IFileHistoryHandler fileHistoryHandler, IDownloadHandler downloadHandler, IDebugHandler debugHandler)
Definition at line 27 of file FileWebSocketService.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            WebSocketHandler = webSocketHandler;
            FileHandler = fileHandler;
            FileHistoryHandler = fileHistoryHandler;
            DownloadHandler = downloadHandler;
            DebugHandler = debugHandler;
        }
Member Function Documentation
DeleteFile()
async Task LittleWeebLibrary.Services.FileWebSocketService.DeleteFile (JObject fileInfoJson)
Implements LittleWeebLibrary.Services.IFileWebSocketService.
Definition at line 39 of file FileWebSocketService.cs.
References LittleWeebLibrary.Handlers.FileHandler.DeleteFile(), LittleWeebLibrary.Handlers.DownloadHandler.RemoveDownload(), LittleWeebLibrary.Handlers.FileHistoryHandler.RemoveFileFromFileHistory(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("DeleteFile called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(fileInfoJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string filePath = fileInfoJson.Value<string>("path");
                if (filePath.Contains("//"))
                {
                    filePath.Replace("//", "/");
                }
                if (filePath.Contains("\\\\"))
                {
                    filePath.Replace("\\\\", "\\");
                }
                await DownloadHandler.RemoveDownload(filePath);
                await FileHistoryHandler.
      RemoveFileFromFileHistory(filePath);
                string result = FileHandler.DeleteFile(filePath);
                await WebSocketHandler.SendMessage(result);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "parse_file_to_delete_error",
                    errormessage = "Could not parse json containing file to delete information.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
OpenFile()
async Task LittleWeebLibrary.Services.FileWebSocketService.OpenFile (JObject fileInfoJson)
Implements LittleWeebLibrary.Services.IFileWebSocketService.
Definition at line 78 of file FileWebSocketService.cs.
References LittleWeebLibrary.Handlers.FileHandler.OpenFile(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("OpenFile called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(fileInfoJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string filePath = fileInfoJson.Value<string>("path");
                if (filePath.Contains("//"))
                {
                    filePath.Replace("//", "/");
                }
                if (filePath.Contains("\\\\"))
                {
                    filePath.Replace("\\\\", "\\");
                }
                if (filePath != null)
                {
                    string result = FileHandler.OpenFile(filePath);
                    await WebSocketHandler.SendMessage(result);
                }
                else
                {
                    DebugHandler.TraceMessage("Request does not contain path
       parameter to open file.", DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "parse_file_to_open_error",
                        errormessage = "Request does not contain path parameter to open file.",
                        errortype = "warning",
                        exception = "none"
                    };
                    await WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "parse_file_to_open_error",
                    errormessage = "Could not parse json containing file to open information.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Services.FileWebSocketService.WebSocketHandler [private]
Definition at line 21 of file FileWebSocketService.cs.
FileHandler
readonly IFileHandler LittleWeebLibrary.Services.FileWebSocketService.FileHandler [private]
Definition at line 22 of file FileWebSocketService.cs.
FileHistoryHandler
readonly IFileHistoryHandler LittleWeebLibrary.Services.FileWebSocketService.FileHistoryHandler [private]
Definition at line 23 of file FileWebSocketService.cs.
DownloadHandler
readonly IDownloadHandler LittleWeebLibrary.Services.FileWebSocketService.DownloadHandler [private]
Definition at line 24 of file FileWebSocketService.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Services.FileWebSocketService.DebugHandler [private]
Definition at line 25 of file FileWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/FileWebSocketService.cs