LittleWeebLibrary.Handlers.DataBaseHandler Class Reference
Public Member Functions
DataBaseHandler (IDebugHandler debugHandler)
async Task< JArray > GetCollection (string collection)
async Task< JObject > GetJObject (string collection, string id)
async Task< JObject > GetJObject (string collection, string property, string value)
async Task< bool > RemoveJObject (string collection, string id)
async Task< bool > RemoveJObject (string collection, string property, string value)
async Task< bool > StoreJObject (string collection, JObject toStore, string id=``)
async Task< bool > UpdateJObject (string collection, JObject toUpdate, string id, bool overwrite=false)
async Task< bool > UpdateJObject (string collection, JObject toUpdate, string property, string value, bool overwrite=false)
Private Attributes
readonly string DataBasePath = ``
readonly IDebugHandler DebugHandler
Detailed Description
Definition at line 25 of file DataBaseHandler.cs.
Constructor & Destructor Documentation
DataBaseHandler()
LittleWeebLibrary.Handlers.DataBaseHandler.DataBaseHandler (IDebugHandler debugHandler)
Definition at line 30 of file DataBaseHandler.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.BasePath(), LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            DataBasePath = PortablePath.Combine(UtilityMethods.
      BasePath(), "DataBase");
            try
            {
                if (!Directory.Exists(DataBasePath))
                {
                    Directory.CreateDirectory(DataBasePath);
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("FAILED OPENING OR CREATING DATABASE!",
      DebugSource.CONSTRUCTOR, DebugType.ERROR);
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.CONSTRUCTOR, DebugType.ERROR);
            }
        }
Member Function Documentation
GetCollection()
async Task<JArray> LittleWeebLibrary.Handlers.DataBaseHandler.GetCollection (string collection)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 51 of file DataBaseHandler.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.ReadBinaryFile(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.StaticClasses.UtilityMethods.Unzip().
Referenced by LittleWeebLibrary.Services.DataBaseWebSocketService.GetCollection(), and LittleWeebLibrary.Handlers.FileHistoryHandler.GetCurrentFileHistory().
        {
            DebugHandler.TraceMessage("GetCollection called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
            string collectionPath = PortablePath.Combine(DataBasePath, collection);
            DebugHandler.TraceMessage("Collection Path: " + collectionPath,
      DebugSource.TASK, DebugType.INFO);
            if (!Directory.Exists(collectionPath)) {
                Directory.CreateDirectory(collectionPath);
            }
            string[] jsonFiles = Directory.GetFiles(collectionPath);
            JArray collectionlist = new JArray();
            foreach (string path in jsonFiles)
            {
                if (Path.GetExtension(path) == ".jzip") {
                    byte[] data = await UtilityMethods.
      ReadBinaryFile(path);
                    string content = await UtilityMethods.Unzip(data);
                    JObject jObject = JObject.Parse(content);
                    collectionlist.Add(jObject);
                }
            }
            return collectionlist;
        }
GetJObject() [1/2]
async Task<JObject> LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject (string collection, string id)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 80 of file DataBaseHandler.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.ReadBinaryFile(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.StaticClasses.UtilityMethods.Unzip().
Referenced by LittleWeebLibrary.Handlers.FileHistoryHandler.AddFileToFileHistory(), LittleWeebLibrary.Handlers.AnimeRuleHandler.AddRules(), LittleWeebLibrary.Handlers.AnimeRuleHandler.FilterAnimeRules(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeProfile(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetBotList(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetDocument(), and LittleWeebLibrary.Handlers.FileHistoryHandler.RemoveFileFromFileHistory().
        {
            DebugHandler.TraceMessage("GetJObject called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Id: " + id,
      DebugSource.TASK, DebugType.PARAMETERS);
            JObject toReturn = new JObject();
            string collectionPath = PortablePath.Combine(DataBasePath, collection);
            DebugHandler.TraceMessage("Collection Path: " + collectionPath,
      DebugSource.TASK, DebugType.INFO);
            string path = PortablePath.Combine(collectionPath, id + ".jzip");
            DebugHandler.TraceMessage("Collection Path + File: " + path,
      DebugSource.TASK, DebugType.INFO);
            try
            {
                if (!Directory.Exists(collectionPath))
                {
                    Directory.CreateDirectory(collectionPath);
                }
                else
                {
                    if (File.Exists(path))
                    {
                        byte[] data = await UtilityMethods.
      ReadBinaryFile(path);
                        string content = await UtilityMethods.
      Unzip(data);
                        JObject jObject = JObject.Parse(content);
                        toReturn = jObject;
                    }
                    else
                    {
                        DebugHandler.TraceMessage("Failed to open file: " + path +
      ", file not found!", DebugSource.TASK, DebugType.ERROR);
                    }
                    
                }
                
            }
            catch (IOException ioe)
            {
                DebugHandler.TraceMessage("Failed to open file: " + path + ",
       error: " + ioe.ToString(), DebugSource.TASK, DebugType.ERROR);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Failed to open file: " + path + ",
       error: " + e.ToString(), DebugSource.TASK, DebugType.ERROR);
            }
            
            return toReturn;
        }
GetJObject() [2/2]
async Task<JObject> LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject (string collection, string property, string value)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 134 of file DataBaseHandler.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.ReadBinaryFile(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.StaticClasses.UtilityMethods.Unzip().
        {
            DebugHandler.TraceMessage("GetJObject called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Property: " + property,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Value: " + value,
      DebugSource.TASK, DebugType.PARAMETERS);
            JObject toReturn = new JObject();
            string collectionPath = PortablePath.Combine(DataBasePath, collection);
            DebugHandler.TraceMessage("Collection Path: " + collectionPath,
      DebugSource.TASK, DebugType.INFO);
            string pathparsing = "";
            try
            {
                if (!Directory.Exists(collectionPath))
                {
                    Directory.CreateDirectory(collectionPath);
                }
                string[] jsonFiles = Directory.GetFiles(collectionPath);
                foreach (string path in jsonFiles)
                {
                    pathparsing = path;
                    if (Path.GetExtension(path) == ".jzip")
                    {
                        byte[] data = await UtilityMethods.
      ReadBinaryFile(path);
                        string content = await UtilityMethods.
      Unzip(data);
                        JObject jObject = JObject.Parse(content);
                        if (jObject.Value<string>(property) == value)
                        {
                            toReturn = jObject;
                            break;
                        }
                    }
                }
            }
            catch (IOException ioe)
            {
                DebugHandler.TraceMessage("Failed to open file: " + pathparsing + "
      , error: " + ioe.ToString(), DebugSource.TASK, DebugType.ERROR);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Failed to open file: " + pathparsing + "
      , error: " + e.ToString(), DebugSource.TASK, DebugType.ERROR);
            }
            
            return toReturn;
        }
RemoveJObject() [1/2]
async Task<bool> LittleWeebLibrary.Handlers.DataBaseHandler.RemoveJObject (string collection, string id)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 188 of file DataBaseHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.DataBaseWebSocketService.DeleteDocument(), and LittleWeebLibrary.Handlers.FileHistoryHandler.RemoveFileFromFileHistory().
        {
            DebugHandler.TraceMessage("RemoveJObject called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("ID: " + id,
      DebugSource.TASK, DebugType.PARAMETERS);
            string collectionPath = PortablePath.Combine(DataBasePath, collection);
            DebugHandler.TraceMessage("Collection Path: " + collectionPath,
      DebugSource.TASK, DebugType.INFO);
            bool toReturn = false;
            await Task.Run(() =>
            {
                if (Directory.Exists(collectionPath))
                {
                    string toRemove = PortablePath.Combine(collectionPath, id + ".jzip");
                    try
                    {
                        if (File.Exists(toRemove))
                        {
                            File.Delete(toRemove);
                            toReturn = true;
                        }
                        else
                        {
                            DebugHandler.TraceMessage("Failed to remove file: " +
      toRemove + ", error: File not found!", DebugSource.TASK, DebugType.ERROR);
                        }
                    }
                    catch (IOException ioe)
                    {
                        DebugHandler.TraceMessage("Failed to remove file: " +
      toRemove + ", error: " + ioe.ToString(), DebugSource.TASK, DebugType.ERROR);
                    }
                    catch (Exception e)
                    {
                        DebugHandler.TraceMessage("Failed to remove file: " +
      toRemove + ", error: " + e.ToString(), DebugSource.TASK, DebugType.ERROR);
                    }
                }
            });
           
            
            return toReturn;
        }
RemoveJObject() [2/2]
async Task<bool> LittleWeebLibrary.Handlers.DataBaseHandler.RemoveJObject (string collection, string property, string value)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 235 of file DataBaseHandler.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.ReadBinaryFile(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.StaticClasses.UtilityMethods.Unzip().
        {
            DebugHandler.TraceMessage("RemoveJObject called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Property: " + property,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Value: " + value,
      DebugSource.TASK, DebugType.PARAMETERS);
            string collectionPath = PortablePath.Combine(DataBasePath, collection);
            DebugHandler.TraceMessage("Collection Path: " + collectionPath,
      DebugSource.TASK, DebugType.INFO);
            bool toReturn = false;
            if (Directory.Exists(collectionPath))
            {
               
                string toRemove = "";
                try
                {
                    string[] jsonFiles = Directory.GetFiles(collectionPath);
                    foreach (string path in jsonFiles)
                    {
                        if (Path.GetExtension(path) == ".jzip")
                        {
                            byte[] data = await UtilityMethods.
      ReadBinaryFile(path);
                            string content = await UtilityMethods.
      Unzip(data);
                            JObject jObject = JObject.Parse(content);
                            if (jObject.Value<string>(property) == value)
                            {
                                toReturn = true;
                                toRemove = path;
                                break;
                            }
                        }
                    }
                    File.Delete(toRemove);
                }
                catch (IOException ioe)
                {
                    DebugHandler.TraceMessage("Failed to remove file: " + toRemove
      + ", error: " + ioe.ToString(), DebugSource.TASK, DebugType.ERROR);
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage("Failed to remove file: " + toRemove
      + ", error: " + e.ToString(), DebugSource.TASK, DebugType.ERROR);
                }
            }
            return toReturn;
        }
StoreJObject()
async Task<bool> LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject (string collection, JObject toStore, string id = ``)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 287 of file DataBaseHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), LittleWeebLibrary.StaticClasses.UtilityMethods.WriteBinaryFile(), and LittleWeebLibrary.StaticClasses.UtilityMethods.Zip().
Referenced by LittleWeebLibrary.Handlers.FileHistoryHandler.AddFileToFileHistory(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeProfile(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetBotList(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring(), and LittleWeebLibrary.Services.DataBaseWebSocketService.StoreDocument().
        {
            DebugHandler.TraceMessage("StoreJObject called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
             bool toReturn = false;
            string collectionPath = PortablePath.Combine(DataBasePath, collection);
            if (id == string.Empty)
            {
                id = Guid.NewGuid().ToString("N");
            }
            DebugHandler.TraceMessage("Collection Path: " + collectionPath,
      DebugSource.TASK, DebugType.INFO);
            string pathparsing = PortablePath.Combine(collectionPath, id + ".jzip");
            try
            {
                if (!Directory.Exists(collectionPath))
                {
                    Directory.CreateDirectory(collectionPath);
                }
                toStore["_id"] = id;
                byte[] zipped = await UtilityMethods.Zip(toStore.ToString());
                await UtilityMethods.WriteBinaryFile(pathparsing, zipped);
                toReturn = true;
            }
            catch (IOException ioe)
            {
                DebugHandler.TraceMessage("Failed to write file: " + pathparsing +
      ", error: " + ioe.ToString(), DebugSource.TASK, DebugType.ERROR);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Failed to write file: " + pathparsing +
      ", error: " + e.ToString(), DebugSource.TASK, DebugType.ERROR);
            }
            
            return toReturn;
        }
UpdateJObject() [1/2]
async Task<bool> LittleWeebLibrary.Handlers.DataBaseHandler.UpdateJObject (string collection, JObject toUpdate, string id, bool overwrite = false)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 332 of file DataBaseHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.AnimeRuleHandler.AddRules(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeEpisodes(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeProfile(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.FileHistoryHandler.RemoveFileFromFileHistory(), and LittleWeebLibrary.Services.DataBaseWebSocketService.UpdateDocument().
        {
            DebugHandler.TraceMessage("UpdateJObject called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Id: " + id,
      DebugSource.TASK, DebugType.PARAMETERS);
            bool toReturn = false;
            JObject old = await GetJObject(collection, id);
            if (old.Count > 0)
            {
                if (!overwrite)
                {
                    JsonMergeSettings mergeSettings = new JsonMergeSettings()
                    {
                        MergeArrayHandling = MergeArrayHandling.Union
                    };
                    old.Merge(toUpdate, mergeSettings);
                }
                else
                {
                    old = toUpdate;
                }
                toReturn = await StoreJObject(collection, old, id);
            }
            else
            {
                toReturn = await StoreJObject(collection, toUpdate, id);
            }
            return toReturn;
        }
UpdateJObject() [2/2]
async Task<bool> LittleWeebLibrary.Handlers.DataBaseHandler.UpdateJObject (string collection, JObject toUpdate, string property, string value, bool overwrite = false)
Implements LittleWeebLibrary.Handlers.IDataBaseHandler.
Definition at line 368 of file DataBaseHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("UpdateJObject called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Collection: " + collection,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Property: " + property,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("Value: " + value,
      DebugSource.TASK, DebugType.PARAMETERS);
            bool toReturn = false;
            JObject old = await GetJObject(collection, property, value);
            if (old.Count > 0)
            {
                if (!overwrite)
                {
                    JsonMergeSettings mergeSettings = new JsonMergeSettings()
                    {
                        MergeArrayHandling = MergeArrayHandling.Union
                    };
                    old.Merge(toUpdate, mergeSettings);
                }
                else
                {
                    old = toUpdate;
                }
                toReturn = await StoreJObject(collection, old, old.Value<string>("_id"));
            }
            else
            {
                toReturn = await StoreJObject(collection, toUpdate);
            }
            return toReturn;
        }
Member Data Documentation
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.DataBaseHandler.DebugHandler [private]
Definition at line 27 of file DataBaseHandler.cs.
DataBasePath
readonly string LittleWeebLibrary.Handlers.DataBaseHandler.DataBasePath = `` [private]
Definition at line 28 of file DataBaseHandler.cs.
The documentation for this class was generated from the following file:
Handlers/DataBaseHandler.cs