LittleWeebLibrary.Services.VersionWebSocketService Class Reference
Public Member Functions
VersionWebSocketService (IWebSocketHandler webSocketHandler, IVersionHandler versionHandler, IDebugHandler debugHandler)
async Task CheckVersion ()
Private Attributes
IDebugHandler DebugHandler
IVersionHandler VersionHandler
IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 21 of file VersionWebSocketService.cs.
Constructor & Destructor Documentation
VersionWebSocketService()
LittleWeebLibrary.Services.VersionWebSocketService.VersionWebSocketService (IWebSocketHandler webSocketHandler, IVersionHandler versionHandler, IDebugHandler debugHandler)
Definition at line 28 of file VersionWebSocketService.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            VersionHandler = versionHandler;
            WebSocketHandler = webSocketHandler;
            DebugHandler = debugHandler;
        }
Member Function Documentation
CheckVersion()
async Task LittleWeebLibrary.Services.VersionWebSocketService.CheckVersion ()
Implements LittleWeebLibrary.Services.IVersionWebSocketService.
Definition at line 37 of file VersionWebSocketService.cs.
References LittleWeebLibrary.Models.JsonVersionInfo.currentbuild, LittleWeebLibrary.Models.JsonVersionInfo.currentversion, LittleWeebLibrary.Handlers.VersionHandler.GetLatestVersionAndroid(), LittleWeebLibrary.Handlers.VersionHandler.GetLatestVersionDesktop(), LittleWeebLibrary.Handlers.VersionHandler.GetLocalVersion(), LittleWeebLibrary.Models.JsonVersionInfo.newbuild, LittleWeebLibrary.Models.JsonVersionInfo.newversion, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonVersionInfo.ToJson(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Models.JsonVersionInfo.update_available.
Referenced by LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("CheckVersion called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JsonVersionInfo versionInfoDevelop = new
      JsonVersionInfo();
            JsonVersionInfo versionInfoRelease = new
      JsonVersionInfo();
            versionInfoDevelop = await VersionHandler.
      GetLatestVersionDesktop(false);
            versionInfoRelease = await VersionHandler.
      GetLatestVersionDesktop(true);
#if __ANDROID__
            versionInfoDevelop = await VersionHandler.
      GetLatestVersionAndroid(false);
            versionInfoRelease = await VersionHandler.
      GetLatestVersionAndroid(true);
#endif
            JsonVersionInfo currentVersion = VersionHandler.
      GetLocalVersion();
            try
            {
                if (versionInfoDevelop.newversion != "Not Found" && currentVersion.
      currentversion != "Not Found")
                {
                    DebugHandler.TraceMessage("Current: " + currentVersion.
      ToJson(), DebugSource.TASK, DebugType.INFO);
                    DebugHandler.TraceMessage("Develop: " + versionInfoDevelop.
      ToJson(), DebugSource.TASK, DebugType.INFO);
                    int currentBuild = int.Parse(currentVersion.currentbuild);
                    int newBuild = int.Parse(versionInfoDevelop.newbuild);
                    if (versionInfoDevelop.newversion == currentVersion.
      currentversion && currentBuild >= newBuild)
                    {
                        versionInfoDevelop.update_available = false;
                    }
                    else
                    {
                        versionInfoDevelop.update_available = true;
                    }
                }
                if (versionInfoRelease.newversion != "Not Found" && currentVersion.
      currentversion != "Not Found")
                {
                    DebugHandler.TraceMessage("Current: " + currentVersion.
      ToJson(), DebugSource.TASK, DebugType.INFO);
                    DebugHandler.TraceMessage("Develop: " + versionInfoRelease.
      ToJson(), DebugSource.TASK, DebugType.INFO);
                    
                    int currentBuild = int.Parse(currentVersion.currentbuild);
                    int newBuild = int.Parse(versionInfoRelease.newbuild);
                    if (versionInfoRelease.newversion == currentVersion.
      currentversion && currentBuild >= newBuild)
                    {
                        versionInfoRelease.update_available = false;
                    }
                    else
                    {
                        versionInfoRelease.update_available = true;
                    }
                }
                versionInfoDevelop.currentbuild = currentVersion.
      currentbuild;
                versionInfoDevelop.currentversion = currentVersion.
      currentversion;
                await WebSocketHandler.SendMessage(versionInfoDevelop.
      ToJson());
                versionInfoRelease.currentbuild = currentVersion.
      currentbuild;
                versionInfoRelease.currentversion = currentVersion.
      currentversion;
                await WebSocketHandler.SendMessage(versionInfoRelease.
      ToJson());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
Member Data Documentation
VersionHandler
IVersionHandler LittleWeebLibrary.Services.VersionWebSocketService.VersionHandler [private]
Definition at line 24 of file VersionWebSocketService.cs.
WebSocketHandler
IWebSocketHandler LittleWeebLibrary.Services.VersionWebSocketService.WebSocketHandler [private]
Definition at line 25 of file VersionWebSocketService.cs.
DebugHandler
IDebugHandler LittleWeebLibrary.Services.VersionWebSocketService.DebugHandler [private]
Definition at line 26 of file VersionWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/VersionWebSocketService.cs