LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController Class Reference
Public Member Functions
DataBaseWebSocketController (IWebSocketHandler webSocketHandler, IDataBaseWebSocketService dataBaseWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDataBaseWebSocketService DataBaseWebSocketService
readonly IDebugHandler DebugHandler
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 12 of file DataBaseWebSocketController.cs.
Constructor & Destructor Documentation
DataBaseWebSocketController()
LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.DataBaseWebSocketController (IWebSocketHandler webSocketHandler, IDataBaseWebSocketService dataBaseWebSocketService, IDebugHandler debugHandler)
Definition at line 19 of file DataBaseWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            DataBaseWebSocketService = dataBaseWebSocketService;
            WebSocketHandler = webSocketHandler;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 28 of file DataBaseWebSocketController.cs.
References LittleWeebLibrary.Services.DataBaseWebSocketService.DeleteDocument(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetCollection(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetDocument(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Services.DataBaseWebSocketService.StoreDocument(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Services.DataBaseWebSocketService.UpdateDocument().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try
                {
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        JObject extra = query.Value<JObject>("extra");
                        if (extra != null)
                        {
                            switch (action)
                            {
                                case "get_collection":
                                    DataBaseWebSocketService.
      GetCollection(extra);
                                    break;
                                case "get_document":
                                    DataBaseWebSocketService.
      GetDocument(extra);
                                    break;
                                case "store_document":
                                    DataBaseWebSocketService.
      StoreDocument(extra);
                                    break;
                                case "delete_document":
                                    DataBaseWebSocketService.
      DeleteDocument(extra);
                                    break;
                                case "update_document":
                                    DataBaseWebSocketService.
      UpdateDocument(extra);
                                    break;
                            }
                        }
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
               
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.WebSocketHandler [private]
Definition at line 15 of file DataBaseWebSocketController.cs.
DataBaseWebSocketService
readonly IDataBaseWebSocketService LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.DataBaseWebSocketService [private]
Definition at line 16 of file DataBaseWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.DebugHandler [private]
Definition at line 17 of file DataBaseWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/DataBaseWebSocketController.cs