LittleWeebLibrary.Services.DataBaseWebSocketService Class Reference
Public Member Functions
DataBaseWebSocketService (IWebSocketHandler webSocketHandler, IDataBaseHandler dataBaseHandler, IDebugHandler debugHandler)
async Task DeleteDocument (JObject query)
async Task GetCollection (JObject query)
async Task GetDocument (JObject query)
async Task StoreDocument (JObject query)
async Task UpdateDocument (JObject query)
Private Attributes
IDataBaseHandler DataBaseHandler
IDebugHandler DebugHandler
IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 25 of file DataBaseWebSocketService.cs.
Constructor & Destructor Documentation
DataBaseWebSocketService()
LittleWeebLibrary.Services.DataBaseWebSocketService.DataBaseWebSocketService (IWebSocketHandler webSocketHandler, IDataBaseHandler dataBaseHandler, IDebugHandler debugHandler)
Definition at line 32 of file DataBaseWebSocketService.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DataBaseHandler = dataBaseHandler;
            WebSocketHandler = webSocketHandler;
            DebugHandler = debugHandler;
        }
Member Function Documentation
DeleteDocument()
async Task LittleWeebLibrary.Services.DataBaseWebSocketService.DeleteDocument (JObject query)
Implements LittleWeebLibrary.Services.IDataBaseWebSocketService.
Definition at line 41 of file DataBaseWebSocketService.cs.
References LittleWeebLibrary.Handlers.DataBaseHandler.RemoveJObject(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonSuccess.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("DeleteDocument called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string collection = query.Value<string>("collection");
            bool succes = false;
            if (query.ContainsKey("parameter") && query.ContainsKey("value"))
            {
                succes = await DataBaseHandler.RemoveJObject(collection, query.
      Value<string>("parameter"), query.Value<string>("value"));
            }
            else if (query.ContainsKey("id"))
            {
                succes = await DataBaseHandler.RemoveJObject(collection, query.
      Value<string>("id"));
            }
            else
            {
                JsonError jsonError = new JsonError()
                {
                    type = "delete_document_error",
                    errormessage = "Either parameter & value or id are not defined!",
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
            if (succes)
            {
                JsonSuccess jsonSuccess = new JsonSuccess()
                {
                    message = "Succesfully deleted document!"
                };
                await WebSocketHandler.SendMessage(jsonSuccess.
      ToJson());
            }
            else
            {
                JsonError jsonError = new JsonError()
                {
                    type = "delete_document_error",
                    errormessage = "Failed to delete document.",
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
        }
GetCollection()
async Task LittleWeebLibrary.Services.DataBaseWebSocketService.GetCollection (JObject query)
Implements LittleWeebLibrary.Services.IDataBaseWebSocketService.
Definition at line 90 of file DataBaseWebSocketService.cs.
References LittleWeebLibrary.Handlers.DataBaseHandler.GetCollection(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonDataBaseCollection.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetCollection called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string collection = query.Value<string>("collection");
            JArray result = await DataBaseHandler.GetCollection(collection);
            if (result.Count > 0)
            {
                JsonDataBaseCollection collectionresult = new
      JsonDataBaseCollection()
                {
                    result = result
                };
                await WebSocketHandler.SendMessage(collectionresult.
      ToJson());
            }
            else
            {
                JsonError jsonError = new JsonError()
                {
                    type = "get_collection_error",
                    errormessage = "Collection is empty.",
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
        }
GetDocument()
async Task LittleWeebLibrary.Services.DataBaseWebSocketService.GetDocument (JObject query)
Implements LittleWeebLibrary.Services.IDataBaseWebSocketService.
Definition at line 121 of file DataBaseWebSocketService.cs.
References LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonDataBaseDocument.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetDocument called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string collection = query.Value<string>("collection");
            JObject document = new JObject();
            if (query.ContainsKey("parameter") && query.ContainsKey("value"))
            {
                document = await DataBaseHandler.GetJObject(collection, query.
      Value<string>("parameter"), query.Value<string>("value"));
            }
            else if (query.ContainsKey("id"))
            {
                document = await DataBaseHandler.GetJObject(collection, query.
      Value<string>("id"));
            }
            else
            {
                JsonError jsonError = new JsonError()
                {
                    type = "get_document_error",
                    errormessage = "Either parameter & value or id are not defined!",
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
            if (document.Count > 0)
            {
                JsonDataBaseDocument tosend = new
      JsonDataBaseDocument()
                {
                    result = document
                };
                await WebSocketHandler.SendMessage(tosend.
      ToString());
            }
            else
            {
                JsonError jsonError = new JsonError()
                {
                    type = "get_document_error",
                    errormessage = "Failed to get document.",
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
        }
StoreDocument()
async Task LittleWeebLibrary.Services.DataBaseWebSocketService.StoreDocument (JObject query)
Implements LittleWeebLibrary.Services.IDataBaseWebSocketService.
Definition at line 168 of file DataBaseWebSocketService.cs.
References LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject(), LittleWeebLibrary.Models.JsonSuccess.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("StoreDocument called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string collection = query.Value<string>("collection");
            JObject document = query.Value<JObject>("document");
            bool succes = false;
            if (query.ContainsKey("id"))
            {
                succes = await DataBaseHandler.StoreJObject(collection, document
      , query.Value<string>("id"));
            }
            else
            {
                succes = await DataBaseHandler.StoreJObject(collection, document
      );
            }
            if (succes)
            {
                JsonSuccess jsonSuccess = new JsonSuccess()
                {
                    message = "Succesfully stored document!"
                };
                await WebSocketHandler.SendMessage(jsonSuccess.
      ToJson());
            }
            else
            {
                JsonError jsonError = new JsonError()
                {
                    type = "store_document_error",
                    errormessage = "Failed to store document.",
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
        }
UpdateDocument()
async Task LittleWeebLibrary.Services.DataBaseWebSocketService.UpdateDocument (JObject query)
Implements LittleWeebLibrary.Services.IDataBaseWebSocketService.
Definition at line 205 of file DataBaseWebSocketService.cs.
References LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonSuccess.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Handlers.DataBaseHandler.UpdateJObject().
Referenced by LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("UpdateDocument called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string collection = query.Value<string>("collection");
            JObject document = query.Value<JObject>("document");
            bool succes = false;
            if (query.ContainsKey("id"))
            {
                succes = await DataBaseHandler.UpdateJObject(collection,
      document, query.Value<string>("id"));
            }
            else
            {
                succes = await DataBaseHandler.UpdateJObject(collection,
      document);
            }
            if (succes)
            {
                JsonSuccess jsonSuccess = new JsonSuccess()
                {
                    message = "Succesfully updated document!"
                };
                await WebSocketHandler.SendMessage(jsonSuccess.
      ToJson());
            }
            else
            {
                JsonError jsonError = new JsonError()
                {
                    type = "update_document_error",
                    errormessage = "Failed to update document.",
                    errortype = "warning"
                };
                await WebSocketHandler.SendMessage(jsonError.
      ToJson());
            }
        }
Member Data Documentation
DataBaseHandler
IDataBaseHandler LittleWeebLibrary.Services.DataBaseWebSocketService.DataBaseHandler [private]
Definition at line 28 of file DataBaseWebSocketService.cs.
WebSocketHandler
IWebSocketHandler LittleWeebLibrary.Services.DataBaseWebSocketService.WebSocketHandler [private]
Definition at line 29 of file DataBaseWebSocketService.cs.
DebugHandler
IDebugHandler LittleWeebLibrary.Services.DataBaseWebSocketService.DebugHandler [private]
Definition at line 30 of file DataBaseWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/DataBaseWebSocketService.cs