LittleWeebLibrary.Handlers.DebugHandler Class Reference
Public Member Functions
DebugHandler ()
void SetSettings (ISettingsHandler settingsHandler)
void StopDebugger ()
void TraceMessage (string message, DebugSource sourcetype, DebugType debugtype, [System.Runtime.CompilerServices.CallerMemberName] string memberName=``, [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath=``, [System.Runtime.CompilerServices.CallerLineNumber] int sourceLineNumber=0)
Private Member Functions
async Task CreateFile ()
async Task DebugFileWriter (string[] message)
async Task TraceWriter ()
void WriteTrace (string toWrite)
Private Attributes
readonly string DebugFileName = `littleweeb.log`
string DebugPath = ``
readonly string [] DebugSourceTypes = new string[] { `CONSTRUCTOR`, `METHOD`, `EVENT`, `TASK`, `EXTERNAL(LIBRARY)`, `NOT DEFINED` }
readonly string [] DebugTypes = new string[] { `NOT DEFINED`, `ENTRY/EXIT`, `PARAMETERS`, `INFO`, `WARNING`, `ERROR` }
bool DebugWriteAble = true
LittleWeebSettings LittleWeebSettings
readonly List< string[]> MessageQueue
ISettingsHandler SettingsHandler
bool stop = false
Detailed Description
Definition at line 29 of file DebugHandler.cs.
Constructor & Destructor Documentation
DebugHandler()
LittleWeebLibrary.Handlers.DebugHandler.DebugHandler ()
Definition at line 43 of file DebugHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.DebugLevel.
        {
            LittleWeebSettings = new LittleWeebSettings()
            {
                Local = true,
                Port = 1515,
                DebugLevel = new List<int>() { 0, 1, 2, 3, 4, 5 },
                DebugType = new List<int>() { 0, 1, 2, 3, 4, 5 },
                RandomUsernameLength = 6,
                MaxDebugLogSize = 2000
            };
            MessageQueue = new List<string[]>();
            foreach (int level in LittleWeebSettings.
      DebugLevel)
            {
                WriteTrace("DEBUG LEVEL: " + level);
            }
            CreateFile();
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method
       continues before the call is completed
            TraceWriter();
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method
       continues before the call is completed
            WriteTrace("Succesfully initiated debug handler!");
        }
Member Function Documentation
SetSettings()
void LittleWeebLibrary.Handlers.DebugHandler.SetSettings (ISettingsHandler settingsHandler)
Implements LittleWeebLibrary.Handlers.IDebugHandler.
Definition at line 71 of file DebugHandler.cs.
References LittleWeebLibrary.Handlers.ISettingsHandler.GetLittleWeebSettings().
Referenced by LittleWeebLibrary.StartUp.StartUp().
        {
            LittleWeebSettings = settingsHandler.GetLittleWeebSettings();
            SettingsHandler = settingsHandler;
        }
TraceWriter()
async Task LittleWeebLibrary.Handlers.DebugHandler.TraceWriter () [private]
Definition at line 78 of file DebugHandler.cs.
        {
            string[] debugMessage = new string[5];
            while (!stop)
            {
                try
                {
                    bool succes = false;
                    lock (MessageQueue)
                    {
                        if (MessageQueue.Count > 0)
                        {
                            debugMessage = MessageQueue[0];
                            MessageQueue.RemoveAt(0);
                            succes = true;
                        }
                    }
                    if (succes)
                    {
                       await DebugFileWriter(debugMessage);
                    }
                }
                catch (Exception e)
                {
                    WriteTrace(e.ToString());
                }
                if (MessageQueue.Count != 0)
                {
                    await Task.Delay(1);
                }
                else
                {
                    await Task.Delay(10);
                }
            }
        }
TraceMessage()
void LittleWeebLibrary.Handlers.DebugHandler.TraceMessage (string message, DebugSource sourcetype, DebugType debugtype, [System.Runtime.CompilerServices.CallerMemberName] string memberName = ``, [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath = ``, [System.Runtime.CompilerServices.CallerLineNumber] int sourceLineNumber = 0)
Implements LittleWeebLibrary.Handlers.IDebugHandler.
Definition at line 118 of file DebugHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.DebugLevel, and LittleWeebLibrary.Settings.LittleWeebSettings.DebugType.
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.AbortDownload(), LittleWeebLibrary.Handlers.DownloadHandler.AbortDownload(), LittleWeebLibrary.Handlers.DownloadHandler.AddDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownloads(), LittleWeebLibrary.Handlers.DownloadHandler.AddDownloads(), LittleWeebLibrary.Handlers.FileHistoryHandler.AddFileToFileHistory(), LittleWeebLibrary.Services.InfoApiWebSocketService.AddRule(), LittleWeebLibrary.Handlers.AnimeRuleHandler.AddRules(), LittleWeebLibrary.Handlers.AnimeProfileHandler.AnimeLatestEpisode(), LittleWeebLibrary.Services.VersionWebSocketService.CheckVersion(), LittleWeebLibrary.Handlers.AnimeProfileHandler.CombineAnimeEpisodesParsedNiblResults(), LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.DirectoryWebSocketService.CreateDirectory(), LittleWeebLibrary.Handlers.DirectoryHandler.CreateDirectory(), LittleWeebLibrary.Handlers.AnimeProfileHandler.CurrentlyAiringAsync(), LittleWeebLibrary.Handlers.IrcClientHandler.CurrentSettings(), LittleWeebLibrary.Handlers.DataBaseHandler.DataBaseHandler(), LittleWeebLibrary.Services.DirectoryWebSocketService.DeleteDirectory(), LittleWeebLibrary.Handlers.DirectoryHandler.DeleteDirectory(), LittleWeebLibrary.Services.DataBaseWebSocketService.DeleteDocument(), LittleWeebLibrary.Services.FileWebSocketService.DeleteFile(), LittleWeebLibrary.Handlers.FileHandler.DeleteFile(), LittleWeebLibrary.Services.IrcWebSocketService.DisableSendMessage(), LittleWeebLibrary.Services.IrcWebSocketService.Disconnect(), LittleWeebLibrary.Handlers.DownloadHandler.DownloadHandler(), LittleWeebLibrary.Handlers.DownloadHandler.DownloadQueueHandler(), LittleWeebLibrary.Services.IrcWebSocketService.EnableSendMessage(), LittleWeebLibrary.Handlers.AnimeRuleHandler.FilterAnimeRules(), LittleWeebLibrary.Handlers.AnimeRuleHandler.Get(), LittleWeebLibrary.Handlers.NiblHandler.Get(), LittleWeebLibrary.Handlers.KitsuHandler.Get(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories(), LittleWeebLibrary.Handlers.KitsuHandler.GetAllCategories(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres(), LittleWeebLibrary.Handlers.KitsuHandler.GetAllGenres(), LittleWeebLibrary.Handlers.KitsuHandler.GetAnime(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeEpisodes(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeEpisodes(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeProfile(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeProfile(), LittleWeebLibrary.Handlers.NiblHandler.GetBotList(), LittleWeebLibrary.Handlers.KitsuHandler.GetCategories(), LittleWeebLibrary.Handlers.DataBaseHandler.GetCollection(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetCollection(), LittleWeebLibrary.Services.DownloadWebSocketService.GetCurrentFileHistory(), LittleWeebLibrary.Handlers.FileHistoryHandler.GetCurrentFileHistory(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.Services.IrcWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.KitsuHandler.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.DownloadHandler.GetCurrentlyDownloading(), LittleWeebLibrary.Handlers.DirectoryHandler.GetDirectories(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDirectories(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetDocument(), LittleWeebLibrary.Handlers.DirectoryHandler.GetDrives(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDrives(), LittleWeebLibrary.Handlers.KitsuHandler.GetEpisodes(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetFilesForAnime(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetFreeSpace(), LittleWeebLibrary.Handlers.DirectoryHandler.GetFreeSpace(), LittleWeebLibrary.Handlers.KitsuHandler.GetFullAnime(), LittleWeebLibrary.Handlers.KitsuHandler.GetGenres(), LittleWeebLibrary.Handlers.SettingsHandler.GetIrcSettings(), LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject(), LittleWeebLibrary.Handlers.NiblHandler.GetLatestEpisode(), LittleWeebLibrary.Handlers.NiblHandler.GetLatestFiles(), LittleWeebLibrary.Handlers.VersionHandler.GetLatestVersionAndroid(), LittleWeebLibrary.Handlers.VersionHandler.GetLatestVersionDesktop(), LittleWeebLibrary.Handlers.SettingsHandler.GetLittleWeebSettings(), LittleWeebLibrary.Handlers.VersionHandler.GetLocalVersion(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetPreviousSeasonsTotalEpisodes(), LittleWeebLibrary.Handlers.KitsuHandler.GetRelations(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetSeasonFromAnime(), LittleWeebLibrary.Handlers.AnimeRuleHandler.Init(), LittleWeebLibrary.Handlers.IrcClientHandler.IsConnected(), LittleWeebLibrary.Handlers.IrcClientHandler.IsDownloading(), LittleWeebLibrary.Handlers.IrcClientHandler.OnDownloadUpdate(), LittleWeebLibrary.Handlers.IrcClientHandler.OnDownloadUpdateDebug(), LittleWeebLibrary.Services.DownloadWebSocketService.OnDownloadUpdateEvent(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientConnectionStatusEvent(), LittleWeebLibrary.Handlers.DownloadHandler.OnIrcClientDownloadEvent(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientMessageEvent(), LittleWeebLibrary.Handlers.IrcClientHandler.OnMessage(), LittleWeebLibrary.Handlers.IrcClientHandler.OnMessageDebug(), LittleWeebLibrary.Handlers.IrcClientHandler.OnUserListUpdate(), LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.BaseWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Handlers.WebSocketHandler.OnWebSocketServerEvent(), LittleWeebLibrary.Handlers.DirectoryHandler.OpenDirectory(), LittleWeebLibrary.Handlers.FileHandler.OpenFile(), LittleWeebLibrary.Services.FileWebSocketService.OpenFile(), LittleWeebLibrary.Services.DownloadWebSocketService.Openfullfilepath(), LittleWeebLibrary.Handlers.AnimeProfileHandler.ParseNiblSearchResults(), LittleWeebLibrary.Handlers.AnimeProfileHandler.ParseTitles(), LittleWeebLibrary.Services.DownloadWebSocketService.RemoveDownload(), LittleWeebLibrary.Handlers.DownloadHandler.RemoveDownload(), LittleWeebLibrary.Handlers.FileHistoryHandler.RemoveFileFromFileHistory(), LittleWeebLibrary.Handlers.DataBaseHandler.RemoveJObject(), LittleWeebLibrary.Handlers.KitsuHandler.SearchAnime(), LittleWeebLibrary.Services.InfoApiWebSocketService.SearchKitsu(), LittleWeebLibrary.Handlers.NiblHandler.SearchNibl(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Handlers.IrcClientHandler.SendMessage(), LittleWeebLibrary.Services.IrcWebSocketService.SendMessage(), LittleWeebLibrary.Services.SettingsWebSocketService.SetAllIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetAllLittleWeebSettings(), LittleWeebLibrary.Handlers.IrcClientHandler.Setfullfilepath(), LittleWeebLibrary.Services.SettingsWebSocketService.Setfullfilepath(), LittleWeebLibrary.Handlers.IrcClientHandler.SetIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings(), LittleWeebLibrary.Services.DirectoryWebSocketService.SetIrcSettings(), LittleWeebLibrary.Services.DownloadWebSocketService.SetIrcSettings(), LittleWeebLibrary.Services.IrcWebSocketService.SetIrcSettings(), LittleWeebLibrary.Handlers.DownloadHandler.SetIrcSettings(), LittleWeebLibrary.Handlers.WebSocketHandler.SetLittleWeebSettings(), LittleWeebLibrary.Handlers.IrcClientHandler.SetLittleWeebSettings(), LittleWeebLibrary.Services.DirectoryWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Services.DownloadWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Handlers.FileHandler.SetLittleWeebSettings(), LittleWeebLibrary.Services.IrcWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Handlers.DownloadHandler.SetLittleWeebSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetSettingsClasses(), LittleWeebLibrary.Controllers.BaseWebSocketController.SetSubControllers(), LittleWeebLibrary.Handlers.IrcClientHandler.StartConnection(), LittleWeebLibrary.Handlers.IrcClientHandler.StartDownload(), LittleWeebLibrary.Handlers.WebSocketHandler.StartServer(), LittleWeebLibrary.Handlers.IrcClientHandler.StopConnection(), LittleWeebLibrary.Handlers.IrcClientHandler.StopDownload(), LittleWeebLibrary.Handlers.DownloadHandler.StopQueue(), LittleWeebLibrary.Handlers.WebSocketHandler.StopServer(), LittleWeebLibrary.Services.DataBaseWebSocketService.StoreDocument(), LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject(), LittleWeebLibrary.Services.DataBaseWebSocketService.UpdateDocument(), LittleWeebLibrary.Handlers.DataBaseHandler.UpdateJObject(), LittleWeebLibrary.Handlers.SettingsHandler.WriteIrcSettings(), and LittleWeebLibrary.Handlers.SettingsHandler.WriteLittleWeebSettings().
        {
            if (LittleWeebSettings.DebugLevel.Contains((int)debugtype) &&
      LittleWeebSettings.DebugType.Contains((int)sourcetype))
            {
                string[] debugMessage = new string[] { message, memberName, sourceFilePath,
      sourceLineNumber.ToString(), DebugSourceTypes[(int)sourcetype], DebugTypes[(int)debugtype] };
                lock (MessageQueue)
                {
                    MessageQueue.Add(debugMessage);
                }
            }
            
        }
CreateFile()
async Task LittleWeebLibrary.Handlers.DebugHandler.CreateFile () [private]
Definition at line 134 of file DebugHandler.cs.
        {
            try
            {
#if __ANDROID__
                DebugPath = Path.Combine(Path.Combine(Android.OS.Environment.
      ExternalStorageDirectory.AbsolutePath, "LittleWeeb"), "DebugLog");
#else
                DebugPath = Path.Combine(Path.Combine(Environment.GetFolderPath(Environment.
      SpecialFolder.MyDocuments), "LittleWeeb"), "DebugLog");
#endif
                if (!Directory.Exists(DebugPath))
                {
                    Directory.CreateDirectory(DebugPath);
                }
                if (!File.Exists(Path.Combine(DebugPath, DebugFileName)))
                {
                    WriteTrace("Debug file does not exist, creating file: " + Path.Combine(
      DebugPath, DebugFileName));
                    using (var fileStream = File.Open(Path.Combine(DebugPath,
      DebugFileName), FileMode.CreateNew, FileAccess.ReadWrite, FileShare.ReadWrite))
                    {
                        using (var streamWriter = new StreamWriter(fileStream))
                        {
                            await streamWriter.WriteLineAsync("Starting Log AT: " + DateTime.UtcNow +
      Environment.NewLine);
                            streamWriter.Close();
                        }
                        fileStream.Close();
                    }
                    WriteTrace("Debug file has been created.");
                }
                DebugWriteAble = true;
            }
            catch (Exception e)
            {
                DebugWriteAble = false;
                WriteTrace(e.ToString());
            }
        }
DebugFileWriter()
async Task LittleWeebLibrary.Handlers.DebugHandler.DebugFileWriter (string [] message) [private]
Definition at line 173 of file DebugHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.MaxDebugLogSize.
        {
            try
            {
                if (DebugWriteAble)
                {
                    string debugSourceType = "";
                    if (message[5] == "NOT DEFINED")
                    {
                        debugSourceType = "NOT DEFINED";
                    }
                    else
                    {
                        debugSourceType = message[5];
                    }
                    string toWriteString = "|" + message[4] + "|[" + message[1] + ", " + Path.
      GetFileNameWithoutExtension(message[2]) + "," + message[3] + "]|" + debugSourceType + "|" + message[0] + "|" ;
                    WriteTrace(toWriteString);
                    string currentLog = string.Empty;
                    bool rewrite = false;
                    using (FileStream fileStream = new FileStream(Path.Combine(
      DebugPath, DebugFileName), FileMode.OpenOrCreate, FileAccess.Read, FileShare.
      ReadWrite))
                    {
                        using (StreamReader streamReader = new StreamReader(fileStream))
                        {
                            currentLog = streamReader.ReadToEnd();
                            if (currentLog.Split(new string[] { Environment.NewLine }, StringSplitOptions.
      None).Length > LittleWeebSettings.MaxDebugLogSize)
                            {
                                currentLog = currentLog.Skip(toWriteString.Split(new string[] { Environment
      .NewLine }, StringSplitOptions.None).Length) + Environment.NewLine + toWriteString;
                                rewrite = true;
                            }
                            else
                            {
                                currentLog = toWriteString;
                            }
                            streamReader.DiscardBufferedData();
                        }
                      
                    }
                    FileMode mode = FileMode.Append;
                    if (rewrite)
                    {
                        mode = FileMode.Truncate;
                    }
                    using (FileStream fileStream = new FileStream(Path.Combine(
      DebugPath, DebugFileName), mode, FileAccess.Write, FileShare.ReadWrite))
                    {
                        using (StreamWriter streamWriter = new StreamWriter(fileStream))
                        {
                            streamWriter.Flush();
                            streamWriter.Write(currentLog + Environment.NewLine);
                            streamWriter.Flush();
                            streamWriter.Dispose();
                            currentLog = string.Empty;
                        }
                    }
                    await Task.Delay(1);
                }
            }
            catch (Exception e)
            {
                WriteTrace(e.ToString());
            }
        }
WriteTrace()
void LittleWeebLibrary.Handlers.DebugHandler.WriteTrace (string toWrite) [private]
Definition at line 247 of file DebugHandler.cs.
        {
            Console.WriteLine(toWrite);
        }
StopDebugger()
void LittleWeebLibrary.Handlers.DebugHandler.StopDebugger ()
Implements LittleWeebLibrary.Handlers.IDebugHandler.
Definition at line 252 of file DebugHandler.cs.
        {
            stop = true;
        }
Member Data Documentation
DebugWriteAble
bool LittleWeebLibrary.Handlers.DebugHandler.DebugWriteAble = true [private]
Definition at line 32 of file DebugHandler.cs.
DebugFileName
readonly string LittleWeebLibrary.Handlers.DebugHandler.DebugFileName = `littleweeb.log` [private]
Definition at line 33 of file DebugHandler.cs.
DebugPath
string LittleWeebLibrary.Handlers.DebugHandler.DebugPath = `` [private]
Definition at line 34 of file DebugHandler.cs.
DebugTypes
readonly string [] LittleWeebLibrary.Handlers.DebugHandler.DebugTypes = new string[] { `NOT DEFINED`, `ENTRY/EXIT`, `PARAMETERS`, `INFO`, `WARNING`, `ERROR` } [private]
Definition at line 35 of file DebugHandler.cs.
DebugSourceTypes
readonly string [] LittleWeebLibrary.Handlers.DebugHandler.DebugSourceTypes = new string[] { `CONSTRUCTOR`, `METHOD`, `EVENT`, `TASK`, `EXTERNAL(LIBRARY)`, `NOT DEFINED` } [private]
Definition at line 36 of file DebugHandler.cs.
MessageQueue
readonly List<string[]> LittleWeebLibrary.Handlers.DebugHandler.MessageQueue [private]
Definition at line 37 of file DebugHandler.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Handlers.DebugHandler.LittleWeebSettings [private]
Definition at line 38 of file DebugHandler.cs.
stop
bool LittleWeebLibrary.Handlers.DebugHandler.stop = false [private]
Definition at line 39 of file DebugHandler.cs.
SettingsHandler
ISettingsHandler LittleWeebLibrary.Handlers.DebugHandler.SettingsHandler [private]
Definition at line 41 of file DebugHandler.cs.
The documentation for this class was generated from the following file:
Handlers/DebugHandler.cs