LittleWeebLibrary.Handlers.SettingsHandler Class Reference
Public Member Functions
SettingsHandler (IDebugHandler debugHandler)
IrcSettings GetIrcSettings ()
LittleWeebSettings GetLittleWeebSettings ()
void WriteIrcSettings (IrcSettings ircSettings)
void WriteLittleWeebSettings (LittleWeebSettings littleWeebSettings)
Private Attributes
readonly IDebugHandler DebugHandler
readonly string SettingsPath
Detailed Description
Definition at line 21 of file SettingsHandler.cs.
Constructor & Destructor Documentation
SettingsHandler()
LittleWeebLibrary.Handlers.SettingsHandler.SettingsHandler (IDebugHandler debugHandler)
Definition at line 29 of file SettingsHandler.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.BasePath(), and LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            string littleWeebSettingsName = "LittleWeebSettings.json";
            string ircSettingsName = "IrcSettings.json";
            SettingsPath = PortablePath.Combine(UtilityMethods.
      BasePath(), "Settings");
            if (!Directory.Exists(SettingsPath))
            {
                Directory.CreateDirectory(SettingsPath);
            }
            if (!File.Exists(PortablePath.Combine(SettingsPath, littleWeebSettingsName))){
                WriteLittleWeebSettings(new
      LittleWeebSettings()
                {
                    Local = true,
                    Port = 1515,
                    DebugLevel = new List<int>() { 0, 1, 2, 3, 4, 5 },
                    DebugType = new List<int>() { 0, 1, 2, 3, 4},
                    RandomUsernameLength = 6,
                    MaxDebugLogSize = 2000
                });
            }
            if (!File.Exists(PortablePath.Combine(SettingsPath, ircSettingsName)))
            {
                WriteIrcSettings(new IrcSettings());
            }
        }
Member Function Documentation
WriteIrcSettings()
void LittleWeebLibrary.Handlers.SettingsHandler.WriteIrcSettings (IrcSettings ircSettings)
Implements LittleWeebLibrary.Handlers.ISettingsHandler.
Definition at line 67 of file SettingsHandler.cs.
References LittleWeebLibrary.Settings.IrcSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.SettingsWebSocketService.Setfullfilepath(), and LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings().
        {
            DebugHandler.TraceMessage("WriteIrcSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(ircSettings.
      ToString(), DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string settingsName = "IrcSettings.json";
                string settingsJson = JsonConvert.SerializeObject(ircSettings);
                if (!File.Exists(PortablePath.Combine(SettingsPath, settingsName)))
                {
                    using (var fileStream = File.Open(PortablePath.Combine(
      SettingsPath, settingsName), FileMode.OpenOrCreate, System.IO.FileAccess.Write, FileShare
      .ReadWrite))
                    {
                        using (var streamWriter = new StreamWriter(fileStream))
                        {
                            streamWriter.Write(settingsJson);
                        }
                    }
                }
                else
                {
                    using (var fileStream = File.Open(PortablePath.Combine(
      SettingsPath, settingsName), FileMode.Truncate, System.IO.FileAccess.ReadWrite, FileShare
      .ReadWrite))
                    {
                        using (var streamWriter = new StreamWriter(fileStream))
                        {
                            streamWriter.Write(settingsJson);
                        }
                    }
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
WriteLittleWeebSettings()
void LittleWeebLibrary.Handlers.SettingsHandler.WriteLittleWeebSettings (LittleWeebSettings littleWeebSettings)
Implements LittleWeebLibrary.Handlers.ISettingsHandler.
Definition at line 107 of file SettingsHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings().
        {
            DebugHandler.TraceMessage("WriteLittleWeebSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(littleWeebSettings.
      ToString(), DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string settingsName = "LittleWeebSettings.json";
                string settingsJson = JsonConvert.SerializeObject(littleWeebSettings);
                if (!File.Exists(PortablePath.Combine(SettingsPath, settingsName)))
                {
                    using (var fileStream = File.Open(PortablePath.Combine(
      SettingsPath, settingsName), FileMode.OpenOrCreate, System.IO.FileAccess.Write, FileShare
      .ReadWrite))
                    {
                        using (var streamWriter = new StreamWriter(fileStream))
                        {
                            streamWriter.Write(settingsJson);
                        }
                    }
                }
                else
                {
                    using (var fileStream = File.Open(PortablePath.Combine(
      SettingsPath, settingsName), FileMode.Truncate, System.IO.FileAccess.ReadWrite, FileShare
      .ReadWrite))
                    {
                        using (var streamWriter = new StreamWriter(fileStream))
                        {
                            streamWriter.Write(settingsJson);
                        }
                    }
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
GetLittleWeebSettings()
LittleWeebSettings LittleWeebLibrary.Handlers.SettingsHandler.GetLittleWeebSettings ()
Implements LittleWeebLibrary.Handlers.ISettingsHandler.
Definition at line 146 of file SettingsHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.DownloadWebSocketService(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), LittleWeebLibrary.Handlers.IrcClientHandler.IrcClientHandler(), LittleWeebLibrary.Services.IrcWebSocketService.IrcWebSocketService(), and LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings().
        {
            DebugHandler.TraceMessage("GetLittleWeebSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                string settingsName = "LittleWeebSettings.json";
                if (File.Exists(PortablePath.Combine(SettingsPath, settingsName)))
                {
                    string settingsJson = "";
                    using (var fileStream = File.Open(PortablePath.Combine(
      SettingsPath, settingsName), FileMode.Open, System.IO.FileAccess.ReadWrite, FileShare.
      ReadWrite))
                    {
                        using (var streamReader = new StreamReader(fileStream))
                        {
                            string readLine = "";
                            while ((readLine = streamReader.ReadLine()) != null)
                            {
                                settingsJson += readLine;
                            }
                        }
                    }
                    DebugHandler.TraceMessage("Returning read littleweebsettings: "
       + settingsJson, DebugSource.TASK, DebugType.INFO);
                    return JsonConvert.DeserializeObject<LittleWeebSettings>(settingsJson
      );
                }
                else
                {
                    DebugHandler.TraceMessage("Returning new littleweebsettings.",
      DebugSource.TASK, DebugType.INFO);
                    return new LittleWeebSettings();
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Returning new littleweebsettings.",
      DebugSource.TASK, DebugType.INFO);
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                return new LittleWeebSettings();
            }
        }
GetIrcSettings()
IrcSettings LittleWeebLibrary.Handlers.SettingsHandler.GetIrcSettings ()
Implements LittleWeebLibrary.Handlers.ISettingsHandler.
Definition at line 188 of file SettingsHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.DownloadWebSocketService(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.Handlers.IrcClientHandler.IrcClientHandler(), LittleWeebLibrary.Services.IrcWebSocketService.IrcWebSocketService(), and LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings().
        {
            DebugHandler.TraceMessage("GetIrcSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            IrcSettings toReturn = new IrcSettings();
            try
            {
                string settingsName = "IrcSettings.json";
                if (File.Exists(PortablePath.Combine(SettingsPath, settingsName)))
                {
                    string settingsJson = "";
                    using (var fileStream = File.Open(PortablePath.Combine(
      SettingsPath, settingsName), FileMode.Open, System.IO.FileAccess.ReadWrite, FileShare.
      ReadWrite))
                    {
                        using (var streamReader = new StreamReader(fileStream))
                        {
                            string readLine = "";
                            while ((readLine = streamReader.ReadLine()) != null)
                            {
                                settingsJson += readLine;
                            }
                        }
                    }
                    toReturn = JsonConvert.DeserializeObject<IrcSettings>(settingsJson);
                    DebugHandler.TraceMessage("Returning read ircsettings: " +
      toReturn, DebugSource.TASK, DebugType.INFO);
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
            return toReturn;
        }
Member Data Documentation
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.SettingsHandler.DebugHandler [private]
Definition at line 25 of file SettingsHandler.cs.
SettingsPath
readonly string LittleWeebLibrary.Handlers.SettingsHandler.SettingsPath [private]
Definition at line 27 of file SettingsHandler.cs.
The documentation for this class was generated from the following file:
Handlers/SettingsHandler.cs