LittleWeebLibrary.Services.DownloadWebSocketService Class Reference
Public Member Functions
DownloadWebSocketService (IWebSocketHandler webSocketHandler, IDirectoryHandler directoryHandler, IDownloadHandler downloadHandler, IFileHandler fileHandler, IFileHistoryHandler fileHistoryHandler, ISettingsHandler settingsHandler, IDebugHandler debugHandler)
async Task AbortDownload (JObject downloadJson)
async Task AddDownload (JObject downloadJson)
async Task AddDownloads (JObject downloadJsonBatch)
async Task GetCurrentFileHistory ()
async Task Openfullfilepath ()
async Task RemoveDownload (JObject downloadJson)
void SetIrcSettings (IrcSettings settings)
void SetLittleWeebSettings (LittleWeebSettings settings)
Private Member Functions
async void OnDownloadUpdateEvent (object sender, DownloadUpdateEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IDirectoryHandler DirectoryHandler
readonly IDownloadHandler DownloadHandler
readonly IFileHandler FileHandler
readonly IFileHistoryHandler FileHistoryHandler
IrcSettings IrcSettings
JsonDownloadInfo LastDownloadedInfo
LittleWeebSettings LittleWeebSettings
readonly ISettingsHandler SettingsHandler
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 22 of file DownloadWebSocketService.cs.
Constructor & Destructor Documentation
DownloadWebSocketService()
LittleWeebLibrary.Services.DownloadWebSocketService.DownloadWebSocketService (IWebSocketHandler webSocketHandler, IDirectoryHandler directoryHandler, IDownloadHandler downloadHandler, IFileHandler fileHandler, IFileHistoryHandler fileHistoryHandler, ISettingsHandler settingsHandler, IDebugHandler debugHandler)
Definition at line 39 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Handlers.SettingsHandler.GetIrcSettings(), LittleWeebLibrary.Handlers.SettingsHandler.GetLittleWeebSettings(), LittleWeebLibrary.Handlers.IDownloadHandler.OnDownloadUpdateEvent, and LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            
            debugHandler.TraceMessage("Constructor called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            WebSocketHandler = webSocketHandler;
            DirectoryHandler = directoryHandler;
            DownloadHandler = downloadHandler;
            FileHandler = fileHandler;
            FileHistoryHandler = fileHistoryHandler;
            SettingsHandler = settingsHandler;
            LastDownloadedInfo = new JsonDownloadInfo();
            LittleWeebSettings = SettingsHandler.
      GetLittleWeebSettings();
            IrcSettings = SettingsHandler.
      GetIrcSettings();
            downloadHandler.OnDownloadUpdateEvent +=
      OnDownloadUpdateEvent;
        }
Member Function Documentation
AddDownload()
async Task LittleWeebLibrary.Services.DownloadWebSocketService.AddDownload (JObject downloadJson)
Implements LittleWeebLibrary.Services.IDownloadWebSocketService.
Definition at line 68 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Handlers.DownloadHandler.AddDownload(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("AddDownload called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(downloadJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
                    
            try
            {
                JsonDownloadInfo downloadInfo = new
      JsonDownloadInfo()
                {
                    anime_id = downloadJson.Value<JObject>("animeInfo").Value<string>("animeid"),
                    anime_name = downloadJson.Value<JObject>("animeInfo").Value<string>("title"),
                    id = downloadJson.Value<string>("id"),
                    episodeNumber = downloadJson.Value<string>("episodeNumber"),
                    season = downloadJson.Value<string>("season"),
                    pack = downloadJson.Value<string>("pack"),
                    bot = downloadJson.Value<string>("bot"),
                    fullfilepath= downloadJson.Value<string>("dir"),
                    filename = downloadJson.Value<string>("filename"),
                    progress = downloadJson.Value<string>("progress"),
                    speed = downloadJson.Value<string>("speed"),
                    status = downloadJson.Value<string>("status"),
                    filesize = downloadJson.Value<string>("filesize")
                };
                LastDownloadedInfo = downloadInfo;
                JObject result = await DownloadHandler.
      AddDownload(downloadInfo);
                await WebSocketHandler.SendMessage(result.ToString());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
              
                JsonError error = new JsonError()
                {
                    type = "parse_download_to_add_error",
                    errormessage = "Could not parse json containing download to add information.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
RemoveDownload()
async Task LittleWeebLibrary.Services.DownloadWebSocketService.RemoveDownload (JObject downloadJson)
Implements LittleWeebLibrary.Services.IDownloadWebSocketService.
Definition at line 118 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Handlers.DownloadHandler.RemoveDownload(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("RemoveDownload called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(downloadJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string id = downloadJson.Value<string>("id");
                string filePath = downloadJson.Value<string>("path");
                JObject result = new JObject();
                if (id != null)
                {
                    result = await DownloadHandler.RemoveDownload(id);
                    await WebSocketHandler.SendMessage(result.ToString());
                }
                else
                {
                    JsonError error = new JsonError()
                    {
                        type = "parse_download_to_remove_error",
                        errormessage = "Neither id or file path have been defined!",
                        errortype = "warning",
                        exception = "none"
                    };
                    await WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "parse_download_to_remove_error",
                    errormessage = "Could not parse json containing download to remove information.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
GetCurrentFileHistory()
async Task LittleWeebLibrary.Services.DownloadWebSocketService.GetCurrentFileHistory ()
Implements LittleWeebLibrary.Services.IDownloadWebSocketService.
Definition at line 166 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Handlers.FileHistoryHandler.GetCurrentFileHistory(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetCurrentFileHistory called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            await WebSocketHandler.SendMessage(
      FileHistoryHandler.GetCurrentFileHistory().ToString());
        }
Openfullfilepath()
async Task LittleWeebLibrary.Services.DownloadWebSocketService.Openfullfilepath ()
Implements LittleWeebLibrary.Services.IDownloadWebSocketService.
Definition at line 172 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.DirectoryHandler.OpenDirectory(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("Openfullfilepath called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string result = DirectoryHandler.OpenDirectory(
      IrcSettings.fullfilepath);
            await WebSocketHandler.SendMessage(result);
        }
OnDownloadUpdateEvent()
async void LittleWeebLibrary.Services.DownloadWebSocketService.OnDownloadUpdateEvent (object sender, DownloadUpdateEventArgs args) [private]
Definition at line 179 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.EventArguments.DownloadUpdateEventArgs.downloadInfo, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonDownloadInfo.status, LittleWeebLibrary.Models.JsonDownloadInfo.ToJson(), LittleWeebLibrary.EventArguments.DownloadUpdateEventArgs.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnDownloadUpdateEvent called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                await WebSocketHandler.SendMessage(args.
      downloadInfo.ToJson());
                if (args.downloadInfo.status == "COMPLETED")
                {
                    await GetCurrentFileHistory();
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
SetIrcSettings()
void LittleWeebLibrary.Services.DownloadWebSocketService.SetIrcSettings (IrcSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 199 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetIrcSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IrcSettings = settings;
        }
SetLittleWeebSettings()
void LittleWeebLibrary.Services.DownloadWebSocketService.SetLittleWeebSettings (LittleWeebSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 206 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetLittleWeebSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            LittleWeebSettings = settings;
        }
AbortDownload()
async Task LittleWeebLibrary.Services.DownloadWebSocketService.AbortDownload (JObject downloadJson)
Implements LittleWeebLibrary.Services.IDownloadWebSocketService.
Definition at line 213 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Handlers.DownloadHandler.AbortDownload(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("AbortDownload called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(downloadJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            string id = downloadJson.Value<string>("id");
            string filePath = downloadJson.Value<string>("path");
            if (id != null)
            {
                JObject result = await DownloadHandler.
      AbortDownload(id);
                await WebSocketHandler.SendMessage(result.ToString());
            }
            else
            {
                DebugHandler.TraceMessage("Neither id or file path have been
       defined!", DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "parse_download_to_abort_error",
                    errormessage = "Neither id or file path have been defined!",
                    errortype = "warning",
                    exception = "none"
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
AddDownloads()
async Task LittleWeebLibrary.Services.DownloadWebSocketService.AddDownloads (JObject downloadJsonBatch)
Implements LittleWeebLibrary.Services.IDownloadWebSocketService.
Definition at line 239 of file DownloadWebSocketService.cs.
References LittleWeebLibrary.Handlers.DownloadHandler.AddDownloads(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("AddDownloads called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(downloadJsonBatch.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                JArray listWithDownloads = downloadJsonBatch.Value<JArray>("batch");
                List<JsonDownloadInfo> batch = new List<JsonDownloadInfo>();
                foreach (JObject downloadJson in listWithDownloads)
                {
                    JsonDownloadInfo downloadInfo = new
      JsonDownloadInfo()
                    {
                        anime_id = downloadJson.Value<JObject>("animeInfo").Value<string>("animeid"),
                        anime_name = downloadJson.Value<JObject>("animeInfo").Value<string>("title"),
                        id = downloadJson.Value<string>("id"),
                        episodeNumber = downloadJson.Value<string>("episodeNumber"),
                        season = downloadJson.Value<string>("season"),
                        pack = downloadJson.Value<string>("pack"),
                        bot = downloadJson.Value<string>("bot"),
                        filename = downloadJson.Value<string>("filename"),
                        progress = downloadJson.Value<string>("progress"),
                        speed = downloadJson.Value<string>("speed"),
                        status = downloadJson.Value<string>("status"),
                        filesize = downloadJson.Value<string>("filesize")
                    };
                    LastDownloadedInfo = downloadInfo;
                    batch.Add(downloadInfo);
                }
                
                JObject result = await DownloadHandler.
      AddDownloads(batch);
                await WebSocketHandler.SendMessage(result.ToString());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "parse_downloads_to_add_error",
                    errormessage = "Could not parse json containing downloads to add information.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Services.DownloadWebSocketService.WebSocketHandler [private]
Definition at line 25 of file DownloadWebSocketService.cs.
DirectoryHandler
readonly IDirectoryHandler LittleWeebLibrary.Services.DownloadWebSocketService.DirectoryHandler [private]
Definition at line 26 of file DownloadWebSocketService.cs.
DownloadHandler
readonly IDownloadHandler LittleWeebLibrary.Services.DownloadWebSocketService.DownloadHandler [private]
Definition at line 27 of file DownloadWebSocketService.cs.
FileHistoryHandler
readonly IFileHistoryHandler LittleWeebLibrary.Services.DownloadWebSocketService.FileHistoryHandler [private]
Definition at line 28 of file DownloadWebSocketService.cs.
FileHandler
readonly IFileHandler LittleWeebLibrary.Services.DownloadWebSocketService.FileHandler [private]
Definition at line 29 of file DownloadWebSocketService.cs.
SettingsHandler
readonly ISettingsHandler LittleWeebLibrary.Services.DownloadWebSocketService.SettingsHandler [private]
Definition at line 30 of file DownloadWebSocketService.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Services.DownloadWebSocketService.DebugHandler [private]
Definition at line 31 of file DownloadWebSocketService.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Services.DownloadWebSocketService.LittleWeebSettings [private]
Definition at line 32 of file DownloadWebSocketService.cs.
IrcSettings
IrcSettings LittleWeebLibrary.Services.DownloadWebSocketService.IrcSettings [private]
Definition at line 33 of file DownloadWebSocketService.cs.
LastDownloadedInfo
JsonDownloadInfo LittleWeebLibrary.Services.DownloadWebSocketService.LastDownloadedInfo [private]
Definition at line 35 of file DownloadWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/DownloadWebSocketService.cs