LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController Class Reference
Public Member Functions
InfoApiWebSocketController (IWebSocketHandler webSocketHandler, IInfoApiWebSocketService infoApiWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IInfoApiWebSocketService InfoApiWebSocketService
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 12 of file InfoApiWebSocketController.cs.
Constructor & Destructor Documentation
InfoApiWebSocketController()
LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.InfoApiWebSocketController (IWebSocketHandler webSocketHandler, IInfoApiWebSocketService infoApiWebSocketService, IDebugHandler debugHandler)
Definition at line 21 of file InfoApiWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            InfoApiWebSocketService = infoApiWebSocketService;
            WebSocketHandler = webSocketHandler;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 30 of file InfoApiWebSocketController.cs.
References LittleWeebLibrary.Services.InfoApiWebSocketService.AddRule(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeEpisodes(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAnimeProfile(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetBotList(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetCurrentlyAiring(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetFilesForAnime(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Services.InfoApiWebSocketService.SearchKitsu(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try
                {
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        JObject extra = query.Value<JObject>("extra");
                        if (extra != null)
                        {
                            switch (action)
                            {
                                case "search_nibl":
                                    InfoApiWebSocketService.
      GetFilesForAnime(extra);
                                    break;
                                case "get_anime_profile":
                                    InfoApiWebSocketService.
      GetAnimeProfile(extra);
                                    break;
                                case "get_anime_episodes":
                                    InfoApiWebSocketService.
      GetAnimeEpisodes(extra);
                                    break;
                                case "get_currently_airing":
                                    InfoApiWebSocketService.
      GetCurrentlyAiring(extra);
                                    break;
                                case "search_kitsu":
                                    InfoApiWebSocketService.
      SearchKitsu(extra);
                                    break;
                                case "add_rule":
                                    InfoApiWebSocketService.
      AddRule(extra);
                                    break;
                                case "get_categories_kitsu":
                                    InfoApiWebSocketService.
      GetAllCategories(extra);
                                    break;
                                case "get_genres_kitsu":
                                    InfoApiWebSocketService.
      GetAllGenres(extra);
                                    break;
                                case "get_botlist_nibl":
                                    InfoApiWebSocketService.
      GetBotList(extra);
                                    break;
                            }
                        }
                        else
                        {
                            switch (action)
                            {
                                case "get_currently_airing":
                                    InfoApiWebSocketService.
      GetCurrentlyAiring();
                                    break;
                                case "get_categories_kitsu":
                                    InfoApiWebSocketService.
      GetAllCategories(new JObject());
                                    break;
                                case "get_genres_kitsu":
                                    InfoApiWebSocketService.
      GetAllGenres(new JObject());
                                    break;
                                case "get_botlist_nibl":
                                    InfoApiWebSocketService.
      GetBotList(new JObject());
                                    break;
                            }
                        }
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
               
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.WebSocketHandler [private]
Definition at line 17 of file InfoApiWebSocketController.cs.
InfoApiWebSocketService
readonly IInfoApiWebSocketService LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.InfoApiWebSocketService [private]
Definition at line 18 of file InfoApiWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.DebugHandler [private]
Definition at line 19 of file InfoApiWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/InfoApiWebSocketController.cs