LittleWeebLibrary.Services.IrcWebSocketService Class Reference
Public Member Functions
IrcWebSocketService (IWebSocketHandler webSocketHandler, IIrcClientHandler ircClientHandler, ISettingsHandler settingsHandler, IDebugHandler debugHandler)
async Task Connect (JObject ircJson=null)
async Task DisableSendMessage ()
async Task Disconnect ()
async Task EnableSendMessage ()
async Task GetCurrentIrcSettings ()
async Task SendMessage (JObject ircMessageJson)
void SetIrcSettings (IrcSettings settings)
void SetLittleWeebSettings (LittleWeebSettings settings)
Private Member Functions
async void OnIrcClientConnectionStatusEvent (object sender, IrcClientConnectionStatusArgs args)
async void OnIrcClientMessageEvent (object sender, IrcClientMessageEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IIrcClientHandler IrcClientHandler
IrcSettings IrcSettings
bool IsIrcConnected
LittleWeebSettings LittleWeebSettings
bool SendMessageToWebSocketClient
readonly ISettingsHandler SettingsHandler
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 22 of file IrcWebSocketService.cs.
Constructor & Destructor Documentation
IrcWebSocketService()
LittleWeebLibrary.Services.IrcWebSocketService.IrcWebSocketService (IWebSocketHandler webSocketHandler, IIrcClientHandler ircClientHandler, ISettingsHandler settingsHandler, IDebugHandler debugHandler)
Definition at line 38 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Handlers.SettingsHandler.GetIrcSettings(), LittleWeebLibrary.Handlers.SettingsHandler.GetLittleWeebSettings(), LittleWeebLibrary.Handlers.IrcClientHandler.OnIrcClientConnectionStatusEvent, LittleWeebLibrary.Handlers.IrcClientHandler.OnIrcClientMessageEvent, and LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("IrcWebSocketService Constructor called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            SendMessageToWebSocketClient = false;
            IsIrcConnected = false;
            SettingsHandler = settingsHandler;
            IrcClientHandler = ircClientHandler;
            WebSocketHandler = webSocketHandler;
            DebugHandler = debugHandler;
            LittleWeebSettings = SettingsHandler.
      GetLittleWeebSettings();
            IrcSettings = SettingsHandler.
      GetIrcSettings();
            IrcClientHandler.OnIrcClientMessageEvent +=
      OnIrcClientMessageEvent;
            IrcClientHandler.OnIrcClientConnectionStatusEvent
       += OnIrcClientConnectionStatusEvent;
        }
Member Function Documentation
Connect()
async Task LittleWeebLibrary.Services.IrcWebSocketService.Connect (JObject ircJson = null)
Implements LittleWeebLibrary.Services.IIrcWebSocketService.
Definition at line 56 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.Channels, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.StaticClasses.UtilityMethods.GenerateUsername(), LittleWeebLibrary.Settings.LittleWeebSettings.RandomUsernameLength, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Settings.IrcSettings.ServerAddress, LittleWeebLibrary.Handlers.IrcClientHandler.StartConnection(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonIrcInfo.ToJson(), LittleWeebLibrary.Settings.IrcSettings.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), LittleWeebLibrary.Settings.IrcSettings.UserName, and LittleWeebLibrary.Handlers.SettingsHandler.WriteIrcSettings().
Referenced by LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("Connect called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            bool succes = false;
            try
            {
                if (ircJson == null)
                {
                    string username = IrcSettings.UserName;
                    if (username == "")
                    {
                        username = UtilityMethods.GenerateUsername(
      LittleWeebSettings.RandomUsernameLength);
                    }
                    IrcSettings.UserName = username;
                }
                else
                {
                    DebugHandler.TraceMessage(ircJson.ToString(),
      DebugSource.TASK, DebugType.INFO);
                    string username = ircJson.Value<string>("username");
                    if (username == "")
                    {
                        username = UtilityMethods.GenerateUsername(
      LittleWeebSettings.RandomUsernameLength);
                    }
                    IrcSettings.ServerAddress = ircJson.Value<string>("address");
                    IrcSettings.Channels = ircJson.Value<string>("channels");
                    IrcSettings.UserName = username;
                }
                succes = IrcClientHandler.StartConnection(
      IrcSettings);
                if (succes)
                {
                    JsonIrcInfo ircInfo = new JsonIrcInfo()
                    {
                        connected = succes,
                        channel = IrcSettings.Channels,
                        server = IrcSettings.ServerAddress,
                        user = IrcSettings.UserName,
                        fullfilepath = IrcSettings.fullfilepath
                    };
                    await WebSocketHandler.SendMessage(ircInfo.
      ToJson());
                }
                else
                {
                    JsonIrcInfo ircInfo = new JsonIrcInfo()
                    {
                        connected = succes,
                        channel = IrcSettings.Channels,
                        server = IrcSettings.ServerAddress,
                        user = IrcSettings.UserName,
                        fullfilepath = IrcSettings.fullfilepath
                    };
                    await WebSocketHandler.SendMessage(ircInfo.
      ToJson());
                }
                DebugHandler.TraceMessage("Started irc connection using the
       following settings: " + IrcSettings.ToString(), DebugSource.TASK,
      DebugType.INFO);
                SettingsHandler.WriteIrcSettings(
      IrcSettings);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonIrcInfo ircInfo = new JsonIrcInfo()
                {
                    connected = succes,
                    channel = IrcSettings.Channels,
                    server = IrcSettings.ServerAddress,
                    user = IrcSettings.UserName,
                    fullfilepath = IrcSettings.fullfilepath
                };
                await WebSocketHandler.SendMessage(ircInfo.
      ToJson());
                JsonError error = new JsonError()
                {
                    type = "irc_connect_error",
                    errormessage = "Could not start connection to irc server.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
            IsIrcConnected = succes;
        }
GetCurrentIrcSettings()
async Task LittleWeebLibrary.Services.IrcWebSocketService.GetCurrentIrcSettings ()
Implements LittleWeebLibrary.Services.IIrcWebSocketService.
Definition at line 153 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.Channels, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Settings.IrcSettings.ServerAddress, LittleWeebLibrary.Models.JsonIrcInfo.ToJson(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Settings.IrcSettings.UserName.
Referenced by LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("GetCurrentIrcSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JsonIrcInfo ircInfo = new JsonIrcInfo()
            {
                connected = IsIrcConnected,
                channel = IrcSettings.Channels,
                server = IrcSettings.ServerAddress,
                user = IrcSettings.UserName,
                fullfilepath= IrcSettings.fullfilepath
            };
            await WebSocketHandler.SendMessage(ircInfo.
      ToJson());
        }
EnableSendMessage()
async Task LittleWeebLibrary.Services.IrcWebSocketService.EnableSendMessage ()
Implements LittleWeebLibrary.Services.IIrcWebSocketService.
Definition at line 169 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonSuccess.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("EnableSendMessage called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            SendMessageToWebSocketClient = true;
            JsonSuccess jsonSuccess = new JsonSuccess()
            {
                message = "Succesfully enabled sending IRC messages to client."
            };
            await WebSocketHandler.SendMessage(jsonSuccess.
      ToJson());
        }
DisableSendMessage()
async Task LittleWeebLibrary.Services.IrcWebSocketService.DisableSendMessage ()
Implements LittleWeebLibrary.Services.IIrcWebSocketService.
Definition at line 182 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonSuccess.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("DisableSendMessage called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            SendMessageToWebSocketClient = false;
            JsonSuccess jsonSuccess = new JsonSuccess()
            {
                message = "Succesfully disabled sending IRC messages to client."
            };
            await WebSocketHandler.SendMessage(jsonSuccess.
      ToJson());
        }
Disconnect()
async Task LittleWeebLibrary.Services.IrcWebSocketService.Disconnect ()
Implements LittleWeebLibrary.Services.IIrcWebSocketService.
Definition at line 195 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.Channels, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Settings.IrcSettings.ServerAddress, LittleWeebLibrary.Handlers.IrcClientHandler.StopConnection(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonIrcInfo.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Settings.IrcSettings.UserName.
Referenced by LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("Disconnect called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            bool succes = false;
            try
            {
                succes = IrcClientHandler.StopConnection();
                JsonIrcInfo ircInfo = new JsonIrcInfo()
                {
                    connected = !succes,
                    channel = IrcSettings.Channels,
                    server = IrcSettings.ServerAddress,
                    user = IrcSettings.UserName,
                    fullfilepath = IrcSettings.fullfilepath
                };
                await WebSocketHandler.SendMessage(ircInfo.
      ToJson());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                succes = IrcClientHandler.StopConnection();
                JsonIrcInfo ircInfo = new JsonIrcInfo()
                {
                    connected = !succes,
                    channel = IrcSettings.Channels,
                    server = IrcSettings.ServerAddress,
                    user = IrcSettings.UserName,
                    fullfilepath = IrcSettings.fullfilepath
                };
                await WebSocketHandler.SendMessage(ircInfo.
      ToJson());
                JsonError error = new JsonError()
                {
                    type = "irc_disconnect_error",
                    errormessage = "Could not stop connection to irc server.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
SendMessage()
async Task LittleWeebLibrary.Services.IrcWebSocketService.SendMessage (JObject ircMessageJson)
Implements LittleWeebLibrary.Services.IIrcWebSocketService.
Definition at line 242 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Handlers.IrcClientHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent().
        {
            DebugHandler.TraceMessage("SendMessage called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(ircMessageJson.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string message = ircMessageJson.Value<string>("message");
                IrcClientHandler.SendMessage(message);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "irc_connect_error",
                    errormessage = "Could not send message to irc server.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
OnIrcClientMessageEvent()
async void LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientMessageEvent (object sender, IrcClientMessageEventArgs args) [private]
Definition at line 268 of file IrcWebSocketService.cs.
References LittleWeebLibrary.EventArguments.IrcClientMessageEventArgs.Channel, LittleWeebLibrary.EventArguments.IrcClientMessageEventArgs.Message, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonIrcChatMessage.ToJson(), LittleWeebLibrary.EventArguments.IrcClientMessageEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.EventArguments.IrcClientMessageEventArgs.User.
        {
            DebugHandler.TraceMessage("OnIrcClientMessageEvent called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                if (SendMessageToWebSocketClient)
                {
                    JsonIrcChatMessage messageToSend = new
      JsonIrcChatMessage()
                    {
                        channel = args.Channel,
                        user = args.User,
                        message = args.Message
                    };
                    await WebSocketHandler.SendMessage(messageToSend.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                if (SendMessageToWebSocketClient)
                {
                    JsonError error = new JsonError()
                    {
                        type = "irc_status_error",
                        errormessage = "Error on sending irc message to client.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    await WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
        }
OnIrcClientConnectionStatusEvent()
async void LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientConnectionStatusEvent (object sender, IrcClientConnectionStatusArgs args) [private]
Definition at line 307 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.Channels, LittleWeebLibrary.EventArguments.IrcClientConnectionStatusArgs.Connected, LittleWeebLibrary.EventArguments.IrcClientConnectionStatusArgs.CurrentIrcSettings, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Settings.IrcSettings.ServerAddress, LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonIrcInfo.ToJson(), LittleWeebLibrary.EventArguments.IrcClientConnectionStatusArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Settings.IrcSettings.UserName.
        {
            DebugHandler.TraceMessage("OnIrcClientConnectionStatusEvent called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IsIrcConnected = args.Connected;
            try
            {
                JsonIrcInfo update = new JsonIrcInfo()
                {
                    connected = args.Connected,
                    channel = args.CurrentIrcSettings.Channels,
                    server = args.CurrentIrcSettings.
      ServerAddress,
                    user = args.CurrentIrcSettings.UserName,
                    fullfilepath= args.CurrentIrcSettings.
      fullfilepath
                };
                await WebSocketHandler.SendMessage(update.
      ToJson());
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "irc_status_error",
                    errormessage = "Error on sending irc status update to client.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                await WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
SetIrcSettings()
void LittleWeebLibrary.Services.IrcWebSocketService.SetIrcSettings (IrcSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 342 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Settings.IrcSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetIrcSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IrcSettings = settings;
        }
SetLittleWeebSettings()
void LittleWeebLibrary.Services.IrcWebSocketService.SetLittleWeebSettings (LittleWeebSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 349 of file IrcWebSocketService.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetLittleWeebSettings called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            LittleWeebSettings = settings;
        }
Member Data Documentation
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Services.IrcWebSocketService.WebSocketHandler [private]
Definition at line 24 of file IrcWebSocketService.cs.
IrcClientHandler
readonly IIrcClientHandler LittleWeebLibrary.Services.IrcWebSocketService.IrcClientHandler [private]
Definition at line 25 of file IrcWebSocketService.cs.
SettingsHandler
readonly ISettingsHandler LittleWeebLibrary.Services.IrcWebSocketService.SettingsHandler [private]
Definition at line 26 of file IrcWebSocketService.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Services.IrcWebSocketService.DebugHandler [private]
Definition at line 27 of file IrcWebSocketService.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Services.IrcWebSocketService.LittleWeebSettings [private]
Definition at line 30 of file IrcWebSocketService.cs.
IrcSettings
IrcSettings LittleWeebLibrary.Services.IrcWebSocketService.IrcSettings [private]
Definition at line 31 of file IrcWebSocketService.cs.
SendMessageToWebSocketClient
bool LittleWeebLibrary.Services.IrcWebSocketService.SendMessageToWebSocketClient [private]
Definition at line 33 of file IrcWebSocketService.cs.
IsIrcConnected
bool LittleWeebLibrary.Services.IrcWebSocketService.IsIrcConnected [private]
Definition at line 34 of file IrcWebSocketService.cs.
The documentation for this class was generated from the following file:
Services/IrcWebSocketService.cs