LittleWeebLibrary.StaticClasses.UtilityMethods Class Reference
Public Types
enum OperatingSystems { OperatingSystems.Windows,
OperatingSystems.OsX,
OperatingSystems.Linux,
OperatingSystems.Unknown
 }
Static Public Member Functions
static string BasePath ()
static double CalculateSimilarity (string source, string target)
Calculate percentage similarity of two strings
Parameters
source Source String to Compare with
target Targeted String to Compare
Returns
Return Similarity between two strings from 0 to 1.0
static OperatingSystems CheckOperatingSystems ()
static void CopyTo (Stream src, Stream dest)
static string GenerateUsername (int requestedLength)
static long GetEpoch ()
static long GetFreeSpaceKbits (string path)
static string IntToRoman (int num)
static async Task< byte[]> ReadBinaryFile (string path)
static string RemoveSpecialCharacters (string str)
static async Task< string > Unzip (byte[] bytes)
static async Task< bool > WriteBinaryFile (string path, byte[] value)
static async Task< byte[]> Zip (string str)
Static Private Member Functions
static int LevenshteinDistance (string source, string target)
https://stackoverflow.com/a/40775015/4564466
Detailed Description
Definition at line 12 of file UtilityMethods.cs.
Member Enumeration Documentation
OperatingSystems
enum LittleWeebLibrary.StaticClasses.UtilityMethods.OperatingSystems [strong]
Enumerator
Windows
OsX
Linux
Unknown
Definition at line 15 of file UtilityMethods.cs.
        {
            Windows,
            OsX,
            Linux,
            Unknown
        }
Member Function Documentation
RemoveSpecialCharacters()
static string LittleWeebLibrary.StaticClasses.UtilityMethods.RemoveSpecialCharacters (string str) [static]
Definition at line 23 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.ParseTitles().
        {
            return Regex.Replace(str, "[^0-9A-Za-z ,]", " ");
        }
GetEpoch()
static long LittleWeebLibrary.StaticClasses.UtilityMethods.GetEpoch () [static]
Definition at line 29 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeEpisodes(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeProfile(), and LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring().
        {
            DateTime epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            TimeSpan mili = DateTime.Now - epoch;
            return (long)mili.TotalMilliseconds;
        }
IntToRoman()
static string LittleWeebLibrary.StaticClasses.UtilityMethods.IntToRoman (int num) [static]
Definition at line 36 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.ParseTitles().
        {
            string[] thou = { "", "M", "MM", "MMM" };
            string[] hun = { "", "C", "CC", "CCC", "CD", "D", "DC", "DCC", "DCCC", "CM" };
            string[] ten = { "", "X", "XX", "XXX", "XL", "L", "LX", "LXX", "LXXX", "XC" };
            string[] ones = { "", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX" };
            string roman = "";
            roman += thou[(int)(num / 1000) % 10];
            roman += hun[(int)(num / 100) % 10];
            roman += ten[(int)(num / 10) % 10];
            roman += ones[num % 10];
            return roman;
        }
GenerateUsername()
static string LittleWeebLibrary.StaticClasses.UtilityMethods.GenerateUsername (int requestedLength) [static]
Definition at line 51 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.Connect().
        {
            
            Random rnd = new Random();
            string[] consonants = { "b", "c", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "q", "r", "
      s", "t", "v", "w", "x", "y", "z" };
            string[] vowels = { "a", "e", "i", "o", "u" };
            string word = "";
            if (requestedLength == 1)
            {
                word = vowels[rnd.Next(0, vowels.Length - 1)];
            }
            else
            {
                for (int i = 0; i < requestedLength; i += 2)
                {
                    word += consonants[rnd.Next(0, consonants.Length - 1)] + vowels[rnd.Next(0, vowels.
      Length - 1)];
                }
                word = word.Replace("q", "qu").Substring(0, requestedLength); // We may generate a string
       longer than requested length, but it doesn't matter if cut off the excess.
            }
            return word;
        }
GetFreeSpaceKbits()
static long LittleWeebLibrary.StaticClasses.UtilityMethods.GetFreeSpaceKbits (string path) [static]
Definition at line 78 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.AddDownload(), LittleWeebLibrary.Handlers.DownloadHandler.AddDownloads(), and LittleWeebLibrary.Handlers.DirectoryHandler.GetFreeSpace().
        {
            DriveInfo[] systemDrives = DriveInfo.GetDrives();
            foreach (DriveInfo i in systemDrives)
            {
                if (path.IndexOf(i.Name) > -1)
                {
                    return (i.TotalFreeSpace / 128); //bytes -> kbits
                }
            }
            return 0;
        }
CopyTo()
static void LittleWeebLibrary.StaticClasses.UtilityMethods.CopyTo (Stream src, Stream dest) [static]
Definition at line 93 of file UtilityMethods.cs.
        {
            byte[] bytes = new byte[4096];
            int cnt;
            while ((cnt = src.Read(bytes, 0, bytes.Length)) != 0)
            {
                dest.Write(bytes, 0, cnt);
            }
        }
Zip()
static async Task<byte[]> LittleWeebLibrary.StaticClasses.UtilityMethods.Zip (string str) [static]
Definition at line 105 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject().
        {
            byte[] bytes = Encoding.UTF8.GetBytes(str);
            await Task.Run(() => {
                using (var msi = new MemoryStream(bytes))
                using (var mso = new MemoryStream())
                {
                    using (var gs = new GZipStream(mso, CompressionMode.Compress))
                    {
                        //msi.CopyTo(gs);
                        CopyTo(msi, gs);
                    }
                    bytes = mso.ToArray();
                }
            });
          
            return bytes;
        }
Unzip()
static async Task<string> LittleWeebLibrary.StaticClasses.UtilityMethods.Unzip (byte [] bytes) [static]
Definition at line 127 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.DataBaseHandler.GetCollection(), LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject(), and LittleWeebLibrary.Handlers.DataBaseHandler.RemoveJObject().
        {
            string toreturn = string.Empty;
            await Task.Run(() =>
            {
                using (var msi = new MemoryStream(bytes))
                using (var mso = new MemoryStream())
                {
                    using (var gs = new GZipStream(msi, CompressionMode.Decompress))
                    {
                        //gs.CopyTo(mso);
                        CopyTo(gs, mso);
                    }
                    toreturn = Encoding.UTF8.GetString(mso.ToArray());
                }
            });
            return toreturn;
        }
WriteBinaryFile()
static async Task<bool> LittleWeebLibrary.StaticClasses.UtilityMethods.WriteBinaryFile (string path, byte [] value) [static]
Definition at line 149 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.DataBaseHandler.StoreJObject().
        {
            bool toreturn = false;
            await Task.Run(() =>
            {
                try
                {
                    using (BinaryWriter writer = new BinaryWriter(File.Open(path, FileMode.OpenOrCreate,
      System.IO.FileAccess.ReadWrite)))
                    {
                        writer.Write(value);
                    }
                    toreturn = true;
                }
                catch
                {
                    toreturn = false;
                }
            });
            return toreturn;
        }
ReadBinaryFile()
static async Task<byte[]> LittleWeebLibrary.StaticClasses.UtilityMethods.ReadBinaryFile (string path) [static]
Definition at line 170 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.Handlers.DataBaseHandler.GetCollection(), LittleWeebLibrary.Handlers.DataBaseHandler.GetJObject(), and LittleWeebLibrary.Handlers.DataBaseHandler.RemoveJObject().
        {
            byte[] value = new byte[0];
            await Task.Run(() =>
            {
                using (BinaryReader reader = new BinaryReader(File.Open(path, FileMode.OpenOrCreate,
      System.IO.FileAccess.ReadWrite)))
                {
                    const int bufferSize = 4096;
                    using (var ms = new MemoryStream())
                    {
                        byte[] buffer = new byte[bufferSize];
                        int count;
                        while ((count = reader.Read(buffer, 0, buffer.Length)) != 0)
                            ms.Write(buffer, 0, count);
                        value = ms.ToArray();
                    }
                }
            });
            return value;
        }
CheckOperatingSystems()
static OperatingSystems LittleWeebLibrary.StaticClasses.UtilityMethods.CheckOperatingSystems () [static]
Definition at line 192 of file UtilityMethods.cs.
Referenced by LittleWeebLibrary.StaticClasses.UtilityMethods.BasePath(), LittleWeebLibrary.Handlers.VersionHandler.GetLatestVersionDesktop(), LittleWeebLibrary.Handlers.DirectoryHandler.OpenDirectory(), and LittleWeebLibrary.Handlers.FileHandler.OpenFile().
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) {
                return OperatingSystems.Linux;
            }
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                return OperatingSystems.OsX;
            }
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                return OperatingSystems.Windows;
            }
            return OperatingSystems.Unknown;
        }
BasePath()
static string LittleWeebLibrary.StaticClasses.UtilityMethods.BasePath () [static]
Definition at line 214 of file UtilityMethods.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.CheckOperatingSystems().
Referenced by LittleWeebLibrary.Handlers.DataBaseHandler.DataBaseHandler(), and LittleWeebLibrary.Handlers.SettingsHandler.SettingsHandler().
        {
            string path = "";
#if __ANDROID__
             path = PortablePath.Combine(PortablePath.Combine(Android.OS.Environment.
      ExternalStorageDirectory.AbsolutePath, "LittleWeeb"), "DataBase");
#else
            switch (UtilityMethods.CheckOperatingSystems())
            {
                case UtilityMethods.OperatingSystems.Linux:
                    path = PortablePath.Combine(Environment.GetFolderPath(Environment.SpecialFolder.
      Personal), ".LittleWeeb");
                    break;
                case UtilityMethods.OperatingSystems.Windows:
                    path = PortablePath.Combine(Environment.GetFolderPath(Environment.SpecialFolder.
      MyDocuments), "LittleWeeb");
                    break;
                case UtilityMethods.OperatingSystems.OsX:
                    path = PortablePath.Combine(PortablePath.Combine(Environment.GetFolderPath(Environment.
      SpecialFolder.MyDocuments), "Library"), ".LittleWeeb");
                    break;
            }
#endif
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            return path;
        }
LevenshteinDistance()
static int LittleWeebLibrary.StaticClasses.UtilityMethods.LevenshteinDistance (string source, string target) [static], [private]
https://stackoverflow.com/a/40775015/4564466
Parameters
source
target
Returns
Definition at line 248 of file UtilityMethods.cs.
        {
            // degenerate cases
            if (source == target) return 0;
            if (source.Length == 0) return target.Length;
            if (target.Length == 0) return source.Length;
            // create two work vectors of integer distances
            int[] v0 = new int[target.Length + 1];
            int[] v1 = new int[target.Length + 1];
            // initialize v0 (the previous row of distances)
            // this row is A[0][i]: edit distance for an empty s
            // the distance is just the number of characters to delete from t
            for (int i = 0; i < v0.Length; i++)
                v0[i] = i;
            for (int i = 0; i < source.Length; i++)
            {
                // calculate v1 (current row distances) from the previous row v0
                // first element of v1 is A[i+1][0]
                // edit distance is delete (i+1) chars from s to match empty t
                v1[0] = i + 1;
                // use formula to fill in the rest of the row
                for (int j = 0; j < target.Length; j++)
                {
                    var cost = (source[i] == target[j]) ? 0 : 1;
                    v1[j + 1] = Math.Min(v1[j] + 1, Math.Min(v0[j + 1] + 1, v0[j] + cost));
                }
                // copy v1 (current row) to v0 (previous row) for next iteration
                for (int j = 0; j < v0.Length; j++)
                    v0[j] = v1[j];
            }
            return v1[target.Length];
        }
CalculateSimilarity()
static double LittleWeebLibrary.StaticClasses.UtilityMethods.CalculateSimilarity (string source, string target) [static]
Calculate percentage similarity of two strings
Parameters
source Source String to Compare with
target Targeted String to Compare
Returns
Return Similarity between two strings from 0 to 1.0
Definition at line 294 of file UtilityMethods.cs.
        {
            if ((source == null) || (target == null)) return 0.0;
            if ((source.Length == 0) || (target.Length == 0)) return 0.0;
            if (source == target) return 1.0;
            int stepsToSame = LevenshteinDistance(source, target);
            return (1.0 - ((double)stepsToSame / (double)Math.Max(source.Length, target.Length)));
        }
The documentation for this class was generated from the following file:
StaticClasses/UtilityMethods.cs