LittleWeebLibrary.Controllers.BaseWebSocketController Class Reference
Public Member Functions
BaseWebSocketController (IWebSocketHandler webSocketHandler, IDebugHandler debugHandler)
void SetSubControllers (List< ISubWebSocketController > subControllers)
Private Member Functions
void OnWebSocketEvent (object sender, WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
List< ISubWebSocketController > SubControllers
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 13 of file BaseWebSocketController.cs.
Constructor & Destructor Documentation
BaseWebSocketController()
LittleWeebLibrary.Controllers.BaseWebSocketController.BaseWebSocketController (IWebSocketHandler webSocketHandler, IDebugHandler debugHandler)
Definition at line 20 of file BaseWebSocketController.cs.
References LittleWeebLibrary.Handlers.WebSocketHandler.OnWebSocketEvent, and LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            WebSocketHandler = webSocketHandler;
            WebSocketHandler.OnWebSocketEvent +=
      OnWebSocketEvent;
        }
Member Function Documentation
SetSubControllers()
void LittleWeebLibrary.Controllers.BaseWebSocketController.SetSubControllers (List< ISubWebSocketController > subControllers)
Implements LittleWeebLibrary.Controllers.IBaseWebSocketController.
Definition at line 32 of file BaseWebSocketController.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetSubControllers called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            SubControllers = subControllers;
        }
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.BaseWebSocketController.OnWebSocketEvent (object sender, WebSocketEventArgs args) [private]
Definition at line 38 of file BaseWebSocketController.cs.
References LittleWeebLibrary.Controllers.ISubWebSocketController.OnWebSocketEvent(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try{
                foreach (ISubWebSocketController controller in SubControllers)
                {
                    controller.OnWebSocketEvent(args);
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
            }
        }
Member Data Documentation
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.BaseWebSocketController.WebSocketHandler [private]
Definition at line 16 of file BaseWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.BaseWebSocketController.DebugHandler [private]
Definition at line 17 of file BaseWebSocketController.cs.
SubControllers
List<ISubWebSocketController> LittleWeebLibrary.Controllers.BaseWebSocketController.SubControllers [private]
Definition at line 18 of file BaseWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/BaseWebSocketController.cs