LittleWeebLibrary.Models.JsonIrcInfo Class Reference
Public Member Functions
JObject ToJObject ()
string ToJson ()
override string ToString ()
Public Attributes
string type = `irc_data`
Properties
string channel = string.Empty [get, set]
bool connected = false [get, set]
string fullfilepath = string.Empty [get, set]
string server = string.Empty [get, set]
string updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get, set]
string user = string.Empty [get, set]
Detailed Description
Definition at line 7 of file JsonIrcInfo.cs.
Member Function Documentation
ToJson()
string LittleWeebLibrary.Models.JsonIrcInfo.ToJson ()
Definition at line 17 of file JsonIrcInfo.cs.
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.IrcWebSocketService.Disconnect(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.Services.IrcWebSocketService.GetCurrentIrcSettings(), and LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientConnectionStatusEvent().
        {
            return JsonConvert.SerializeObject(this);
        }
ToString()
override string LittleWeebLibrary.Models.JsonIrcInfo.ToString ()
Definition at line 21 of file JsonIrcInfo.cs.
        {
            JObject jobject = ToJObject();
            string properties = string.Empty;
            foreach (var x in jobject)
            {
                properties += x.Key + ": " + x.Value.ToString();
            }
            return properties;
        }
ToJObject()
JObject LittleWeebLibrary.Models.JsonIrcInfo.ToJObject ()
Definition at line 32 of file JsonIrcInfo.cs.
        {
            JObject jobject = JObject.FromObject(this);
            return jobject;
        }
Member Data Documentation
type
string LittleWeebLibrary.Models.JsonIrcInfo.type = `irc_data`
Definition at line 9 of file JsonIrcInfo.cs.
Property Documentation
connected
bool LittleWeebLibrary.Models.JsonIrcInfo.connected = false [get], [set]
Definition at line 10 of file JsonIrcInfo.cs.
{ get; set; } = false;
channel
string LittleWeebLibrary.Models.JsonIrcInfo.channel = string.Empty [get], [set]
Definition at line 11 of file JsonIrcInfo.cs.
{ get; set; } = string.Empty;
server
string LittleWeebLibrary.Models.JsonIrcInfo.server = string.Empty [get], [set]
Definition at line 12 of file JsonIrcInfo.cs.
{ get; set; } = string.Empty;
user
string LittleWeebLibrary.Models.JsonIrcInfo.user = string.Empty [get], [set]
Definition at line 13 of file JsonIrcInfo.cs.
{ get; set; } = string.Empty;
fullfilepath
string LittleWeebLibrary.Models.JsonIrcInfo.fullfilepath = string.Empty [get], [set]
Definition at line 14 of file JsonIrcInfo.cs.
{ get; set; } = string.Empty;
updated
string LittleWeebLibrary.Models.JsonIrcInfo.updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get], [set]
Definition at line 15 of file JsonIrcInfo.cs.
{ get; set; } = StaticClasses.UtilityMethods.GetEpoch().ToString();
The documentation for this class was generated from the following file:
Models/JsonIrcInfo.cs