LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController Class Reference
Public Member Functions
DirectoryWebSocketController (IWebSocketHandler webSocketHandler, IDirectoryWebSocketService directoryWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IDirectoryWebSocketService DirectoryWebSocketService
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 12 of file DirectoryWebSocketController.cs.
Constructor & Destructor Documentation
DirectoryWebSocketController()
LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.DirectoryWebSocketController (IWebSocketHandler webSocketHandler, IDirectoryWebSocketService directoryWebSocketService, IDebugHandler debugHandler)
Definition at line 21 of file DirectoryWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Contructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            DirectoryWebSocketService = directoryWebSocketService;
            WebSocketHandler = webSocketHandler;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 30 of file DirectoryWebSocketController.cs.
References LittleWeebLibrary.Services.DirectoryWebSocketService.CreateDirectory(), LittleWeebLibrary.Services.DirectoryWebSocketService.DeleteDirectory(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDirectories(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDrives(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try
                {
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        JObject extra = query.Value<JObject>("extra");
                        if (extra != null)
                        {
                            switch (action)
                            {
                                case "create_directory":
                                    DirectoryWebSocketService.
      CreateDirectory(extra);
                                    break;
                                case "delete_directory":
                                    DirectoryWebSocketService.
      DeleteDirectory(extra);
                                    break;
                                case "get_directories":
                                    DirectoryWebSocketService.
      GetDirectories(extra);
                                    break;
                            }
                        }
                        else
                        {
                            switch (action)
                            {
                                case "get_directories":
                                    DirectoryWebSocketService.
      GetDrives();
                                    break;
                            }
                        }
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                   
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
               
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.WebSocketHandler [private]
Definition at line 17 of file DirectoryWebSocketController.cs.
DirectoryWebSocketService
readonly IDirectoryWebSocketService LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.DirectoryWebSocketService [private]
Definition at line 18 of file DirectoryWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.DebugHandler [private]
Definition at line 19 of file DirectoryWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/DirectoryWebSocketController.cs