LittleWeebLibrary.Models.JsonSuccess Class Reference
Public Member Functions
JObject ToJObject ()
string ToJson ()
override string ToString ()
Public Attributes
string type = `success`
Properties
string message = string.Empty [get, set]
string updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get, set]
Detailed Description
Definition at line 7 of file JsonSuccess.cs.
Member Function Documentation
ToJson()
string LittleWeebLibrary.Models.JsonSuccess.ToJson ()
Definition at line 14 of file JsonSuccess.cs.
Referenced by LittleWeebLibrary.Services.InfoApiWebSocketService.AddRule(), LittleWeebLibrary.Handlers.DirectoryHandler.DeleteDirectory(), LittleWeebLibrary.Services.DataBaseWebSocketService.DeleteDocument(), LittleWeebLibrary.Handlers.FileHandler.DeleteFile(), LittleWeebLibrary.Services.IrcWebSocketService.DisableSendMessage(), LittleWeebLibrary.Services.IrcWebSocketService.EnableSendMessage(), LittleWeebLibrary.Handlers.DirectoryHandler.OpenDirectory(), LittleWeebLibrary.Handlers.FileHandler.OpenFile(), LittleWeebLibrary.Services.DataBaseWebSocketService.StoreDocument(), and LittleWeebLibrary.Services.DataBaseWebSocketService.UpdateDocument().
        {
            return JsonConvert.SerializeObject(this);
        }
ToString()
override string LittleWeebLibrary.Models.JsonSuccess.ToString ()
Definition at line 18 of file JsonSuccess.cs.
        {
            JObject jobject = ToJObject();
            string properties = string.Empty;
            foreach (var x in jobject)
            {
                properties += x.Key + ": " + x.Value.ToString();
            }
            return properties;
        }
ToJObject()
JObject LittleWeebLibrary.Models.JsonSuccess.ToJObject ()
Definition at line 29 of file JsonSuccess.cs.
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.AbortDownload(), and LittleWeebLibrary.Handlers.DownloadHandler.StopQueue().
        {
            JObject jobject = JObject.FromObject(this);
            return jobject;
        }
Member Data Documentation
type
string LittleWeebLibrary.Models.JsonSuccess.type = `success`
Definition at line 10 of file JsonSuccess.cs.
Property Documentation
message
string LittleWeebLibrary.Models.JsonSuccess.message = string.Empty [get], [set]
Definition at line 11 of file JsonSuccess.cs.
{ get; set; } = string.Empty;
updated
string LittleWeebLibrary.Models.JsonSuccess.updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get], [set]
Definition at line 12 of file JsonSuccess.cs.
{ get; set; } = StaticClasses.UtilityMethods.GetEpoch().ToString();
The documentation for this class was generated from the following file:
Models/JsonSuccess.cs