LittleWeebLibrary.Handlers.IrcClientHandler Class Reference
Public Member Functions
IrcClientHandler (ISettingsHandler settingsHandler, IDebugHandler debugHandler)
IrcSettings CurrentSettings ()
bool IsConnected ()
bool IsDownloading ()
void SendMessage (string message)
void Setfullfilepath (string path)
void SetIrcSettings (IrcSettings settings)
void SetLittleWeebSettings (LittleWeebSettings settings)
bool StartConnection (IrcSettings settings=null)
void StartDownload (JsonDownloadInfo download)
bool StopConnection ()
bool StopDownload ()
Events
EventHandler< IrcClientConnectionStatusArgs > OnIrcClientConnectionStatusEvent
EventHandler< IrcClientDownloadEventArgs > OnIrcClientDownloadEvent
EventHandler< IrcClientMessageEventArgs > OnIrcClientMessageEvent
Private Member Functions
void OnDownloadUpdate (object sender, DCCEventArgs args)
void OnDownloadUpdateDebug (object sender, DCCDebugMessageArgs args)
void OnMessage (object sender, IrcReceivedEventArgs args)
void OnMessageDebug (object sender, IrcDebugMessageEventArgs args)
void OnUserListUpdate (object sender, IrcUserListReceivedEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
SimpleIRC IrcClient
IrcSettings IrcSettings
bool IsConnectedBool = false
LittleWeebSettings LittleWeebSettings
readonly ISettingsHandler SettingsHandler
Detailed Description
Definition at line 30 of file IrcClientHandler.cs.
Constructor & Destructor Documentation
IrcClientHandler()
LittleWeebLibrary.Handlers.IrcClientHandler.IrcClientHandler (ISettingsHandler settingsHandler, IDebugHandler debugHandler)
Definition at line 48 of file IrcClientHandler.cs.
References LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.Handlers.SettingsHandler.GetIrcSettings(), LittleWeebLibrary.Handlers.SettingsHandler.GetLittleWeebSettings(), and LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            SettingsHandler = settingsHandler;
            DebugHandler = debugHandler;
            IrcSettings = SettingsHandler.
      GetIrcSettings();
            LittleWeebSettings = SettingsHandler.
      GetLittleWeebSettings();
            IrcClient = new SimpleIRC();
            IrcClient.SetCustomDownloadDir(IrcSettings.
      fullfilepath);
            IrcClient.IrcClient.OnUserListReceived += OnUserListUpdate;
            IrcClient.IrcClient.OnMessageReceived += OnMessage;
            IrcClient.IrcClient.OnDebugMessage += OnMessageDebug;
            IrcClient.DccClient.OnDccEvent += OnDownloadUpdate;
            IrcClient.DccClient.OnDccDebugMessage +=
      OnDownloadUpdateDebug;
        }
Member Function Documentation
SetIrcSettings()
void LittleWeebLibrary.Handlers.IrcClientHandler.SetIrcSettings (IrcSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 69 of file IrcClientHandler.cs.
References LittleWeebLibrary.Settings.IrcSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetIrcSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IrcSettings = settings;
        }
SetLittleWeebSettings()
void LittleWeebLibrary.Handlers.IrcClientHandler.SetLittleWeebSettings (LittleWeebSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 76 of file IrcClientHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetLittleWeebSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            LittleWeebSettings = settings;
        }
Setfullfilepath()
void LittleWeebLibrary.Handlers.IrcClientHandler.Setfullfilepath (string path)
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 83 of file IrcClientHandler.cs.
References LittleWeebLibrary.Settings.IrcSettings.fullfilepath, and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("Setfullfilepath Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(path, DebugSource.TASK,
      DebugType.PARAMETERS);
            IrcClient.SetCustomDownloadDir(path);
            IrcSettings.fullfilepath= path;
        }
SendMessage()
void LittleWeebLibrary.Handlers.IrcClientHandler.SendMessage (string message)
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 91 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.SendMessage().
        {
            DebugHandler.TraceMessage("SendMessage Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(message,
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                if (IrcClient != null)
                {
                    if (IrcClient.IsClientRunning())
                    {
                        IrcClient.SendMessageToAll(message);
                    }
                    else
                    {
                       DebugHandler.TraceMessage("Irc client is not connected!",
      DebugSource.TASK, DebugType.WARNING);
                    }
                }
                else
                {
                    DebugHandler.TraceMessage("Irc client is not set!",
      DebugSource.TASK, DebugType.WARNING);
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
StartDownload()
void LittleWeebLibrary.Handlers.IrcClientHandler.StartDownload (JsonDownloadInfo download)
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 120 of file IrcClientHandler.cs.
References LittleWeebLibrary.Models.JsonDownloadInfo.bot, LittleWeebLibrary.Models.JsonDownloadInfo.downloadDirectory, LittleWeebLibrary.Models.JsonDownloadInfo.pack, LittleWeebLibrary.Models.JsonDownloadInfo.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.DownloadQueueHandler().
        {
            DebugHandler.TraceMessage("StartDownload Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(download.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                string xdccMessage = "/msg " + download.bot + " xdcc send #" + download.
      pack;
                IrcClient.SetCustomDownloadDir(download.
      downloadDirectory);
                SendMessage(xdccMessage);
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
        }
StartConnection()
bool LittleWeebLibrary.Handlers.IrcClientHandler.StartConnection (IrcSettings settings = null)
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 137 of file IrcClientHandler.cs.
References LittleWeebLibrary.Settings.IrcSettings.Channels, LittleWeebLibrary.Settings.IrcSettings.Port, LittleWeebLibrary.Settings.IrcSettings.Secure, LittleWeebLibrary.Settings.IrcSettings.ServerAddress, LittleWeebLibrary.Handlers.DebugHandler.TraceMessage(), and LittleWeebLibrary.Settings.IrcSettings.UserName.
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.Connect().
        {
            DebugHandler.TraceMessage("StartConnection Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                if (settings != null)
                {
                    DebugHandler.TraceMessage(settings.
      ToString(), DebugSource.TASK, DebugType.PARAMETERS);
                    IrcSettings = settings;
                }
                IrcClient.SetupIrc(IrcSettings.ServerAddress,
      IrcSettings.UserName, IrcSettings.Channels,
      IrcSettings.Port, "", 3000, IrcSettings.Secure);
                Thread.Sleep(500);
                if (!IrcClient.StartClient())
                {
                    OnIrcClientConnectionStatusEvent?.Invoke(this, new
      IrcClientConnectionStatusArgs()
                    {
                        Connected = false,
                        ChannelsAndUsers = null
                    });
                    DebugHandler.TraceMessage("Irc client is could not connect!",
      DebugSource.TASK, DebugType.WARNING);
                    return false;
                }
                else
                {
                    DebugHandler.TraceMessage("Irc client is succesfully connected!
      ", DebugSource.TASK, DebugType.INFO);
                    return true;
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                return false;
            }
        }
StopConnection()
bool LittleWeebLibrary.Handlers.IrcClientHandler.StopConnection ()
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 176 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.Disconnect(), and LittleWeebLibrary.StartUp.Stop().
        {
            DebugHandler.TraceMessage("StopConnection Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                if (IrcClient.IsClientRunning())
                {
                    if (IrcClient.StopClient())
                    {
                        if (IrcClient.StopXDCCDownload())
                        {
                            DebugHandler.TraceMessage("Succesfully stopped download
       before stopping IRC Client!", DebugSource.TASK, DebugType.INFO);
                        }
                        OnIrcClientConnectionStatusEvent?.Invoke(this, new
      IrcClientConnectionStatusArgs()
                        {
                            Connected = false,
                            CurrentIrcSettings = IrcSettings
                        });
                        DebugHandler.TraceMessage("Succesfully stopped IRC Client!"
      , DebugSource.TASK, DebugType.INFO);
                        return true;
                    }
                    else
                    {
                        DebugHandler.TraceMessage("Could not stop connection with
       IRC server!", DebugSource.TASK, DebugType.WARNING);
                        return false;
                    }
                }
                else
                {
                    DebugHandler.TraceMessage("Irc client is is not connected!",
      DebugSource.TASK, DebugType.WARNING);
                    return true;
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                return false;
            }
        }
StopDownload()
bool LittleWeebLibrary.Handlers.IrcClientHandler.StopDownload ()
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 224 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.AbortDownload(), and LittleWeebLibrary.StartUp.Stop().
        {
            DebugHandler.TraceMessage("StopDownload Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            if (!IrcClient.StopXDCCDownload())
            {
                DebugHandler.TraceMessage("Could not stop download!",
      DebugSource.TASK, DebugType.WARNING);
                return false;
            }
            else
            {
                DebugHandler.TraceMessage("Succesfully stopped download!",
      DebugSource.TASK, DebugType.INFO);
                return true;
            }
        }
IsDownloading()
bool LittleWeebLibrary.Handlers.IrcClientHandler.IsDownloading ()
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 239 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.AbortDownload().
        {
            DebugHandler.TraceMessage("IsDownloading Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            return IrcClient.CheckIfDownload();
        }
IsConnected()
bool LittleWeebLibrary.Handlers.IrcClientHandler.IsConnected ()
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 245 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("IsConnected Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                if (IrcClient.IsClientRunning())
                {
                    IsConnectedBool = true;
                    return true;
                }
                else
                {
                    IsConnectedBool = false;
                    return false;
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                IsConnectedBool = false;
                return false;
            }
        }
CurrentSettings()
IrcSettings LittleWeebLibrary.Handlers.IrcClientHandler.CurrentSettings ()
Implements LittleWeebLibrary.Handlers.IIrcClientHandler.
Definition at line 270 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("CurrentSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            return IrcSettings;
        }
OnMessage()
void LittleWeebLibrary.Handlers.IrcClientHandler.OnMessage (object sender, IrcReceivedEventArgs args) [private]
Definition at line 276 of file IrcClientHandler.cs.
References LittleWeebLibrary.EventArguments.IrcClientMessageEventArgs.Channel, LittleWeebLibrary.EventArguments.IrcClientMessageEventArgs.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnMessage Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            IrcClientMessageEventArgs eventArgs = new
      IrcClientMessageEventArgs()
            {
                Channel = args.Channel,
                User = args.User,
                Message = args.Message
            };
            DebugHandler.TraceMessage(eventArgs.ToString(),
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            OnIrcClientMessageEvent?.Invoke(this, eventArgs);
        }
OnMessageDebug()
void LittleWeebLibrary.Handlers.IrcClientHandler.OnMessageDebug (object sender, IrcDebugMessageEventArgs args) [private]
Definition at line 292 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnMessageDebug Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.Type + " || " + args.Message,
      DebugSource.TASK, DebugType.INFO);
        }
OnUserListUpdate()
void LittleWeebLibrary.Handlers.IrcClientHandler.OnUserListUpdate (object sender, IrcUserListReceivedEventArgs args) [private]
Definition at line 298 of file IrcClientHandler.cs.
References LittleWeebLibrary.EventArguments.IrcClientConnectionStatusArgs.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnUserListUpdate Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            try
            {
                if (args.UsersPerChannel.Count > 0)
                {
                    IrcClientConnectionStatusArgs eventArgs = new
      IrcClientConnectionStatusArgs()
                    {
                        ChannelsAndUsers = args.UsersPerChannel,
                        Connected = true,
                        CurrentIrcSettings = IrcSettings
                    };
                    DebugHandler.TraceMessage(eventArgs.
      ToString(), DebugSource.TASK, DebugType.PARAMETERS);
                   
                    if (!IsConnectedBool)
                    {
                        OnIrcClientConnectionStatusEvent?.Invoke(this,
      eventArgs);
                    }
                    IsConnectedBool = true;
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
            }
           
        }
OnDownloadUpdate()
void LittleWeebLibrary.Handlers.IrcClientHandler.OnDownloadUpdate (object sender, DCCEventArgs args) [private]
Definition at line 331 of file IrcClientHandler.cs.
References LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.FileName, LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnDownloadUpdate Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            IrcClientDownloadEventArgs eventArgs = new
      IrcClientDownloadEventArgs()
            {
                FileName = args.FileName,
                FileLocation = args.FilePath,
                DownloadSpeed = args.KBytesPerSecond.ToString(),
                FileSize = (args.FileSize / 1048576),
                DownloadProgress = args.Progress,
                DownloadStatus = args.Status
            };
            DebugHandler.TraceMessage(eventArgs.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            OnIrcClientDownloadEvent?.Invoke(this, eventArgs);
        }
OnDownloadUpdateDebug()
void LittleWeebLibrary.Handlers.IrcClientHandler.OnDownloadUpdateDebug (object sender, DCCDebugMessageArgs args) [private]
Definition at line 350 of file IrcClientHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnDownloadUpdateDebug Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.Type + " || " + args.Message,
      DebugSource.TASK, DebugType.INFO);
        }
Member Data Documentation
SettingsHandler
readonly ISettingsHandler LittleWeebLibrary.Handlers.IrcClientHandler.SettingsHandler [private]
Definition at line 39 of file IrcClientHandler.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.IrcClientHandler.DebugHandler [private]
Definition at line 40 of file IrcClientHandler.cs.
IrcClient
SimpleIRC LittleWeebLibrary.Handlers.IrcClientHandler.IrcClient [private]
Definition at line 42 of file IrcClientHandler.cs.
IrcSettings
IrcSettings LittleWeebLibrary.Handlers.IrcClientHandler.IrcSettings [private]
Definition at line 43 of file IrcClientHandler.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Handlers.IrcClientHandler.LittleWeebSettings [private]
Definition at line 44 of file IrcClientHandler.cs.
IsConnectedBool
bool LittleWeebLibrary.Handlers.IrcClientHandler.IsConnectedBool = false [private]
Definition at line 46 of file IrcClientHandler.cs.
Event Documentation
OnIrcClientMessageEvent
EventHandler<IrcClientMessageEventArgs> LittleWeebLibrary.Handlers.IrcClientHandler.OnIrcClientMessageEvent
Definition at line 34 of file IrcClientHandler.cs.
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.IrcWebSocketService().
OnIrcClientDownloadEvent
EventHandler<IrcClientDownloadEventArgs> LittleWeebLibrary.Handlers.IrcClientHandler.OnIrcClientDownloadEvent
Definition at line 35 of file IrcClientHandler.cs.
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.DownloadHandler().
OnIrcClientConnectionStatusEvent
EventHandler<IrcClientConnectionStatusArgs> LittleWeebLibrary.Handlers.IrcClientHandler.OnIrcClientConnectionStatusEvent
Definition at line 36 of file IrcClientHandler.cs.
Referenced by LittleWeebLibrary.Services.IrcWebSocketService.IrcWebSocketService().
The documentation for this class was generated from the following file:
Handlers/IrcClientHandler.cs