LittleWeebLibrary.Controllers.DownloadWebSocketController Class Reference
Public Member Functions
DownloadWebSocketController (IWebSocketHandler webSocketHandler, IDownloadWebSocketService downloadWebSocketService, IDirectoryWebSocketService directoryWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IDirectoryWebSocketService DirectoryWebSocketService
readonly IDownloadWebSocketService DownloadWebSocketService
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 12 of file DownloadWebSocketController.cs.
Constructor & Destructor Documentation
DownloadWebSocketController()
LittleWeebLibrary.Controllers.DownloadWebSocketController.DownloadWebSocketController (IWebSocketHandler webSocketHandler, IDownloadWebSocketService downloadWebSocketService, IDirectoryWebSocketService directoryWebSocketService, IDebugHandler debugHandler)
Definition at line 22 of file DownloadWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            DownloadWebSocketService = downloadWebSocketService;
            WebSocketHandler = webSocketHandler;
            DirectoryWebSocketService = directoryWebSocketService;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 32 of file DownloadWebSocketController.cs.
References LittleWeebLibrary.Services.DownloadWebSocketService.AbortDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownloads(), LittleWeebLibrary.Services.DownloadWebSocketService.GetCurrentFileHistory(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetFreeSpace(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Services.DownloadWebSocketService.Openfullfilepath(), LittleWeebLibrary.Services.DownloadWebSocketService.RemoveDownload(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try
                {
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        JObject extra = query.Value<JObject>("extra");
                        if (extra != null)
                        {
                            switch (action)
                            {
                                case "add_download":
                                    DownloadWebSocketService.
      AddDownload(extra);
                                    break;
                                case "add_downloads":
                                    DownloadWebSocketService.
      AddDownloads(extra);
                                    break;
                                case "abort_download":
                                    DownloadWebSocketService.
      AbortDownload(extra);
                                    break;
                                case "remove_download":
                                    DownloadWebSocketService.
      RemoveDownload(extra);
                                    break;
                            }
                        }
                        else
                        {
                            switch (action)
                            {
                                case "get_downloads":
                                    DownloadWebSocketService.
      GetCurrentFileHistory();
                                    break;
                                case "get_free_space":
                                    DirectoryWebSocketService.
      GetFreeSpace();
                                    break;
                                case "open_download_directory":
                                    DownloadWebSocketService.
      Openfullfilepath();
                                    break;
                            }
                        }
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
DownloadWebSocketService
readonly IDownloadWebSocketService LittleWeebLibrary.Controllers.DownloadWebSocketController.DownloadWebSocketService [private]
Definition at line 17 of file DownloadWebSocketController.cs.
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.DownloadWebSocketController.WebSocketHandler [private]
Definition at line 18 of file DownloadWebSocketController.cs.
DirectoryWebSocketService
readonly IDirectoryWebSocketService LittleWeebLibrary.Controllers.DownloadWebSocketController.DirectoryWebSocketService [private]
Definition at line 19 of file DownloadWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.DownloadWebSocketController.DebugHandler [private]
Definition at line 20 of file DownloadWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/DownloadWebSocketController.cs