LittleWeebLibrary.Handlers.DownloadHandler Class Reference
Public Member Functions
DownloadHandler (IIrcClientHandler ircClientHandler, IFileHistoryHandler fileHistoryHandler, IFileHandler fileHandler, IDebugHandler debugHandler)
async Task< JObject > AbortDownload (string id=null)
async Task< JObject > AddDownload (JsonDownloadInfo download)
async Task< JObject > AddDownloads (List< JsonDownloadInfo > download)
JObject GetCurrentlyDownloading ()
async Task< JObject > RemoveDownload (string id=null, string filepath=null)
void SetIrcSettings (IrcSettings settings)
void SetLittleWeebSettings (LittleWeebSettings settings)
JObject StopQueue ()
Events
EventHandler< DownloadUpdateEventArgs > OnDownloadUpdateEvent
Private Member Functions
async Task DownloadQueueHandler ()
int IdGenerator (string animeId, string botName, string packnum, string episode, string season)
async void OnIrcClientDownloadEvent (object sender, IrcClientDownloadEventArgs args)
Private Attributes
JsonDownloadInfo CurrentlyDownloading
readonly IDebugHandler DebugHandler
bool DownloadProcesOnGoing = false
List< JsonDownloadInfo > DownloadQueue
readonly IFileHandler FileHandler
readonly IFileHistoryHandler FileHistoryHandler
readonly IIrcClientHandler IrcClientHandler
IrcSettings IrcSettings
bool Stop
Detailed Description
Definition at line 25 of file DownloadHandler.cs.
Constructor & Destructor Documentation
DownloadHandler()
LittleWeebLibrary.Handlers.DownloadHandler.DownloadHandler (IIrcClientHandler ircClientHandler, IFileHistoryHandler fileHistoryHandler, IFileHandler fileHandler, IDebugHandler debugHandler)
Definition at line 41 of file DownloadHandler.cs.
References LittleWeebLibrary.Handlers.IrcClientHandler.OnIrcClientDownloadEvent, LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("DownloadHandler", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            FileHistoryHandler = fileHistoryHandler;
            FileHandler = fileHandler;
            try
            {
                DownloadQueue = new List<JsonDownloadInfo>();
                IrcClientHandler = ircClientHandler;
                IrcClientHandler.OnIrcClientDownloadEvent +=
      OnIrcClientDownloadEvent;
                CurrentlyDownloading = new JsonDownloadInfo();
                Stop = false;
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method
       continues before the call is completed
                DownloadQueueHandler();
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method
       continues before the call is completed
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.CONSTRUCTOR, DebugType.ERROR);
            }
        }
Member Function Documentation
AddDownload()
async Task<JObject> LittleWeebLibrary.Handlers.DownloadHandler.AddDownload (JsonDownloadInfo download)
Implements LittleWeebLibrary.Handlers.IDownloadHandler.
Definition at line 67 of file DownloadHandler.cs.
References LittleWeebLibrary.Models.JsonDownloadInfo.anime_id, LittleWeebLibrary.Models.JsonDownloadInfo.anime_name, LittleWeebLibrary.Models.JsonDownloadInfo.bot, LittleWeebLibrary.Models.JsonDownloadInfo.downloadDirectory, LittleWeebLibrary.Models.JsonDownloadInfo.downloadIndex, LittleWeebLibrary.Models.JsonDownloadInfo.episodeNumber, LittleWeebLibrary.Models.JsonDownloadInfo.filesize, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.StaticClasses.UtilityMethods.GetFreeSpaceKbits(), LittleWeebLibrary.Models.JsonDownloadInfo.id, LittleWeebLibrary.Models.JsonDownloadInfo.pack, LittleWeebLibrary.Models.JsonDownloadInfo.season, LittleWeebLibrary.Models.JsonDownloadQueue.ToJObject(), LittleWeebLibrary.Models.JsonError.ToJObject(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Models.JsonDownloadInfo.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.AddDownload().
        {
            DebugHandler.TraceMessage("AddDownload Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(download.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            JObject toReturn = new JObject();
            await Task.Run(() =>
            {
                try
                {
                    if (UtilityMethods.GetFreeSpaceKbits(
      IrcSettings.fullfilepath) > long.Parse(download.filesize)) //kbits -> bytes
                    {
                        download.id = IdGenerator(download.anime_id, download.
      bot, download.pack, download.episodeNumber, download.season).ToString();
                        download.downloadDirectory = Path.Combine(
      IrcSettings.fullfilepath, download.anime_name);
                        if (!DownloadQueue.Exists(x => x.id == download.
      id) || CurrentlyDownloading.id != download.id)
                        {
                            download.downloadIndex = DownloadQueue.Count - 1;
                            DownloadQueue.Add(download);
                            DebugHandler.TraceMessage("Added download to queue: " +
       download.ToString(), DebugSource.TASK, DebugType.INFO);
                            JsonDownloadQueue current = new
      JsonDownloadQueue()
                            {
                                downloadQueue = DownloadQueue
                            };
                            toReturn = current.ToJObject();
                        }
                        else
                        {
                            DebugHandler.TraceMessage("Could not add download: " +
      download.ToString() + ", already exist in queue or is already being downloaded ",
      DebugSource.TASK, DebugType.WARNING);
                            JsonError error = new JsonError()
                            {
                                type = "file_already_being_downloaded_error",
                                errormessage = "Could not add download: " + download.
      ToString() + ", already exist in queue or is already being downloaded ",
                                errortype = "warning",
                                exception = "none"
                            };
                            toReturn = error.ToJObject();
                        }
                    }
                    else
                    {
                        DebugHandler.TraceMessage("Could not add download with
       filesize: " + download.filesize + " due to insufficient space required: " +
      UtilityMethods.GetFreeSpaceKbits(IrcSettings.
      fullfilepath).ToString(), DebugSource.TASK, DebugType.WARNING);
                        JsonError error = new JsonError()
                        {
                            type = "unsufficient_space_error",
                            errormessage = "Could not add download with filesize: " + download.
      filesize + " due to insufficient space required: " + UtilityMethods.
      GetFreeSpaceKbits(IrcSettings.fullfilepath).ToString().ToString(),
                            errortype = "warning"
                        };
                        toReturn = error.ToJObject();
                    }
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage("Could not add download with
       filesize: " + e.ToString(), DebugSource.TASK, DebugType.ERROR);
                    JsonError error = new JsonError()
                    {
                        type = "add_download_error",
                        errormessage = "Could not add download to queue.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    toReturn = error.ToJObject();
                }
            });
            return toReturn;
        }
RemoveDownload()
async Task<JObject> LittleWeebLibrary.Handlers.DownloadHandler.RemoveDownload (string id = null, string filepath = null)
Implements LittleWeebLibrary.Handlers.IDownloadHandler.
Definition at line 143 of file DownloadHandler.cs.
References LittleWeebLibrary.Models.JsonDownloadInfo.filename, LittleWeebLibrary.Models.JsonDownloadInfo.fullfilepath, LittleWeebLibrary.Models.JsonDownloadInfo.id, LittleWeebLibrary.Models.JsonDownloadQueue.ToJObject(), LittleWeebLibrary.Models.JsonError.ToJObject(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.FileWebSocketService.DeleteFile(), and LittleWeebLibrary.Services.DownloadWebSocketService.RemoveDownload().
        {
            DebugHandler.TraceMessage("Remove Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("ID: " + id,
      DebugSource.TASK, DebugType.PARAMETERS);
            DebugHandler.TraceMessage("FILEPATH: " + filepath,
      DebugSource.TASK, DebugType.PARAMETERS);
            JObject toReturn = new JObject();
            await Task.Run(async () =>
            {
                try
                {
                    int index = 0;
                    foreach (JsonDownloadInfo queuedDownload in
      DownloadQueue)
                    {
                        if (id != null)
                        {
                            if (queuedDownload.id == id)
                            {
                                DebugHandler.TraceMessage("Removed download at index: " + index.ToString()
      + " using id: " + id, DebugSource.TASK, DebugType.INFO);
                                DownloadQueue.RemoveAt(index);
                                break;
                            }
                        }
                        else if (filepath != null)
                        {
                            if (Path.Combine(queuedDownload.fullfilepath, queuedDownload.
      filename) == filepath)
                            {
                                DebugHandler.TraceMessage("Removed download at
       index: " + index.ToString() + " using filepath: " + filepath, DebugSource.TASK,
      DebugType.INFO);
                                DownloadQueue.RemoveAt(index);
                                break;
                            }
                        }
                        else
                        {
                            DebugHandler.TraceMessage("Could not remove download
       from queue, neither id or filepath is defined.", DebugSource.TASK,
      DebugType.WARNING);
                            JsonError error = new JsonError()
                            {
                                type = "remove_download_error",
                                errormessage = "Could not remove download from queue, neither id or
       filepath is defined.",
                                errortype = "warning"
                            };
                            toReturn = error.ToJObject();
                        }
                        index++;
                    }
                    if (CurrentlyDownloading.id != string.Empty)
                    {
                        await AbortDownload(id);
                    }
                    JsonDownloadQueue current = new
      JsonDownloadQueue()
                    {
                        downloadQueue = DownloadQueue
                    };
                    toReturn = current.ToJObject();
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage("Could not remove download from queue
       by download json: " + e.ToString(), DebugSource.TASK, DebugType.ERROR);
                    JsonError error = new JsonError()
                    {
                        type = "remove_download_error",
                        errormessage = "Could not remove download from queue by download json.",
                        errortype = "exception"
                    };
                    toReturn = error.ToJObject();
                }
            });
            return toReturn;
        }
StopQueue()
JObject LittleWeebLibrary.Handlers.DownloadHandler.StopQueue ()
Implements LittleWeebLibrary.Handlers.IDownloadHandler.
Definition at line 225 of file DownloadHandler.cs.
References LittleWeebLibrary.Models.JsonSuccess.ToJObject(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.StartUp.Stop().
        {
            DebugHandler.TraceMessage("StopQueue Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            Stop = true;
            JsonSuccess succes = new JsonSuccess()
            {
                message = "Succesfully told queue to stop running."
            };
            return succes.ToJObject();
        }
GetCurrentlyDownloading()
JObject LittleWeebLibrary.Handlers.DownloadHandler.GetCurrentlyDownloading ()
Implements LittleWeebLibrary.Handlers.IDownloadHandler.
Definition at line 240 of file DownloadHandler.cs.
References LittleWeebLibrary.Models.JsonDownloadInfo.ToJObject(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("GetCurrentlyDownloading Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            return CurrentlyDownloading.ToJObject();
        }
OnIrcClientDownloadEvent()
async void LittleWeebLibrary.Handlers.DownloadHandler.OnIrcClientDownloadEvent (object sender, IrcClientDownloadEventArgs args) [private]
Definition at line 246 of file DownloadHandler.cs.
References LittleWeebLibrary.Handlers.FileHistoryHandler.AddFileToFileHistory(), LittleWeebLibrary.Models.JsonDownloadInfo.anime_id, LittleWeebLibrary.Models.JsonDownloadInfo.anime_name, LittleWeebLibrary.Models.JsonDownloadInfo.bot, LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.DownloadProgress, LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.DownloadSpeed, LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.DownloadStatus, LittleWeebLibrary.Models.JsonDownloadInfo.episodeNumber, LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.FileLocation, LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.FileName, LittleWeebLibrary.Models.JsonDownloadInfo.filename, LittleWeebLibrary.Models.JsonDownloadInfo.filesize, LittleWeebLibrary.Models.JsonDownloadInfo.fullfilepath, LittleWeebLibrary.Models.JsonDownloadInfo.id, LittleWeebLibrary.Models.JsonDownloadInfo.pack, LittleWeebLibrary.Models.JsonDownloadInfo.progress, LittleWeebLibrary.Models.JsonDownloadInfo.season, LittleWeebLibrary.Models.JsonDownloadInfo.speed, LittleWeebLibrary.Models.JsonDownloadInfo.status, LittleWeebLibrary.EventArguments.IrcClientDownloadEventArgs.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnIrcClientDownloadEvent Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            if (CurrentlyDownloading != null)
            {
                if (args.DownloadStatus == "PARSING" || args.
      DownloadStatus == "WAITING")
                {
                    CurrentlyDownloading.progress = args.
      DownloadProgress.ToString();
                    CurrentlyDownloading.speed = args.
      DownloadSpeed.ToString();
                    CurrentlyDownloading.status = args.
      DownloadStatus;
                    CurrentlyDownloading.filename = args.
      FileName;
                    OnDownloadUpdateEvent?.Invoke(this, new
      DownloadUpdateEventArgs()
                    {
                        downloadInfo = CurrentlyDownloading
                    });
                }
                else
                {
                    CurrentlyDownloading.progress = args.
      DownloadProgress.ToString();
                    CurrentlyDownloading.speed = args.
      DownloadSpeed.ToString();
                    CurrentlyDownloading.status = args.
      DownloadStatus;
                    CurrentlyDownloading.filename = args.
      FileName;
                    CurrentlyDownloading.fullfilepath = args.
      FileLocation;
                    OnDownloadUpdateEvent?.Invoke(this, new
      DownloadUpdateEventArgs()
                    {
                        downloadInfo = CurrentlyDownloading
                    });
                }
                if (args.DownloadStatus.Contains("COMPLETED"))
                {
                    CurrentlyDownloading.progress = args.
      DownloadProgress.ToString();
                    CurrentlyDownloading.speed = args.
      DownloadSpeed.ToString();
                    CurrentlyDownloading.status = args.
      DownloadStatus;
                    CurrentlyDownloading.filename = args.
      FileName;
                    CurrentlyDownloading.fullfilepath = args.
      FileLocation;
                    OnDownloadUpdateEvent?.Invoke(this, new
      DownloadUpdateEventArgs()
                    {
                        downloadInfo = CurrentlyDownloading
                    });
                    await FileHistoryHandler.
      AddFileToFileHistory(new JsonDownloadedInfo()
                    {
                        anime_id = CurrentlyDownloading.
      anime_id,
                        anime_name = CurrentlyDownloading.
      anime_name,
                        id = CurrentlyDownloading.id,
                        season = CurrentlyDownloading.season,
                        episodeNumber = CurrentlyDownloading.
      episodeNumber,
                        bot = CurrentlyDownloading.bot,
                        pack = CurrentlyDownloading.pack,
                        filename = CurrentlyDownloading.
      filename,
                        filesize = CurrentlyDownloading.
      filesize,
                        fullfilepath = CurrentlyDownloading.
      fullfilepath
                    });
                    if (CurrentlyDownloading.id != string.Empty)
                    {
                        await RemoveDownload(CurrentlyDownloading.
      id);
                        CurrentlyDownloading = new
      JsonDownloadInfo();
                    }
                    DownloadProcesOnGoing = false;
                }
                else if (args.DownloadStatus.Contains("FAILED") || args.
      DownloadStatus.Contains("ABORTED"))
                {
                    if (CurrentlyDownloading.id != string.Empty)
                    {
                        await RemoveDownload(CurrentlyDownloading.
      id);
                        CurrentlyDownloading = new
      JsonDownloadInfo();
                    }
                    DownloadProcesOnGoing = false;
                }
            }
            else
            {
                DebugHandler.TraceMessage("Got download event, but no
       CurrrentlyDownloading object has been set!", DebugSource.TASK, DebugType.WARNING);
            }
        }
DownloadQueueHandler()
async Task LittleWeebLibrary.Handlers.DownloadHandler.DownloadQueueHandler () [private]
Definition at line 340 of file DownloadHandler.cs.
References LittleWeebLibrary.Handlers.IrcClientHandler.StartDownload(), LittleWeebLibrary.Models.JsonDownloadInfo.ToJson(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("DownloadQueueHandler Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            while (!Stop)
            {
                if (DownloadQueue.Count > 0 && !
      DownloadProcesOnGoing)
                {
                    DownloadProcesOnGoing = true;
                    CurrentlyDownloading = DownloadQueue[0];
                    DebugHandler.TraceMessage("Requesting start of the following
       download: " + CurrentlyDownloading.ToJson(), DebugSource.TASK,
      DebugType.INFO);
                    IrcClientHandler.StartDownload(
      CurrentlyDownloading);
                }
                await Task.Delay(1000);
            }
        }
SetIrcSettings()
void LittleWeebLibrary.Handlers.DownloadHandler.SetIrcSettings (IrcSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 362 of file DownloadHandler.cs.
References LittleWeebLibrary.Settings.IrcSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetIrcSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            IrcSettings = settings;
        }
SetLittleWeebSettings()
void LittleWeebLibrary.Handlers.DownloadHandler.SetLittleWeebSettings (LittleWeebSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 369 of file DownloadHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetLittleWeebSettings Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
        }
AbortDownload()
async Task<JObject> LittleWeebLibrary.Handlers.DownloadHandler.AbortDownload (string id = null)
Implements LittleWeebLibrary.Handlers.IDownloadHandler.
Definition at line 375 of file DownloadHandler.cs.
References LittleWeebLibrary.Models.JsonDownloadInfo.id, LittleWeebLibrary.Handlers.IrcClientHandler.IsDownloading(), LittleWeebLibrary.Handlers.IrcClientHandler.StopDownload(), LittleWeebLibrary.Models.JsonSuccess.ToJObject(), LittleWeebLibrary.Models.JsonError.ToJObject(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.AbortDownload().
        {
            DebugHandler.TraceMessage("AbortDownload Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("ID: " + id ,
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                if (IrcClientHandler.IsDownloading() &&
      DownloadProcesOnGoing)
                {
                    if (CurrentlyDownloading.id == id)
                    {
                        DebugHandler.TraceMessage("Stopping the current download!",
       DebugSource.TASK, DebugType.INFO);
                        IrcClientHandler.StopDownload();
                    }
                }
                while (IrcClientHandler.IsDownloading())
                {
                    DebugHandler.TraceMessage("Current download still running!",
      DebugSource.TASK, DebugType.INFO);
                    await Task.Delay(100);
                }
                DebugHandler.TraceMessage("Current download stopped!",
      DebugSource.TASK, DebugType.INFO);
                JsonSuccess succes = new JsonSuccess()
                {
                    message = "Succesfully aborted download from download queue by download json."
                };
                return succes.ToJObject();
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Could not remove download from queue by
       download json and stop the download.", DebugSource.TASK, DebugType.WARNING);
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError error = new JsonError()
                {
                    type = "remove_download_error",
                    errormessage = "Could not remove download from queue by download json.",
                    errortype = "exception"
                };
                return error.ToJObject();
            }
        }
AddDownloads()
async Task<JObject> LittleWeebLibrary.Handlers.DownloadHandler.AddDownloads (List< JsonDownloadInfo > download)
Implements LittleWeebLibrary.Handlers.IDownloadHandler.
Definition at line 422 of file DownloadHandler.cs.
References LittleWeebLibrary.Models.JsonDownloadInfo.filesize, LittleWeebLibrary.Settings.IrcSettings.fullfilepath, LittleWeebLibrary.StaticClasses.UtilityMethods.GetFreeSpaceKbits(), LittleWeebLibrary.Models.JsonDownloadQueue.ToJObject(), LittleWeebLibrary.Models.JsonError.ToJObject(), LittleWeebLibrary.Models.JsonError.ToString(), LittleWeebLibrary.Models.JsonDownloadInfo.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.AddDownloads().
        {
            DebugHandler.TraceMessage("AddDownloads Called.",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            JObject toReturn = new JObject();
            await Task.Run(() =>
            {
                try
                {
                    long totalSizeNeeded = 0;
                    foreach (JsonDownloadInfo downloadinfo in download)
                    {
                        DebugHandler.TraceMessage(downloadinfo.
      ToString(), DebugSource.TASK, DebugType.PARAMETERS);
                        totalSizeNeeded += int.Parse(downloadinfo.filesize);
                    }
                    if (UtilityMethods.GetFreeSpaceKbits(
      IrcSettings.fullfilepath) > totalSizeNeeded)
                    {
                        DownloadQueue.AddRange(download);
                        DebugHandler.TraceMessage("Succesfully added " + download.
      Count + " downloads to download queue.", DebugSource.TASK, DebugType.INFO);
                        JsonDownloadQueue current = new
      JsonDownloadQueue()
                        {
                            downloadQueue = DownloadQueue
                        };
                        toReturn = current.ToJObject();
                    }
                    else
                    {
                        DebugHandler.TraceMessage("Could not add downloads with
       filesize: " + totalSizeNeeded + " due to insufficient space required: " + (
      UtilityMethods.GetFreeSpaceKbits(IrcSettings.
      fullfilepath)).ToString(), DebugSource.TASK, DebugType.WARNING);
                        JsonError error = new JsonError()
                        {
                            type = "unsufficient_space_error",
                            errormessage = "Could not add download with filesize: " + totalSizeNeeded + "
       due to insufficient space required: " + (UtilityMethods.
      GetFreeSpaceKbits(IrcSettings.fullfilepath)).ToString(),
                            errortype = "warning"
                        };
                        toReturn = error.ToJObject();
                    }
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage("Could not add downloads: " + e.
      ToString(), DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "add_download_error",
                        errormessage = "Could not add download to queue.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    toReturn = error.ToJObject();
                }
            });
            return toReturn;
        }
IdGenerator()
int LittleWeebLibrary.Handlers.DownloadHandler.IdGenerator (string animeId, string botName, string packnum, string episode, string season) [private]
Definition at line 483 of file DownloadHandler.cs.
        {
            string combined = "";
            combined += animeId;
            combined += botName;
            combined += packnum;
            combined += episode;
            combined += season;
            return combined.GetHashCode();
        }
Member Data Documentation
IrcClientHandler
readonly IIrcClientHandler LittleWeebLibrary.Handlers.DownloadHandler.IrcClientHandler [private]
Definition at line 30 of file DownloadHandler.cs.
FileHistoryHandler
readonly IFileHistoryHandler LittleWeebLibrary.Handlers.DownloadHandler.FileHistoryHandler [private]
Definition at line 31 of file DownloadHandler.cs.
FileHandler
readonly IFileHandler LittleWeebLibrary.Handlers.DownloadHandler.FileHandler [private]
Definition at line 32 of file DownloadHandler.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.DownloadHandler.DebugHandler [private]
Definition at line 33 of file DownloadHandler.cs.
Stop
bool LittleWeebLibrary.Handlers.DownloadHandler.Stop [private]
Definition at line 35 of file DownloadHandler.cs.
DownloadProcesOnGoing
bool LittleWeebLibrary.Handlers.DownloadHandler.DownloadProcesOnGoing = false [private]
Definition at line 36 of file DownloadHandler.cs.
CurrentlyDownloading
JsonDownloadInfo LittleWeebLibrary.Handlers.DownloadHandler.CurrentlyDownloading [private]
Definition at line 37 of file DownloadHandler.cs.
IrcSettings
IrcSettings LittleWeebLibrary.Handlers.DownloadHandler.IrcSettings [private]
Definition at line 38 of file DownloadHandler.cs.
DownloadQueue
List<JsonDownloadInfo> LittleWeebLibrary.Handlers.DownloadHandler.DownloadQueue [private]
Definition at line 39 of file DownloadHandler.cs.
Event Documentation
OnDownloadUpdateEvent
EventHandler<DownloadUpdateEventArgs> LittleWeebLibrary.Handlers.DownloadHandler.OnDownloadUpdateEvent
Definition at line 27 of file DownloadHandler.cs.
The documentation for this class was generated from the following file:
Handlers/DownloadHandler.cs