LittleWeebLibrary.Controllers.FileWebSocketController Class Reference
Public Member Functions
FileWebSocketController (IWebSocketHandler webSocketHandler, IFileWebSocketService fileWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IFileWebSocketService FileWebSocketService
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 12 of file FileWebSocketController.cs.
Constructor & Destructor Documentation
FileWebSocketController()
LittleWeebLibrary.Controllers.FileWebSocketController.FileWebSocketController (IWebSocketHandler webSocketHandler, IFileWebSocketService fileWebSocketService, IDebugHandler debugHandler)
Definition at line 21 of file FileWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            FileWebSocketService = fileWebSocketService;
            WebSocketHandler = webSocketHandler;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 31 of file FileWebSocketController.cs.
References LittleWeebLibrary.Services.FileWebSocketService.DeleteFile(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Services.FileWebSocketService.OpenFile(), LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try{
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        JObject extra = query.Value<JObject>("extra");
                        if (extra != null)
                        {
                            switch (action)
                            {
                                case "delete_file":
                                    FileWebSocketService.
      DeleteFile(extra);
                                    break;
                                case "open_file":
                                    FileWebSocketService.
      OpenFile(extra);
                                    break;
                            }
                        }
                    
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
FileWebSocketService
readonly IFileWebSocketService LittleWeebLibrary.Controllers.FileWebSocketController.FileWebSocketService [private]
Definition at line 17 of file FileWebSocketController.cs.
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.FileWebSocketController.WebSocketHandler [private]
Definition at line 18 of file FileWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.FileWebSocketController.DebugHandler [private]
Definition at line 19 of file FileWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/FileWebSocketController.cs