LittleWeebLibrary.Handlers.FileHandler Class Reference
Public Member Functions
FileHandler (IDebugHandler debugHandler)
string DeleteFile (string filePath, string fileName=null)
string OpenFile (string filePath, string fileName=null)
void SetIrcSettings (IrcSettings settings)
void SetLittleWeebSettings (LittleWeebSettings settings)
Private Attributes
readonly IDebugHandler DebugHandler
LittleWeebSettings LittleWeebSettings
Detailed Description
Definition at line 23 of file FileHandler.cs.
Constructor & Destructor Documentation
FileHandler()
LittleWeebLibrary.Handlers.FileHandler.FileHandler (IDebugHandler debugHandler)
Definition at line 30 of file FileHandler.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor called", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
        }
Member Function Documentation
OpenFile()
string LittleWeebLibrary.Handlers.FileHandler.OpenFile (string filePath, string fileName = null)
Implements LittleWeebLibrary.Handlers.IFileHandler.
Definition at line 36 of file FileHandler.cs.
References LittleWeebLibrary.StaticClasses.UtilityMethods.CheckOperatingSystems(), LittleWeebLibrary.Models.JsonSuccess.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.FileWebSocketService.OpenFile().
        {
            DebugHandler.TraceMessage("OpenFile called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("FilePath: " + filePath,
      DebugSource.TASK, DebugType.PARAMETERS);
            string fullFilePath = filePath;
            if (fileName != null)
            {
                DebugHandler.TraceMessage("FileName: " + fileName,
      DebugSource.TASK, DebugType.PARAMETERS);
                fullFilePath = Path.Combine(filePath, fileName);
                DebugHandler.TraceMessage("Full Filepath: " + fullFilePath,
      DebugSource.TASK, DebugType.INFO);
            }
            try
            {
                for (int i = 0; i < 20; i++)
                {
                    if (File.Exists(fullFilePath))
                    {
#if __ANDROID__
                        Android.Net.Uri uri = Android.Net.Uri.Parse(fullFilePath);
                        Intent intent = new Intent(Intent.ActionView);
                        intent.SetDataAndType(uri, "video/*");
                        intent.SetFlags(ActivityFlags.ClearWhenTaskReset | ActivityFlags.NewTask);
                        Android.App.Application.Context.StartActivity(intent);
#else
                        if (UtilityMethods.CheckOperatingSystems() ==
      UtilityMethods.OperatingSystems.OsX)
                        {
                            Process.Start("open", fullFilePath);
                        }
                        else
                        {
                            var p = new Process
                            {
                                StartInfo = new ProcessStartInfo(fullFilePath)
                                {
                                    UseShellExecute = true
                                }
                            };
                            p.Start();
                        }
#endif
                        JsonSuccess report = new JsonSuccess()
                        {
                            message = "Succesfully opened file with path: " + fullFilePath
                        };
                        return report.ToJson();
                    }
                    Thread.Sleep(200);
                }
                JsonError jsonError = new JsonError
                {
                    type = "open_file_failed",
                    errormessage = "Could not open file but didn't throw exception.",
                    errortype = "warning",
                    exception = "none"
                };
                DebugHandler.TraceMessage("Could not open file but didn't throw
       exception, file: " + fullFilePath, DebugSource.TASK, DebugType.WARNING);
                return jsonError.ToJson();
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Could not open file. " + fullFilePath,
      DebugSource.TASK, DebugType.WARNING);
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError jsonError = new JsonError
                {
                    type = "open_file_failed",
                    errormessage = "Could not open file.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                return jsonError.ToJson();
            }
        }
DeleteFile()
string LittleWeebLibrary.Handlers.FileHandler.DeleteFile (string filePath, string fileName = null)
Implements LittleWeebLibrary.Handlers.IFileHandler.
Definition at line 126 of file FileHandler.cs.
References LittleWeebLibrary.Models.JsonSuccess.ToJson(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.FileWebSocketService.DeleteFile().
        {
            DebugHandler.TraceMessage("DeleteFile called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("FilePath: " + filePath,
      DebugSource.TASK, DebugType.PARAMETERS);
            string fullFilePath = filePath;
            if (fileName != null)
            {
                DebugHandler.TraceMessage("FileName: " + fileName,
      DebugSource.TASK, DebugType.PARAMETERS);
                fullFilePath = Path.Combine(filePath, fileName);
                DebugHandler.TraceMessage("Full File Path: " + fullFilePath,
      DebugSource.TASK, DebugType.INFO);
            }
            try
            {
                if (File.Exists(fullFilePath))
                {
                    File.Delete(fullFilePath);
                    string[] filePaths = Directory.GetFiles(Path.GetDirectoryName(filePath));
                    if (filePaths.Length == 0)
                    {
                        Directory.Delete(filePath);
                        DebugHandler.TraceMessage("Succesfully deleted file: " +
      fullFilePath + " & empty directory: " + filePath, DebugSource.TASK,
      DebugType.INFO);
                        JsonSuccess report = new JsonSuccess()
                        {
                            message = "Succesfully deleted file with path: " + fullFilePath + " and
       directory: " + filePath
                        };
                        return report.ToJson();
                    }
                    else
                    {
                        DebugHandler.TraceMessage("Succesfully deleted file: " +
      fullFilePath , DebugSource.TASK, DebugType.INFO);
                        JsonSuccess report = new JsonSuccess()
                        {
                            message = "Succesfully deleted file with path: " + fullFilePath
                        };
                        return report.ToJson();
                    }
                }
                else
                {
                    DebugHandler.TraceMessage("File: " + fullFilePath + " does not
       exist, possibly already deleted.", DebugSource.TASK, DebugType.INFO);
                    JsonSuccess report = new JsonSuccess()
                    {
                        message = "File with filepath: " + fullFilePath + " already removed."
                    };
                    return report.ToJson();
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage("Failed to delete file: " + fullFilePath,
       DebugSource.TASK, DebugType.WARNING);
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                JsonError jsonError = new JsonError
                {
                    type = "delete_file_failed",
                    errormessage = "Could not delete file.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                return jsonError.ToJson();
            }
        }
SetIrcSettings()
void LittleWeebLibrary.Handlers.FileHandler.SetIrcSettings (IrcSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 207 of file FileHandler.cs.
        {
        }
SetLittleWeebSettings()
void LittleWeebLibrary.Handlers.FileHandler.SetLittleWeebSettings (LittleWeebSettings settings)
Implements LittleWeebLibrary.GlobalInterfaces.ISettingsInterface.
Definition at line 211 of file FileHandler.cs.
References LittleWeebLibrary.Settings.LittleWeebSettings.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("SetLittleWeebSettings called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(settings.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            LittleWeebSettings = settings;
        }
Member Data Documentation
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.FileHandler.DebugHandler [private]
Definition at line 27 of file FileHandler.cs.
LittleWeebSettings
LittleWeebSettings LittleWeebLibrary.Handlers.FileHandler.LittleWeebSettings [private]
Definition at line 28 of file FileHandler.cs.
The documentation for this class was generated from the following file:
Handlers/FileHandler.cs