LittleWeebLibrary.Controllers.IrcWebSocketController Class Reference
Public Member Functions
IrcWebSocketController (IWebSocketHandler webSocketHandler, IIrcWebSocketService ircWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IIrcWebSocketService IrcWebSocketService
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 12 of file IrcWebSocketController.cs.
Constructor & Destructor Documentation
IrcWebSocketController()
LittleWeebLibrary.Controllers.IrcWebSocketController.IrcWebSocketController (IWebSocketHandler webSocketHandler, IIrcWebSocketService ircWebSocketService, IDebugHandler debugHandler)
Definition at line 21 of file IrcWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            IrcWebSocketService = ircWebSocketService;
            WebSocketHandler = webSocketHandler;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 29 of file IrcWebSocketController.cs.
References LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.IrcWebSocketService.DisableSendMessage(), LittleWeebLibrary.Services.IrcWebSocketService.Disconnect(), LittleWeebLibrary.Services.IrcWebSocketService.EnableSendMessage(), LittleWeebLibrary.Services.IrcWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Services.IrcWebSocketService.SendMessage(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try{
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        JObject extra = query.Value<JObject>("extra");
                        if (extra != null)
                        {
                            switch (action)
                            {
                                case "connect_irc":
                                    IrcWebSocketService.
      Connect(extra);
                                    break;
                                case "sendmessage_irc":
                                    IrcWebSocketService.
      SendMessage(extra);
                                    break;
                            }
                        }
                        else
                        {
                            switch (action)
                            {
                                case "get_irc_data":
                                    IrcWebSocketService.
      GetCurrentIrcSettings();
                                    break;
                                case "connect_irc":
                                    IrcWebSocketService.
      Connect();
                                    break;
                                case "disconnect_irc":
                                    IrcWebSocketService.
      Disconnect();
                                    break;
                                case "enablechat_irc":
                                    IrcWebSocketService.
      EnableSendMessage();
                                    break;
                                case "disablechat_irc":
                                    IrcWebSocketService.
      DisableSendMessage();
                                    break;
                            }
                        }
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
IrcWebSocketService
readonly IIrcWebSocketService LittleWeebLibrary.Controllers.IrcWebSocketController.IrcWebSocketService [private]
Definition at line 17 of file IrcWebSocketController.cs.
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.IrcWebSocketController.WebSocketHandler [private]
Definition at line 18 of file IrcWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.IrcWebSocketController.DebugHandler [private]
Definition at line 19 of file IrcWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/IrcWebSocketController.cs