LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController Class Reference
Public Member Functions
SettingsWebSocketController (IWebSocketHandler webSocketHandler, ISettingsWebSocketService settingsWebSocketService, IDebugHandler debugHandler)
void OnWebSocketEvent (WebSocketEventArgs args)
Private Attributes
readonly IDebugHandler DebugHandler
readonly ISettingsWebSocketService SettingsWebSocketService
readonly IWebSocketHandler WebSocketHandler
Detailed Description
Definition at line 12 of file SettingsWebSocketController.cs.
Constructor & Destructor Documentation
SettingsWebSocketController()
LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.SettingsWebSocketController (IWebSocketHandler webSocketHandler, ISettingsWebSocketService settingsWebSocketService, IDebugHandler debugHandler)
Definition at line 21 of file SettingsWebSocketController.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called.",
      DebugSource.CONSTRUCTOR, DebugType.ENTRY_EXIT);
            DebugHandler = debugHandler;
            SettingsWebSocketService = settingsWebSocketService;
            WebSocketHandler = webSocketHandler;
        }
Member Function Documentation
OnWebSocketEvent()
void LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent (WebSocketEventArgs args)
Implements LittleWeebLibrary.Controllers.ISubWebSocketController.
Definition at line 30 of file SettingsWebSocketController.cs.
References LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.GetCurrentLittleWeebSettings(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.Message, LittleWeebLibrary.Handlers.WebSocketHandler.SendMessage(), LittleWeebLibrary.Services.SettingsWebSocketService.Setfullfilepath(), LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Models.JsonError.ToJson(), LittleWeebLibrary.EventArguments.WebSocketEventArgs.ToString(), LittleWeebLibrary.Models.JsonError.ToString(), and LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("OnWebSocketEvent Called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage(args.ToString(),
      DebugSource.TASK, DebugType.PARAMETERS);
            try
            {
                try{
                    JObject query = JObject.Parse(args.Message);
                    string action = query.Value<string>("action");
                    if (action != null)
                    {
                        JObject extra = query.Value<JObject>("extra");
                        if (extra != null)
                        {
                            switch (action)
                            {
                                case "set_littleweeb_settings":
                                    SettingsWebSocketService.
      SetLittleWeebSettings(extra);
                                    break;
                                case "set_irc_settings":
                                    SettingsWebSocketService.
      SetIrcSettings(extra);
                                    break;
                                case "set_download_directory":
                                    SettingsWebSocketService.
      Setfullfilepath(extra);
                                    break;
                            }
                        }
                        else
                        {
                            switch (action)
                            {
                                case "get_littleweeb_settings":
                                    SettingsWebSocketService.
      GetCurrentLittleWeebSettings();
                                    break;
                                case "get_irc_settings":
                                    SettingsWebSocketService.
      GetCurrentIrcSettings();
                                    break;
                            }
                        }
                    }
                }
                catch (JsonReaderException e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    JsonError error = new JsonError()
                    {
                        type = "command_error",
                        errormessage = "Error happend during parsing of command.",
                        errortype = "exception",
                        exception = e.ToString()
                    };
                    WebSocketHandler.SendMessage(error.
      ToJson());
                }
            }
            catch (Exception e)
            {
                DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.ERROR);
                JsonError error = new JsonError()
                {
                    type = "command_error",
                    errormessage = "Error happend during execution of command.",
                    errortype = "exception",
                    exception = e.ToString()
                };
                WebSocketHandler.SendMessage(error.
      ToJson());
            }
        }
Member Data Documentation
SettingsWebSocketService
readonly ISettingsWebSocketService LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.SettingsWebSocketService [private]
Definition at line 17 of file SettingsWebSocketController.cs.
WebSocketHandler
readonly IWebSocketHandler LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.WebSocketHandler [private]
Definition at line 18 of file SettingsWebSocketController.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.DebugHandler [private]
Definition at line 19 of file SettingsWebSocketController.cs.
The documentation for this class was generated from the following file:
Controllers/SubControllers/SettingsWebSocketController.cs