LittleWeebLibrary.Handlers.NiblHandler Class Reference
Public Member Functions
NiblHandler (IKitsuHandler kitsuHandler, IDebugHandler debugHandler)
async Task< JObject > GetBotList ()
async Task< int > GetLatestEpisode (string query)
async Task< JObject > GetLatestFiles (string botid)
async Task< JObject > SearchNibl (string query)
async Task< JObject > SearchNibl (List< string > query, int episode=-1, string sort=`name`, string order=`ASC`)
Private Member Functions
async Task< string > Get (string url)
Private Attributes
readonly IDebugHandler DebugHandler
readonly IKitsuHandler KitsuHandler
WeebFileNameParser WeebFileNameParser
Detailed Description
Definition at line 27 of file NiblHandler.cs.
Constructor & Destructor Documentation
NiblHandler()
LittleWeebLibrary.Handlers.NiblHandler.NiblHandler (IKitsuHandler kitsuHandler, IDebugHandler debugHandler)
Definition at line 32 of file NiblHandler.cs.
References LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage().
        {
            debugHandler.TraceMessage("Constructor Called", DebugSource.CONSTRUCTOR,
      DebugType.ENTRY_EXIT);
            KitsuHandler = kitsuHandler;
            WeebFileNameParser = new WeebFileNameParser();
            DebugHandler = debugHandler;
        }
Member Function Documentation
GetBotList()
async Task<JObject> LittleWeebLibrary.Handlers.NiblHandler.GetBotList ()
Implements LittleWeebLibrary.Handlers.INiblHandler.
Definition at line 40 of file NiblHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Services.InfoApiWebSocketService.GetBotList().
        {
            DebugHandler.TraceMessage("GetBotList called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            string bots = await Get("bots");
            if (bots.Contains("failed:"))
            {
                return new JObject();
            }
            else
            {
                JObject result = JObject.Parse(bots);
                Dictionary<int, string> botVsId = new Dictionary<int, string>();
                foreach (JObject bot in result.Value<JArray>("content"))
                {
                    string name = bot.Value<string>("name");
                    int id = bot.Value<int>("id");
                    try
                    {
                        botVsId.Add(id, name);
                    }
                    catch
                    {
                        DebugHandler.TraceMessage("Could not add BOT: " + name + "
       with id : " + id + ", id already exists!", DebugSource.TASK, DebugType.WARNING);
                    }
                }
                return JObject.FromObject(botVsId);
            }
        }
GetLatestFiles()
async Task<JObject> LittleWeebLibrary.Handlers.NiblHandler.GetLatestFiles (string botid)
Implements LittleWeebLibrary.Handlers.INiblHandler.
Definition at line 76 of file NiblHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.GetCurrentlyAiring().
        {
            DebugHandler.TraceMessage("GetLatestFiles called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Bot ID: " + botid,
      DebugSource.TASK, DebugType.PARAMETERS);
            JObject bots = await GetBotList();
            string filesresult = await Get("packs/" + botid + "
      /page?episodeNumber=0&page=0&size=500&sort=lastModified&direction=DESC");
                                          
            if (filesresult.Contains("failed:"))
            {
                return new JObject();
            }
            else
            {
                var result = (JObject)JsonConvert.DeserializeObject(filesresult);
                List<Dictionary<string, string>> listWithPacks = new List<Dictionary<string, string>>();
                JArray array = result.Value<JArray>("content");
                try
                {
                    foreach (JObject pack in array.Children())
                    {
                        Dictionary<string, string> info = WeebFileNameParser.
      ParseFullString(pack.Value<string>("name"));
                        info.Add("BotName", bots.Value<string>(pack.Value<string>("botId")));
                        info.Add("PackNumber", pack.Value<string>("number"));
                        info.Add("FullFileName", pack.Value<string>("name"));
                        info.Add("FileSize", pack.Value<long>("sizekbits").ToString());
                        listWithPacks.Add(info);
                    }
                }
                catch(Exception e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                }
                return JObject.Parse("{\"bot\":\"" + bots.Value<string>(botid) + "\",\"packs\":" +
      JsonConvert.SerializeObject(listWithPacks) + " }");
            }
        }
SearchNibl() [1/2]
async Task<JObject> LittleWeebLibrary.Handlers.NiblHandler.SearchNibl (string query)
Implements LittleWeebLibrary.Handlers.INiblHandler.
Definition at line 118 of file NiblHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.AnimeLatestEpisode(), LittleWeebLibrary.Handlers.AnimeProfileHandler.GetAnimeEpisodes(), and LittleWeebLibrary.Services.InfoApiWebSocketService.GetFilesForAnime().
        {
            DebugHandler.TraceMessage("SearchNibl called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("Search query: " + query,
      DebugSource.TASK, DebugType.PARAMETERS);
            string searchresult = await Get("search?query=" + query);
            if (searchresult.Contains("failed:"))
            {
                DebugHandler.TraceMessage("Search query: " + query + " FAILED.",
      DebugSource.TASK, DebugType.WARNING);
                return new JObject();
            }
            else
            {
                DebugHandler.TraceMessage("Search query: " + query + " SUCCEEDED.",
       DebugSource.TASK, DebugType.INFO);
                List<Dictionary<string, string>> listWithPacks = new List<Dictionary<string, string>>();
                try
                {
                    JObject bots = await GetBotList();
                    JObject result = JObject.Parse(searchresult);
                    JArray array = result.Value<JArray>("content");
                    foreach (JObject pack in array.Children())
                    {
                        Dictionary<string, string> info = WeebFileNameParser.
      ParseFullString(pack.Value<string>("name"));
                        info.Add("BotName", bots.Value<string>(pack.Value<string>("botId")));
                        info.Add("PackNumber", pack.Value<string>("number"));
                        info.Add("FullFileName", pack.Value<string>("name"));
                        info.Add("FileSize", pack.Value<long>("sizekbits").ToString());
                        listWithPacks.Add(info);
                    }
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                }
                DebugHandler.TraceMessage("Search query: " + query + " Succeeded.",
       DebugSource.TASK, DebugType.INFO);
                return JObject.Parse("{\"packs\":" + JsonConvert.SerializeObject(listWithPacks) + " }");
            }
        }
SearchNibl() [2/2]
async Task<JObject> LittleWeebLibrary.Handlers.NiblHandler.SearchNibl (List< string > query, int episode = -1, string sort = `name`, string order = `ASC`)
Implements LittleWeebLibrary.Handlers.INiblHandler.
Definition at line 163 of file NiblHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            List<string> urls = new List<string>();
            foreach(string searchquery in query)
            {
                if (episode > 0)
                {
                    urls.Add("search/page?query=" + searchquery + "&size=4000&sort=" + sort + "&direction="
       + order + "&episodeNumber=" + episode.ToString());
                }
                else
                {
                    urls.Add("search/page?query=" + searchquery + "&size=4000&sort=" + sort + "&direction="
       + order);
                }
            }
            List<Task<string>> tasks = new List<Task<string>>();
            foreach (string url in urls)
            {
                tasks.Add(Get(url));
            }
            await Task.WhenAll(tasks.ToArray());
            JObject result = new JObject();
          
            foreach (Task<string> task in tasks)
            {
                result.Merge(JObject.Parse(task.Result));
                task.Dispose();
            }
            JObject bots = await GetBotList();
            JArray array = result.Value<JArray>("content");
            List<Dictionary<string, string>> listWithPacks = new List<Dictionary<string, string>>();
            foreach (JObject pack in array.Children())
            {
                Dictionary<string, string> info = WeebFileNameParser.ParseFullString(pack
      .Value<string>("name"));
                info.Add("BotName", bots.Value<string>(pack.Value<string>("botId")));
                info.Add("PackNumber", pack.Value<string>("number"));
                info.Add("FullFileName", pack.Value<string>("name"));
                info.Add("FileSize", pack.Value<long>("sizekbits").ToString());
                listWithPacks.Add(info);
            }
            DebugHandler.TraceMessage("Search query: " + query + " Succeeded. Total
       Results: " + array.Count(), DebugSource.TASK, DebugType.INFO);
            return JObject.Parse("{\"packs\":" + JsonConvert.SerializeObject(listWithPacks) + " }");
        }
GetLatestEpisode()
async Task<int> LittleWeebLibrary.Handlers.NiblHandler.GetLatestEpisode (string query)
Implements LittleWeebLibrary.Handlers.INiblHandler.
Definition at line 215 of file NiblHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.AnimeLatestEpisode().
        {
            string searchresult = await Get("search/page?query=" + query + "
      &episodeNumber=0&page=0&size=100&sort=episodeNumber&direction=DESC");
            int season = -1;
            Dictionary<string, string> parsedquery = WeebFileNameParser.ParseFullString(
      query);
            if (parsedquery.ContainsKey("Season"))
            {
                season = int.Parse(parsedquery["Season"]);
            }
            if (searchresult.Contains("failed:"))
            {
                DebugHandler.TraceMessage("Search query: " + query + " FAILED.",
      DebugSource.TASK, DebugType.WARNING);
                return -1;
            }
            else
            {
                DebugHandler.TraceMessage("Search query: " + query + " SUCCEEDED.",
       DebugSource.TASK, DebugType.INFO);
                try
                {
                    JObject result = JObject.Parse(searchresult);
                    JArray array = result.Value<JArray>("content");
                    int largest = 0;
                    foreach (JObject pack in array.Children())
                    {
                        Dictionary<string, string> info = WeebFileNameParser.
      ParseFullString(pack.Value<string>("name"));
                        if (season != -1)
                        {
                            if (info.ContainsKey("Season"))
                            {
                                if (int.Parse(info["Season"]) == season)
                                {
                                    if (pack.Value<int>("episodeNumber") > largest)
                                    {
                                        largest = pack.Value<int>("episodeNumber");
                                    }
                                }
                            }
                        }
                        else
                        {
                            if (pack.Value<int>("episodeNumber") > largest)
                            {
                                largest = pack.Value<int>("episodeNumber");
                            }
                        }
                    }
                    int episodeNumber = largest;
                    return episodeNumber;
                    
                }
                catch (Exception e)
                {
                    DebugHandler.TraceMessage(e.ToString(),
      DebugSource.TASK, DebugType.WARNING);
                    return -1;
                }
            }
        }
Get()
async Task<string> LittleWeebLibrary.Handlers.NiblHandler.Get (string url) [private]
Definition at line 285 of file NiblHandler.cs.
References LittleWeebLibrary.Handlers.DebugHandler.TraceMessage().
        {
            DebugHandler.TraceMessage("Get called",
      DebugSource.TASK, DebugType.ENTRY_EXIT);
            DebugHandler.TraceMessage("URL: " + url,
      DebugSource.TASK, DebugType.PARAMETERS);
            using (HttpClient client = new HttpClient())
            {
                HttpResponseMessage response = await client.GetAsync("https://api.nibl.co.uk:8080/nibl/" +
      url);
                if (response.IsSuccessStatusCode)
                {
                    return await response.Content.ReadAsStringAsync();
                }
                else
                {
                    return "failed: " + response.StatusCode.ToString();
                }
            }
        }
Member Data Documentation
WeebFileNameParser
WeebFileNameParser LittleWeebLibrary.Handlers.NiblHandler.WeebFileNameParser [private]
Definition at line 29 of file NiblHandler.cs.
KitsuHandler
readonly IKitsuHandler LittleWeebLibrary.Handlers.NiblHandler.KitsuHandler [private]
Definition at line 30 of file NiblHandler.cs.
DebugHandler
readonly IDebugHandler LittleWeebLibrary.Handlers.NiblHandler.DebugHandler [private]
Definition at line 31 of file NiblHandler.cs.
The documentation for this class was generated from the following file:
Handlers/NiblHandler.cs