LittleWeebLibrary.Models.JsonError Class Reference
Public Member Functions
JObject ToJObject ()
string ToJson ()
override string ToString ()
Public Attributes
string type = `error`
Properties
string errormessage = string.Empty [get, set]
string errortype = string.Empty [get, set]
string updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get, set]
Detailed Description
Definition at line 7 of file JsonError.cs.
Member Function Documentation
ToJson()
string LittleWeebLibrary.Models.JsonError.ToJson ()
Definition at line 15 of file JsonError.cs.
Referenced by LittleWeebLibrary.Services.DownloadWebSocketService.AbortDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownloads(), LittleWeebLibrary.Services.InfoApiWebSocketService.AddRule(), LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.DirectoryWebSocketService.CreateDirectory(), LittleWeebLibrary.Handlers.DirectoryHandler.CreateDirectory(), LittleWeebLibrary.Services.DirectoryWebSocketService.DeleteDirectory(), LittleWeebLibrary.Handlers.DirectoryHandler.DeleteDirectory(), LittleWeebLibrary.Services.DataBaseWebSocketService.DeleteDocument(), LittleWeebLibrary.Services.FileWebSocketService.DeleteFile(), LittleWeebLibrary.Handlers.FileHandler.DeleteFile(), LittleWeebLibrary.Services.IrcWebSocketService.Disconnect(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllCategories(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetAllGenres(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetBotList(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetCollection(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.DirectoryHandler.GetDirectories(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDirectories(), LittleWeebLibrary.Services.DataBaseWebSocketService.GetDocument(), LittleWeebLibrary.Handlers.DirectoryHandler.GetDrives(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientConnectionStatusEvent(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientMessageEvent(), LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Handlers.DirectoryHandler.OpenDirectory(), LittleWeebLibrary.Handlers.FileHandler.OpenFile(), LittleWeebLibrary.Services.FileWebSocketService.OpenFile(), LittleWeebLibrary.Services.DownloadWebSocketService.RemoveDownload(), LittleWeebLibrary.Services.IrcWebSocketService.SendMessage(), LittleWeebLibrary.Services.SettingsWebSocketService.Setfullfilepath(), LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings(), LittleWeebLibrary.Services.DataBaseWebSocketService.StoreDocument(), and LittleWeebLibrary.Services.DataBaseWebSocketService.UpdateDocument().
        {
            return JsonConvert.SerializeObject(this);
        }
ToString()
override string LittleWeebLibrary.Models.JsonError.ToString ()
Definition at line 20 of file JsonError.cs.
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.AddDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownload(), LittleWeebLibrary.Services.DownloadWebSocketService.AddDownloads(), LittleWeebLibrary.Handlers.DownloadHandler.AddDownloads(), LittleWeebLibrary.Services.IrcWebSocketService.Connect(), LittleWeebLibrary.Services.DirectoryWebSocketService.CreateDirectory(), LittleWeebLibrary.Services.DirectoryWebSocketService.DeleteDirectory(), LittleWeebLibrary.Services.FileWebSocketService.DeleteFile(), LittleWeebLibrary.Handlers.FileHandler.DeleteFile(), LittleWeebLibrary.Services.IrcWebSocketService.Disconnect(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetCurrentlyAiring(), LittleWeebLibrary.Handlers.DirectoryHandler.GetDirectories(), LittleWeebLibrary.Services.DirectoryWebSocketService.GetDirectories(), LittleWeebLibrary.Handlers.DirectoryHandler.GetDrives(), LittleWeebLibrary.Services.InfoApiWebSocketService.GetFilesForAnime(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientConnectionStatusEvent(), LittleWeebLibrary.Services.IrcWebSocketService.OnIrcClientMessageEvent(), LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.IrcWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.FileWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Controllers.DownloadWebSocketController.OnWebSocketEvent(), LittleWeebLibrary.Handlers.FileHandler.OpenFile(), LittleWeebLibrary.Services.FileWebSocketService.OpenFile(), LittleWeebLibrary.Services.DownloadWebSocketService.RemoveDownload(), LittleWeebLibrary.Services.IrcWebSocketService.SendMessage(), LittleWeebLibrary.Services.SettingsWebSocketService.Setfullfilepath(), LittleWeebLibrary.Services.SettingsWebSocketService.SetIrcSettings(), and LittleWeebLibrary.Services.SettingsWebSocketService.SetLittleWeebSettings().
        {
            JObject jobject = ToJObject();
            string properties = string.Empty;
            foreach (var x in jobject)
            {
                properties += x.Key + ": " + x.Value.ToString();
            }
            return properties;
        }
ToJObject()
JObject LittleWeebLibrary.Models.JsonError.ToJObject ()
Definition at line 31 of file JsonError.cs.
Referenced by LittleWeebLibrary.Handlers.DownloadHandler.AbortDownload(), LittleWeebLibrary.Handlers.DownloadHandler.AddDownload(), LittleWeebLibrary.Handlers.DownloadHandler.AddDownloads(), and LittleWeebLibrary.Handlers.DownloadHandler.RemoveDownload().
        {
            JObject jobject = JObject.FromObject(this);
            return jobject;
        }
Member Data Documentation
type
string LittleWeebLibrary.Models.JsonError.type = `error`
Definition at line 9 of file JsonError.cs.
get
LittleWeebLibrary.Models.JsonError.get [private]
Definition at line 12 of file JsonError.cs.
set
LittleWeebLibrary.Models.JsonError.set [private]
Definition at line 12 of file JsonError.cs.
Property Documentation
errortype
string LittleWeebLibrary.Models.JsonError.errortype = string.Empty [get], [set]
Definition at line 10 of file JsonError.cs.
{ get; set; } = string.Empty;
errormessage
string LittleWeebLibrary.Models.JsonError.errormessage = string.Empty [get], [set]
Definition at line 11 of file JsonError.cs.
{ get; set; } = string.Empty;
updated
string LittleWeebLibrary.Models.JsonError.updated = StaticClasses.UtilityMethods.GetEpoch().ToString() [get], [set]
Definition at line 13 of file JsonError.cs.
{ get; set; } = StaticClasses.UtilityMethods.GetEpoch().ToString();
The documentation for this class was generated from the following file:
Models/JsonError.cs