LittleWeebLibrary.Handlers.IDebugHandler Interface Reference
Public Member Functions
void SetSettings (ISettingsHandler settingsHandler)
void StopDebugger ()
void TraceMessage (string message, DebugSource sourcetype, DebugType debugtype, [System.Runtime.CompilerServices.CallerMemberName] string memberName=``, [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath=``, [System.Runtime.CompilerServices.CallerLineNumber] int sourceLineNumber=0)
Detailed Description
Definition at line 19 of file DebugHandler.cs.
Member Function Documentation
StopDebugger()
void LittleWeebLibrary.Handlers.IDebugHandler.StopDebugger ()
Implemented in LittleWeebLibrary.Handlers.DebugHandler.
SetSettings()
void LittleWeebLibrary.Handlers.IDebugHandler.SetSettings (ISettingsHandler settingsHandler)
Implemented in LittleWeebLibrary.Handlers.DebugHandler.
TraceMessage()
void LittleWeebLibrary.Handlers.IDebugHandler.TraceMessage (string message, DebugSource sourcetype, DebugType debugtype, [System.Runtime.CompilerServices.CallerMemberName] string memberName = ``, [System.Runtime.CompilerServices.CallerFilePath] string sourceFilePath = ``, [System.Runtime.CompilerServices.CallerLineNumber] int sourceLineNumber = 0)
Implemented in LittleWeebLibrary.Handlers.DebugHandler.
Referenced by LittleWeebLibrary.Handlers.AnimeProfileHandler.AnimeProfileHandler(), LittleWeebLibrary.Handlers.AnimeRuleHandler.AnimeRuleHandler(), LittleWeebLibrary.Controllers.BaseWebSocketController.BaseWebSocketController(), LittleWeebLibrary.Handlers.DataBaseHandler.DataBaseHandler(), LittleWeebLibrary.Controllers.SubControllers.DataBaseWebSocketController.DataBaseWebSocketController(), LittleWeebLibrary.Services.DataBaseWebSocketService.DataBaseWebSocketService(), LittleWeebLibrary.Handlers.DirectoryHandler.DirectoryHandler(), LittleWeebLibrary.Controllers.SubControllers.DirectoryWebSocketController.DirectoryWebSocketController(), LittleWeebLibrary.Services.DirectoryWebSocketService.DirectoryWebSocketService(), LittleWeebLibrary.Handlers.DownloadHandler.DownloadHandler(), LittleWeebLibrary.Controllers.DownloadWebSocketController.DownloadWebSocketController(), LittleWeebLibrary.Services.DownloadWebSocketService.DownloadWebSocketService(), LittleWeebLibrary.Handlers.FileHandler.FileHandler(), LittleWeebLibrary.Handlers.FileHistoryHandler.FileHistoryHandler(), LittleWeebLibrary.Controllers.FileWebSocketController.FileWebSocketController(), LittleWeebLibrary.Services.FileWebSocketService.FileWebSocketService(), LittleWeebLibrary.Controllers.SubControllers.InfoApiWebSocketController.InfoApiWebSocketController(), LittleWeebLibrary.Services.InfoApiWebSocketService.InfoApiWebSocketService(), LittleWeebLibrary.Handlers.IrcClientHandler.IrcClientHandler(), LittleWeebLibrary.Controllers.IrcWebSocketController.IrcWebSocketController(), LittleWeebLibrary.Services.IrcWebSocketService.IrcWebSocketService(), LittleWeebLibrary.Handlers.KitsuHandler.KitsuHandler(), LittleWeebLibrary.Handlers.NiblHandler.NiblHandler(), LittleWeebLibrary.Handlers.SettingsHandler.SettingsHandler(), LittleWeebLibrary.Controllers.SubControllers.SettingsWebSocketController.SettingsWebSocketController(), LittleWeebLibrary.Services.SettingsWebSocketService.SettingsWebSocketService(), LittleWeebLibrary.Handlers.VersionHandler.VersionHandler(), LittleWeebLibrary.Controllers.SubControllers.VersionWebSocketController.VersionWebSocketController(), LittleWeebLibrary.Services.VersionWebSocketService.VersionWebSocketService(), and LittleWeebLibrary.Handlers.WebSocketHandler.WebSocketHandler().
The documentation for this interface was generated from the following file:
Handlers/DebugHandler.cs