LittleWeebLibrary.Handlers.ISettingsHandler Interface Reference
Public Member Functions
IrcSettings GetIrcSettings ()
LittleWeebSettings GetLittleWeebSettings ()
void WriteIrcSettings (IrcSettings ircSettings)
void WriteLittleWeebSettings (LittleWeebSettings littleWeebSettings)
Detailed Description
Definition at line 13 of file SettingsHandler.cs.
Member Function Documentation
GetIrcSettings()
IrcSettings LittleWeebLibrary.Handlers.ISettingsHandler.GetIrcSettings ()
Implemented in LittleWeebLibrary.Handlers.SettingsHandler.
Referenced by LittleWeebLibrary.Services.SettingsWebSocketService.SetSettingsClasses().
GetLittleWeebSettings()
LittleWeebSettings LittleWeebLibrary.Handlers.ISettingsHandler.GetLittleWeebSettings ()
Implemented in LittleWeebLibrary.Handlers.SettingsHandler.
Referenced by LittleWeebLibrary.Handlers.DebugHandler.SetSettings(), LittleWeebLibrary.Services.SettingsWebSocketService.SetSettingsClasses(), and LittleWeebLibrary.Handlers.WebSocketHandler.WebSocketHandler().
WriteIrcSettings()
void LittleWeebLibrary.Handlers.ISettingsHandler.WriteIrcSettings (IrcSettings ircSettings)
Implemented in LittleWeebLibrary.Handlers.SettingsHandler.
WriteLittleWeebSettings()
void LittleWeebLibrary.Handlers.ISettingsHandler.WriteLittleWeebSettings (LittleWeebSettings littleWeebSettings)
Implemented in LittleWeebLibrary.Handlers.SettingsHandler.
The documentation for this interface was generated from the following file:
Handlers/SettingsHandler.cs